### ISSUE TITLE
Can I add more function for my project?

### ISSUE THREAD

**Issue by JosephChang888** [artisan-roaster-scope/artisan#100]
Hi Mr. Makamo, 
I designed one Far IR Roaster this year, it's well down.
And I will like to add more function base on Artisan  for my Social Roaster in the second semi auto Roaster project.
Can you help me  to understand you source code, and how to to compile it on my controller?
Best Regards,

Joseph from Taiwan

**Comment by MAKOMO** [comment]
I have no resource to teach you the source code. Read it. Python source does not need any compilation. Anyhow, this software does not run on any controller. Sorry.
