### ISSUE TITLE
Feature Request: Custom Batch naming schemes 

### ISSUE THREAD

**Issue by loganshaw9** [artisan-roaster-scope/artisan#1010]
in our current workflow in my production facility we using date coding to follow around our bulk bags of coffee and keep them in order

each bulk bag consists of 2, 3 bags roasts

but it ends up just getting one date code

21118a would be one from today

each subsequent bag of the same blend would just go up one letter at the end

21118B would be the next bag of the same type

the next roast of a different blend would restart this process

the way batches work currently do not let me do this easily 

**Describe the solution you'd like**
i would like batches to be able to be named "blend" 21118aa the next batch to be "blend" 21118ab

and so forth automatically

**Describe alternatives you've considered**
we could switch date schemes but we have 100 plus stores and 5000 plus gas stations that are used to it so that makes it difficult 

could manually type it in somewhere but im not sure where and it takes extra time and can create more mistakes

**Additional context**
just really looking for more customization in batch naming to make things easier to keep track of especially for companies looking to make use of the software

**Comment by MAKOMO** [comment]
You can add any custom batch name to the name of the roast. Automatic batch numbers in Artisan are composed from a prefix and running number only. This will most likely not change in the near future as it works well for about everybody.

**Comment by loganshaw9** [comment]
Ok thanks for the reply

No worries appreciate the time
