### ISSUE TITLE
v2.4.6.dmg for mac

### ISSUE THREAD

**Issue by AlejoTuesta** [artisan-roaster-scope/artisan#1016]
i have installed artisan v2.4.2 in my Mac, but dosen't recognize phidgets temp in the program, all ready closed the Phidget app and docent work

**Comment by MAKOMO** [comment]
Why are you using an outdated Artisan version? Does the Phidget Control Panel show the temperatures from your modules?

**Comment by AlejoTuesta** [comment]
i Have a Mac mini with a lowest version of OS and th new artisan requires a new version,  th problem I hv is tt. artisan doesn't get information from the phidget but the phidget has data in the Mac, here some images:
![Captura de pantalla 2022-11-25 a la(s) 3 33 07 p  m](https://user-images.githubusercontent.com/119071825/204052957-855aa963-b07f-477c-a302-a802d0ffbfe8.png)

![Captura de pantalla 2022-11-25 a la(s) 3 33 31 p  m](https://user-images.githubusercontent.com/119071825/204052968-008bc338-170a-4d6f-bcfa-08abee78e50c.png)
![Captura de pantalla 2022-11-25 a la(s) 3 33 45 p  m](https://user-images.githubusercontent.com/119071825/204052985-515a4960-c245-49eb-8a66-c3691f2aa0d4.png)

**Comment by MAKOMO** [comment]
The [latest Artisan](https://github.com/artisan-roaster-scope/artisan/releases/latest) comes with a legacy build for macOS which runs on 10.13. Just download and install [```artisan-mac-legacy-2.8.0.dmg```](https://github.com/artisan-roaster-scope/artisan/releases/download/v2.8.0/artisan-mac-legacy-2.8.0.dmg). 

From your screen shot it seems you are not running the latest Phidget driver. Download and install the latest driver tagged ```OS X 10.11+``` from the [Phidgets download page for macOS](https://www.phidgets.com/docs/OS_-_macOS).

In Artisan under menu ```Config >> Device...``` make sure you have selected in the ```ET/BT``` tab under ```Meter``` the entry ```Phidget 1048 4xTC 01```.

**Comment by MAKOMO** [comment]
Any success?

**Comment by AlejoTuesta** [comment]
yes today I installed the artisan and works fine but I have download the latest Phidget driver and didn't work I had to reinstall the old version and funtion well, thanksFOR THE HELP

**Comment by MAKOMO** [comment]
In which way did the current Phidget driver not work with your 1048? Which older version of the driver did you installed instead?

**Comment by bigl00z3** [comment]
When updating the Phidget driver, the 1048 may also require a firmware upgrade to work correctly. 
This can be done via the Phidget Control Panel. You should see there if there is an update available for your device.

**Comment by MAKOMO** [comment]
Stall
