### ISSUE TITLE
Set Up

### ISSUE THREAD

**Issue by NYCroaster** [artisan-roaster-scope/artisan#104]
Does anyone know how I can change my temperature reading from 00.0 to 000. my temp is reading 400 degrees at 40.0 which in turn gives me a flat graph.
![screen shot 2016-11-02 at 8 39 56 am](https://cloud.githubusercontent.com/assets/23217817/19935775/742727ae-a0d8-11e6-8363-f415f013771a.png)

**Comment by MAKOMO** [comment]
Please the artisan mailing list for configuration questions to the community. This issue mechanism is for reporting implementation bugs.

You can add a symbolic formula like "x/10" via menu Config >> Device; 3rd tab "Symb ET/BT" for either "ET Y(x)" or "BT Y(x)", to divide your original values x by 10 if this is what you are asking for.

**Comment by NYCroaster** [comment]
Thanks Marko,

do u know how can redo a hard reset on the preferences. I followed the blog
set up for the proaster and now the readings dont even work and I forgot
what the original settings were.

Yeekai

**Comment by MAKOMO** [comment]
My last reply here. Please use the the public mailing list: menu Help >> Factory Reset. Once you have a running configuration you should use Help >> Save Settings to store all app settings in a file for later recovery.

**Comment by NYCroaster** [comment]
Sorry thnx

Yeekai Lim
