### ISSUE TITLE
Problem with use Artisan & FZ94

### ISSUE THREAD

**Issue by bzuc0** [artisan-roaster-scope/artisan#105]
Hello everybody!

I have little problem with Artisan software.

I use Coffee-Tech FZ94 roaster and i try pair this machine with Artisan software. I buy this machine in this year, it is the newest machine from coffee-tech. When i install virtual ports, that i pair Artisan with machine, i am connected, but software say this error message:

"Modbus Error: readSingleRegister() Exception response @line 28245"

Ill try make anything, i use manual on https://artisan-roasterscope.blogspot.sk/2015/01/connecting-artisan-to-coffee-tech-fz-94.html and https://artisan-roasterscope.blogspot.sk/2016/08/fz-94-1-bumping-up-modbus.html . 

Artisan is connected, but dont show temperature or anything. And of course, send upwriting message.

Thank you for any help!

**Comment by MAKOMO** [comment]
I know that their older build from this year were still running at 2400 baud, while the latest batches are running at 19200 baud (or maybe 9600) just test different serial settings.

**Comment by bzuc0** [comment]
Thank you for support. Ill try iz and it works! 

Matej



Odoslané z iPhonu

Dňa 10. 11. 2016, o 20:56, Marko Luther <notifications@github.com> napísal:

**Comment by MAKOMO** [comment]
Thanks for your confirmation!

**Comment by lukkubiny** [comment]
Hi Marco,

same problem here today, roasted 5 months without any problem, now still showing "Modbus Error: readSingleRegister() Exception response @line **29640**" 
I tried also different serial settings, nothing changed.

Appreciate any comments,
Luk

**Comment by MAKOMO** [comment]
Luk, this seems beyond my scope as I did not change anything on your setup. That error indicates a general communication issue. Artisan seems not to be able to communicate with the PIDs via the USB2RS485 interface. Either you changed something in your software setup (Artisan configuration, OS update, driver update), your serial driver got corrupted, or it is a hardware defect. Sorry for not being of more help here.

**Comment by lukkubiny** [comment]
Hi Marco,

thank you anyway :) Will check all possibilities.

Best,
Luk

**Comment by rollag16** [comment]
I have a problem artisan 1.1.0 "Modbus Error: readSingleRegister() Exception response @line 30574"

**Comment by MAKOMO** [comment]
This issue is closed. Artisan v1.1.0 is no longer supported. Only the latest version can be  supported, which is currently v2.1.1. Most often those MODBUS Exception responses simply indicate a lack of connectivity to the machine. Maybe you did not install the correct USB driver.
