### ISSUE TITLE
Can't start Control when using Fuji PID

### ISSUE THREAD

**Issue by samrausch** [artisan-roaster-scope/artisan#1054]
## Expected Behavior
Once roast has started, I click the Control button and should then see the control options for setting the PID.

## Actual Behavior
Clicking Control returns the following error:

  File "artisanlib\main.py", line 37106, in PIDcontrol   File "artisanlib\pid_dialogs.py", line 1242, in __init__  -------------------------------------------------------------------------------- artisanlib\main.py::PIDcontrol:37106 	                self = <artisanlib.main.ApplicationWindow object at 0x000001CAD8B5F340> 	                   _ = False 	           modifiers = KeyboardModifier.NoModifier artisanlib\p
[artisan-settings.zip](https://github.com/artisan-roaster-scope/artisan/files/10279889/artisan-settings.zip)
id_dialogs.py::__init__:1242 	                self = <artisanlib.pid_dialogs.PXRpidDlgControl object at 0x000001CAD9A45940> 	              parent = <artisanlib.main.ApplicationWindow object at 0x000001CAD8B5F340> 	                  aw = <artisanlib.main.ApplicationWindow object at 0x000001CAD8B5F340> 	        labelpattern = <PyQt6.QtWidgets.QLabel object at 0x000001CAF01A25F0> 	       button_getall = <PyQt6.QtWidgets.QPushButton object at 0x000001CAF01A2C20> 	         button_rson = <PyQt6.QtWidgets.QPushButton object at 0x000001CAF01A2CB0> 	        button_rsoff = <PyQt6.QtWidgets.QPushButton object at 0x000001CAF01A2D40> 	    button_standbyON = <PyQt6.QtWidgets.QPushButton object at 0x000001CAF01A2DD0> 	   button_standbyOFF = <PyQt6.QtWidgets.QPushButton object at 0x000001CAF01A2E60> 	         button_exit = <PyQt6.QtWidgets.QPushButton object at 0x000001CAF01A2EF0> 	        tab2svbutton = <PyQt6.QtWidgets.QPushButton object at 0x000001CAF01A2F80> 	     tab2getsvbutton = <PyQt6.QtWidgets.QPushButton object at 0x000001CAF01A3130> 	          svwarning1 = <PyQt6.QtWidgets.QLabel object at 0x000001CAF01A3250> 	          svwarning2 = <PyQt6.QtWidgets.QLabel object at 0x000001CAF01A32E0> 	            button_p = <PyQt6.QtWidgets.QPushButton object at 0x000001CAF01A3490> 	            button_i = <PyQt6.QtWidgets.QPushButton object at 0x000001CAF01A3520> 	            button_d = <PyQt6.QtWidgets.QPushButton object at 0x000001CAF01A35B0> 	              plabel = <PyQt6.QtWidgets.QLabel object at 0x000001CAF01A3640> 	              ilabel = <PyQt6.QtWidgets.QLabel object at 0x000001CAF01A36D0> 	              dlabel = <PyQt6.QtWidgets.QLabel object at 0x000001CAF01A3760> 	           __class__ = <class 'artisanlib.pid_dialogs.PXRpidDlgControl'> 

## Steps to Reproduce the Problem

  1. Configure Device type PID, select Fuji PXR, click OK, set correct parameters for the serial connection.
  2. Start roast, observe temps being returned by the PID are correct along with the SV and DC.
  3. Click Control button, get error.

## Specifications

  - Artisan Version: 2.8.0
  - Artisan Build (number in brackets shown in the about box): 682bdaf
  - Platform (Mac/Windows/Linux + OS version): Win 10 64bit
  - Connected devices or roasting machine: Fuji PXR5 PID

Please attach your current Artisan settings file (as exported via menu Help >> Save Settings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
Fixed by Commit 06872f596ea9dfd8348d17a54131ada24bd5a84d. Artisan v2.8.2 will include this fix and will be released tomorrow.
