### ISSUE TITLE
Cannot save in Designer

### ISSUE THREAD

**Issue by carlfino** [artisan-roaster-scope/artisan#1059]
Newbee here.  Not sure if this is a true bug or pilot error, but in v2.8.2 I am unable to save.  Menu items "Save", Save As" and "Save a Copy As" are all greyed out.
Running v2.8.2 on a Macbook Pro M1max w/ Ventura 13.1.

Carl...

**Comment by roasterdave** [comment]
Not a bug.  You can not save a profile directly from the Designer.  You must first exit the Designer by clicking Tools>> Designer.  Then you can save your profile.

This is true for all versions of Artisan.

**Comment by carlfino** [comment]
ouch.  Sorry about that.
