### ISSUE TITLE
Center 301 and USB Serial converter not working together.

### ISSUE THREAD

**Issue by CaseyLoseth** [artisan-roaster-scope/artisan#107]
I'm using a Center 301 and a Startech FTDI USB to RS232 converter cable. The center 301 works on its own and my computer recognizes the converter cable, but Artisan is giving me the error Serial esception: unable to open serial port.

I'm not sure how to fix this, I've followed the instructions on setting up the device with Artisan and everything looks to me like it should work but it's not.

**Comment by MAKOMO** [comment]
You should use the original Center RS232-2-USB converter cable. I never got any other to work with the Center. I close this as this is not an Artisan issue and has to be reported elsewhere.
