### ISSUE TITLE
Artisan 2.8.2 for Raspian bullseye does not run

### ISSUE THREAD

**Issue by timbarnes** [artisan-roaster-scope/artisan#1073]
**Describe the bug**
A fresh install of Artisan 2.8.2 on a Raspberry Pi 4 with the latest Raspian (bullseye) does not start.

**To Reproduce**
1. Install a fresh Raspbian 64-bit using the Raspberry Pi SD card writer
2. Download the 2.8.2_raspbian-bullseye.deb file.
3. Run /usr/bin/artisan
4. Application fails to start, with no error. 

**Expected behavior**
Expected either the application to start, or an error message to be provided.

**Screenshots**

**Setup (please complete the following information):**
 - Artisan Version [e.g. v2.4.4]: 2.8.2
 - Artisan Build (number in brackets shown in the about box) [e.g. 97e6dec]: Unable to determine. Application downloaded 1/12/23.
 - Version [e.g. 22]: Unable to determine
 - Platform (Mac/Windows/Linux + OS version) [e.g. macOS 10.15.3]: Raspbian 11 (bullseye) 64 bit
 - Connected devices or roasting machine [e.g. Probatone 5]: Arduino TC4+.

**Additional context**
The error appears to have to do with libraries. /usr/bin/artisan references PyQt6, but the /usr/share/artisan directory only contains PyQt5 folders. There seem to be problems with other libraries as well.

Please attach your current Artisan settings file (as exported via menu Help >> Save Settings as *.aset) file.
Please attach any relevant Artisan *.alog profiles. No settings, as it has not been possible to run the application.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by roasterdave** [comment]
Artisan supports only 32bit Bullseye on the RPi. At present some of the libraries used by Artisan do not have 64bit RPi support. 

See the supported platforms here: https://github.com/artisan-roaster-scope/artisan/releases/tag/v2.8.2
