### ISSUE TITLE
error trying to run build-ubuntu.sh

### ISSUE THREAD

**Issue by jasonwardenburg** [artisan-roaster-scope/artisan#108]
Hi,
just updated code to most recent version from github today, and trying to run the ubuntu build script. 

complete console output is attached, but relevant snippet is here....

    Updating '/media/jason/files/code/github/artisan/src/translations/artisan_pl.qm'...
        Generated 786 translation(s) (646 finished and 140 unfinished)
        Ignored 839 untranslated source text(s)
    Traceback (most recent call last):
      File "/usr/local/bin/bbfreeze", line 9, in <module>
        load_entry_point('bbfreeze==1.1.3', 'console_scripts', 'bbfreeze')()

    # more python stack output....

    File "/usr/local/lib/python2.7/dist-packages/gevent-1.1.2-py2.7-linux-x86_64.egg/gevent/_socket3.py", line 183
    def makefile(self, mode="r", buffering=None, *,

I've installed the most recent versions of bbfreeze and gevent. Is this a python version issue? Has anyone else run into this?

[artisan-build-output.txt](https://github.com/artisan-roaster-scope/artisan/files/643875/artisan-build-output.txt)

**Comment by MAKOMO** [comment]
bbfreeze and gevent_websockets packages are buggy and need to be patched to make them work. Consult the corresponding discussions on those packages. I close this as it is not addressing an issue in Artisan.
