### ISSUE TITLE
Santoker R500 Bluetooth, not connecting on Artisan.

### ISSUE THREAD

**Issue by acx4** [artisan-roaster-scope/artisan#1087]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MAKOMO** [comment]
Not much details in your report;) The Santoker R500 connection is only supported via WLAN.

**Comment by acx4** [comment]
HI Makomo, I made another report, the is R200 Bluetooth which is working on the Santoker app, it's my sample roaster and I would like to use Artisan for both the sample and the production roaster.  The Santoker App works on Bluetooth in Windows 10 and Linux Ubuntu 22.04 LTS, but Artisan does not.  I also have a smaller Q5 2.0  which that does work via WiFi on both the Santoker App and Artisan.

**Comment by MAKOMO** [comment]
Artisan is not support Bluetooth. Sorry. Thus at any time we accept PRs. Just send in your code...
