### ISSUE TITLE
Configure for Adafruit USB Isolator

### ISSUE THREAD

**Issue by sight1989** [artisan-roaster-scope/artisan#109]
Hello,

I am using TMD-56 with Artisan; Serial Port Config: Com3 / 19200 / 8 / E / 1 / 1. I recently got an adafruit usb isolator and when I plug the tmd-56 into it and then into my computer it is not working. How should I configure for the adafruit?

Thank you,

**Comment by MAKOMO** [comment]
Request support from the vendor of your isolator. This is clearly not an issue concerning Artisan. Usually USB isolators should work transparently. It might be that this isolator builds on a different usb2serial chip and thus needs a different serial driver to be installed.
