### ISSUE TITLE
MODBUS Scan option broken in v2.8.2?

### ISSUE THREAD

**Issue by bw00st3r** [artisan-roaster-scope/artisan#1100]
## Expected Behavior
MODBUS Scan should display values stored in all registers. It worked with v2.1.2, and I could see all the register values, and that was how I figured the correct register to use.

## Actual Behavior
In v2.8.2 the box remains empty.

## Steps to Reproduce the Problem

  1. Artisan 2.8.2 -> Config - Device
  2. ET/BT -> Meter: MODBUS -> OK
  3. Ports Configuration -> MODBUS -> Scan -> Start
  4. No data is written into the window
  
## Specifications

  - Artisan Version: 2.8.2
  - Artisan Build (number in brackets shown in the about box): f525b16
  - Platform (Mac/Windows/Linux + OS version): Windows 10
  - Connected devices or roasting machine: MODBUS via USB

**Comment by MAKOMO** [comment]
Duplication. See Issue #1056.

**Comment by bw00st3r** [comment]
agreed. closing.
