### ISSUE TITLE
Artisan Not reading temperature MacOsx 10.11.5

### ISSUE THREAD

**Issue by legalspeedsupply** [artisan-roaster-scope/artisan#111]
I have my Phidget 1048 hooked up and running on my laptop.  All temperatures on the phidget are reading correctly.  When i open artisan and go to configure, i select the phidget 1048 and all my BT and ET just come up -1.0.  Delta ET and Delta BT just read 0.0.  Not sure what I am doing wrong.

**Comment by MAKOMO** [comment]
If you are not using the Phidgets WebService feature in combination with the Artisan Phidgets remote access, only one application can connect to the hardware. The Phidgets Control Panel counts for one application. Just close that one and then connect Artisan to your Phidget by pressing ON.
