### ISSUE TITLE
PID ON/OFF Alarm and Arduino throw exception

### ISSUE THREAD

**Issue by James-NZ** [artisan-roaster-scope/artisan#112]
When trying to use the PID ON / OFF alarms with an Arduino TC4, I get the following exception:

"Exception: setalarm() 'ApplicationWindow' object has no attribute 'arduino'@line 2501"

Should instances of the following:
((aw.qmc.device == 19 and aw.arduino) or # Arduino TC4

Be replaced with:
((aw.qmc.device == 19 and aw.qmc.PIDbuttonflag) or # Arduino TC4

Cheers,
James

**Comment by MAKOMO** [comment]
Thanks for reporting. Good catch. The variable aw.arduino was removed on merging the Arduino specific PID support with the software PID / generic external PID support.
