### ISSUE TITLE
background profile isn´t loaded automatically

### ISSUE THREAD

**Issue by peterweiser** [artisan-roaster-scope/artisan#1155]
**Describe the bug**
When starting Artisan, the last used background profile isn´t loaded automatically anymore.
In older verisions, Artisan remembered the last used background profile if the checkbox to remove the profile was not ticked.

**Expected behavior**
The last used background profile should be opened again after closing and reopen Artisan.

**Setup (please complete the following information):**
 - Artisan Version [e.g. v2.4.4]: 2.8.3
 - Artisan Build (number in brackets shown in the about box) [e.g. 97e6dec]: 9ca439b
 - Platform (Mac/Windows/Linux + OS version) [e.g. macOS 10.15.3]: Win10 Pro 22H2
 - Connected devices or roasting machine [e.g. Probatone 5]: Dätgen DR12

[artisan-einstellungen.aset.txt](https://github.com/artisan-roaster-scope/artisan/files/11323917/artisan-einstellungen.aset.txt)

**Comment by MAKOMO** [comment]
Peter, I don't know exactly which checkbox you refer to by "to remove the profile" (which dialog? what is the exact name of this flag?).

However, I see that you have the "Always hide background when loading a profile" in the Background dialog (menu Roast >> Background) ticked and this is exactly what happens to me if I start with your settings after quitting Artisan with a background loaded. You see in the screenshot below (taken directly after starting Artisan) that a background profile is loaded, but just not drawn). You can double click its name in the right corner (here in red as playback events is active) to toggle the visibility of the background profile.

Just untick that flag and the background profile will not be hidden on starting up Artisan.

Did I miss something?

<img width="789" alt="Screenshot 2023-04-25 at 17 47 34" src="https://user-images.githubusercontent.com/13909011/234333415-706db1f8-4358-4282-be08-658afd28d6f1.png">

**Comment by peterweiser** [comment]
Hi Mark - thanks for your reply - I misunderstood that checkbox completely, because maybe there´s a translation error. The german translation just says "Profilvorlage beim Laden von Röstungen", which means something like "background profile when loading a roast" which doesn´t really make sense.
I think that checkbox should effect that - if it is ticked, and if a background profile is loaded, that this background profile is loaded, but not shown - so it´s hided somehow. 
Maybe it would be more meaningful if you say "Hintergrundprofil verbergen" or "Profilvorlage verbergen" or "geladene Profilvorlage verbergen".

**Comment by MAKOMO** [comment]
Ups. Yes this translation is at least incomplete. I changed it to "Profilevorlage beim Laden eines Profils verbergen". Luckily there is enough space in this dialog. Please keep report issues you discover. This is an excellent moment in time as we are preparing the next release. Thanks a  lot!

<img width="994" alt="Screenshot 2023-04-26 at 06 48 56" src="https://user-images.githubusercontent.com/13909011/234472705-1bf6a495-decd-4d12-b09e-596b4216621b.png">
