### ISSUE TITLE
Artisan+ No Graphs displayed under the "Roasts" page

### ISSUE THREAD

**Issue by bigl00z3** [artisan-roaster-scope/artisan#1179]
**Describe the bug**

In Artisan+, under the [Roast page](https://artisan.plus/en/roasts) , graphs should be visible in the lower part of the page. At the present time, the following message is shown instead of the graphs `Graphs of your data are shown here as soon as there is enough data.` even when they are hundreds of roasts available.

![image](https://github.com/artisan-roaster-scope/artisan/assets/8886922/d631215a-6c66-4ed2-a05c-82f74302520c)

Graphs on the[ Stores page](https://artisan.plus/en/stores) are displayed as usual.

Nico

**Comment by MAKOMO** [comment]
Dear Nico,

thank you very much for reporting this issue timely. A wrong deploy messed up things a little bit. Should be fixed be now.

Best,
Marko

**Comment by bigl00z3** [comment]
I can confirm the fix.
