### ISSUE TITLE
Artisan+: Roast list order issue

### ISSUE THREAD

**Issue by bigl00z3** [artisan-roaster-scope/artisan#1180]
When looking at the fix for [issue 1179](https://github.com/artisan-roaster-scope/artisan/issues/1179) I think I found an other one:

In Artisan+ [Roast page](https://artisan.plus/en/roasts), it should be possible to change the order of the roast by label and invert the order by clicking on the button with the arrow up ↑ or down ↓ 

<img width="531" alt="image" src="https://github.com/artisan-roaster-scope/artisan/assets/8886922/204093ba-42e4-4dca-bd8c-1f91fe14ee07">

Changing by label (Roast date, ID, Label, Batch number...) works but not inverting the order by clicking a seond time.

Nico

**Comment by paulholleis** [comment]
In fact, the initial sort is wrong. Therefore, clicking once on the "roast date" button does nothing. Clicking twice will invert the sort order. Thanks for reporting, this will be fixed shortly!

**Comment by MAKOMO** [comment]
Fixed
