### ISSUE TITLE
continuous 66f5693   Event name (translated if using default event names)   string  "\t "  bug

### ISSUE THREAD

**Issue by Terracotta-62** [artisan-roaster-scope/artisan#1181]
<img width="876" alt="20230524094334" src="https://github.com/artisan-roaster-scope/artisan/assets/116416332/9b203907-a656-42cf-8745-90e12f1899b6">
<img width="692" alt="20230524094407" src="https://github.com/artisan-roaster-scope/artisan/assets/116416332/dff2d093-84e8-418f-989c-867e4ea5b094">

**Comment by MAKOMO** [comment]
Thanks for your report. This will be fixed with the next commit.
