### ISSUE TITLE
"ON Cooling" doesn't turn on the cooling mode (Kaleido Sniper M2 Pro)

### ISSUE THREAD

**Issue by leotabakov** [artisan-roaster-scope/artisan#1183]
**Describe the bug**
Kaleido Sniper M2 Pro - "ON Cooling" button doesn't turn on the cooling mode.

**To Reproduce**
1. Press "ON" - starts temperature reading
2. Press "ON Cooling" - no reaction from coffee roaster

**Expected behavior**
"ON Cooling" starts the cooling mode.

**Screenshots**
"ON Cooling" as per screenshot.
![image](https://github.com/artisan-roaster-scope/artisan/assets/16628480/a17f998f-c4bc-4ddb-9cfe-66ca7bde89ad)

**Setup (please complete the following information):**
 - Artisan Version [e.g. v2.4.4]: v2.8.3-RC
 - Artisan Build (number in brackets shown in the about box) [e.g. 97e6dec]: b9103d0
 - Platform (Mac/Windows/Linux + OS version) [e.g. macOS 10.15.3]: macOS 13.4
 - Connected devices or roasting machine [e.g. Probatone 5]: Kaleido Sniper M2 Pro

**Additional context**
MacBook Air M2. 
Connection mode: Bluetooth. 
Configuration: Machine -> Kaleido -> Legacy

Please attach your current Artisan settings file (as exported via menu Help >> Save Settings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._
[Artisan_Settings_M2Pro_2_8_3.aset.zip](https://github.com/artisan-roaster-scope/artisan/files/11583554/Artisan_Settings_M2Pro_2_8_3.aset.zip)

**Comment by Terracotta-62** [comment]
Refer to the user manual to re-establish the Bluetooth connection and try.
Prevents the heating boiler from deforming due to uneven heating.  Set DRUM to 50% "

**Comment by particlebanana** [comment]
<img width="1162" alt="2-8-3-rc-buttons" src="https://github.com/artisan-roaster-scope/artisan/assets/370260/48887483-5e37-4528-b5e7-84b259d6abab">

I adjusted some of the buttons and they seem to work. I'll need to test more. The `CLDN,ON` and `CLDN,OFF` didn't have any impact on my machine. Either did `HPM,A` or `HPM,M`.

**Comment by MAKOMO** [comment]
For the Pro version of the Kaleido, please use the configuration file provided by the manufacturer to load the settings. They are not suitable for accessing from the new Artisan device menu, even though you can find the Legacy option, it is not compatible with the earlier Pro version. Therefore, please contact Kaleido customer service to obtain the corresponding Artisan configuration file.
