### ISSUE TITLE
Unable to reconnect after adjusting parameters (Kaleido Sniper M2 Pro)

### ISSUE THREAD

**Issue by leotabakov** [artisan-roaster-scope/artisan#1184]
**Describe the bug**
Unable to reconnect to the machine after changing any of the parameters (burner, drum or air).
"Scope monitoring..." is displayed, Artisan does not show data from sensors, and the machine doesn't react to any parameters change.
When no parameters have been changed after pressing the "ON" button, I can successfully reconnect to the machine.
The connection can be restored only after rebooting the computer.

**To Reproduce**
1. Press "ON"
2. Set DRUM to 50% or change any other parameter
3. Press "OFF"
4. Press "ON". "Scope monitoring..." is displayed, Artisan does not show data from sensors, and the machine doesn't react to any parameters change.

**Expected behavior**
Artisan can reconnect to the machine after changing any parameters.

**Screenshots**
See connection status and readings.
![image](https://github.com/artisan-roaster-scope/artisan/assets/16628480/60bef105-050c-4cbb-a8f2-77a30b44fac2)

**Setup (please complete the following information):**
 - Artisan Version [e.g. v2.4.4]: v2.8.3-RC
 - Artisan Build (number in brackets shown in the about box) [e.g. 97e6dec]: b9103d0
 - Platform (Mac/Windows/Linux + OS version) [e.g. macOS 10.15.3]: macOS 13.4
 - Connected devices or roasting machine [e.g. Probatone 5]: Kaleido Sniper M2 Pro

**Additional context**
MacBook Air M2. 
Connection mode: Bluetooth. 
Configuration: Machine -> Kaleido -> Legacy

Please attach your current Artisan settings file (as exported via menu Help >> Save Settings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

[Artisan_Settings_M2Pro_2_8_3.aset.zip](https://github.com/artisan-roaster-scope/artisan/files/11583604/Artisan_Settings_M2Pro_2_8_3.aset.zip)

**Comment by Terracotta-62** [comment]
Refer to the user manual to re-establish the Bluetooth connection and try.
Prevents the heating boiler from deforming due to uneven heating.  Set DRUM to 50% "
![931d84852258981e33f3e6824ea5de1](https://github.com/artisan-roaster-scope/artisan/assets/116416332/c13b6cb6-429f-4917-addd-ca0159f2bded)

**Comment by MAKOMO** [comment]
For the Pro version of the Kaleido, please use the configuration file provided by the manufacturer to load the settings. They are not suitable for accessing from the new Artisan device menu, even though you can find the Legacy option, it is not compatible with the earlier Pro version. Therefore, please contact Kaleido customer service to obtain the corresponding Artisan configuration file.
