### ISSUE TITLE
Air and Burner +5%, -5% buttons behave unexpectedly (Kaleido Sniper M2 Pro)

### ISSUE THREAD

**Issue by leotabakov** [artisan-roaster-scope/artisan#1185]
**Describe the bug**
Air and Burner +5%, -5% buttons change values on the sliders, but the machine only reacts to the first change. Any subsequent changes don't make any difference. When the same parameters are adjusted using the sliders machine reacts as expected.

**To Reproduce**
1. Press "ON"
2. Set the Air slider to 100%
3. Press - Air 5% button multiple times so that the Slider's value is 0
4. Machine does not react to changes

**Expected behavior**
Air and Burner +5%, -5% buttons change Air and Burner parameters.

**Screenshots**
<img width="1760" alt="image" src="https://github.com/artisan-roaster-scope/artisan/assets/16628480/e8822903-c66a-45d5-9052-00f570b27533">

**Setup (please complete the following information):**
 - Artisan Version [e.g. v2.4.4]: v2.8.3-RC
 - Artisan Build (number in brackets shown in the about box) [e.g. 97e6dec]: b9103d0
 - Platform (Mac/Windows/Linux + OS version) [e.g. macOS 10.15.3]: macOS 13.4
 - Connected devices or roasting machine [e.g. Probatone 5]: Kaleido Sniper M2 Pro

**Additional context**
MacBook Air M2. 
Connection mode: Bluetooth. 
Configuration: Machine -> Kaleido -> Legacy

Please attach your current Artisan settings file (as exported via menu Help >> Save Settings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._
[Artisan_Settings_M2Pro_2_8_3.aset.zip](https://github.com/artisan-roaster-scope/artisan/files/11583623/Artisan_Settings_M2Pro_2_8_3.aset.zip)

**Comment by Terracotta-62** [comment]
https://github.com/artisan-roaster-scope/artisan/assets/116416332/12d69892-913e-4d77-9635-d5d8e3caf307

**Comment by MAKOMO** [comment]
For the Pro version of the Kaleido, please use the configuration file provided by the manufacturer to load the settings. They are not suitable for accessing from the new Artisan device menu, even though you can find the Legacy option, it is not compatible with the earlier Pro version. Therefore, please contact Kaleido customer service to obtain the corresponding Artisan configuration file.
