### ISSUE TITLE
Drum OFF doesn't turn the drum off (Kaleido Sniper M2 Pro)

### ISSUE THREAD

**Issue by leotabakov** [artisan-roaster-scope/artisan#1186]
**Describe the bug**
The "Drum OFF" button doesn't turn the drum off completely but sets it to 10. 
The minimal Drum slider value is also 10.

**To Reproduce**
1. Press "ON"
2. Press "100% Drum"
3. Press "OFF Drum" -> Drum is still spinning.

**Expected behavior**
The drum turns off when the "OFF Drum" button is pressed.

**Screenshots**
"OFF Drum" sets is to 10%. 
<img width="1760" alt="image" src="https://github.com/artisan-roaster-scope/artisan/assets/16628480/d644e32f-c04c-4967-b2fd-8b6bf8989723">

**Setup (please complete the following information):**
 - Artisan Version [e.g. v2.4.4]: v2.8.3-RC
 - Artisan Build (number in brackets shown in the about box) [e.g. 97e6dec]: b9103d0
 - Platform (Mac/Windows/Linux + OS version) [e.g. macOS 10.15.3]: macOS 13.4
 - Connected devices or roasting machine [e.g. Probatone 5]: Kaleido Sniper M2 Pro

**Additional context**
MacBook Air M2. 
Connection mode: Bluetooth. 
Configuration: Machine -> Kaleido -> Legacy

Please attach your current Artisan settings file (as exported via menu Help >> Save Settings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._
[Artisan_Settings_M2Pro_2_8_3.aset.zip](https://github.com/artisan-roaster-scope/artisan/files/11583654/Artisan_Settings_M2Pro_2_8_3.aset.zip)

**Comment by Terracotta-62** [comment]
The manufacturer's hardware firmware designs a protection mechanism in which the drum speed is not zero when the machine temperature is above a specific temperature.

**Comment by Terracotta-62** [comment]
I'm also a user, not a manufacturer.

**Comment by particlebanana** [comment]
<img width="1156" alt="Screenshot 2023-05-31 at 10 55 00 AM" src="https://github.com/artisan-roaster-scope/artisan/assets/370260/26b96df1-a635-43ea-b3c2-fabc2b31d656">
The slider has a min set to 10 in the config. I'll have to try the button, the command seems correct but still new to the Kaledio. I also have the M2 Pro.
