### ISSUE TITLE
Weird automatic logging events during roasts.

### ISSUE THREAD

**Issue by Adondo** [artisan-roaster-scope/artisan#119]
So I've had this issue for a while, and cannot find the reason for it. Before I had playback aid and playback events on in my background profile but I unboxed them. But this doesn't seem to be the solution since this happens even without a background roast. Here's a picture displaying those auto logged events. It's those begginning with an "A..". Any suggestions other than removing all the settings and starting over?

Greetings Robin
![event issue artisan](https://cloud.githubusercontent.com/assets/27862439/25286015/8bd4c284-26bc-11e7-9444-19e728f9fa0a.jpg)

**Comment by MAKOMO** [comment]
You seem to have some alarms defined with Slider as action.
Check the alarm table under menu Config >> Alarms.
