### ISSUE TITLE
disappearing tabs in events window

### ISSUE THREAD

**Issue by peterweiser** [artisan-roaster-scope/artisan#1195]
**Describe the bug**
tabs in "Event"-window disappear (except the "Annotations"-tab) after closing and reopening the window

**To Reproduce**
1. open "Event"-window
2. Click on the tab "Annotations"
3. close that window with the <ok> button
4. open the "Event"-window again
5. see the error - all the tabs are not visible anymore except the "Annotations"-tab. I found out that if you press the <left> arrow key, the tabs come back again

**Expected behavior**
everytime, the "Eents"-window is opend, all the tabs should be visible

**Screenshots**
![grafik](https://github.com/artisan-roaster-scope/artisan/assets/33603377/a2b8b1c9-840f-4e29-9c23-1c4d8b7864db)

**Setup (please complete the following information):**
 - Artisan Version [e.g. v2.8.3]:
 - Artisan Build [b9103d0]:
 - Platform Win10 22H2
 - Connected devices Dätgen DR12 with modbus PID´s and Phidgets

**Comment by roasterdave** [comment]
Thanks for reporting this.  It is due to a subtle bug in the latest version of one of the third party libraries used by Artisan. 

The problem is fixed and available now in the [continuous build ](https://github.com/artisan-roaster-scope/artisan/releases/tag/continuous).
