### ISSUE TITLE
Background profile settings disappear when ok is selected

### ISSUE THREAD

**Issue by SteveCoss** [artisan-roaster-scope/artisan#121]
Hi there,
First off, THANKS so much for developing this.

I am having an issue where background profiles are plotting with with line size zero, then when I change apply and select OK, the setting revert. I am on windows 7

**Comment by MAKOMO** [comment]
Dear Steve,

could you please explain your issue a bit more in detail? The line size of your background curves is set to zero and you cannot change it to any other value? How did Artisan came into this state? Originally, curves have a line size of 1 or 2, right? Which background curves are you talking about? Which menus/dialogs are you using to change the line size? Could you provide screenshots of the graph and the dialogs you are operating? I just tried to replicate your issue, but failed on my Mac (I have no Windows 7 available).

**Comment by SteveCoss** [comment]
Absolutely, sorry to make you ask.


Basically, whenever I load a background profile (under roast tab), the events are not visible. If I press the line display button and find the event lines, there are no markers set and the line width is zero. I can change them, and the lines shoe up after I hit apply, but when I click OK they disappear again. I am going to be at my roasting

computer in a few min and can send screen shots.


Cheers,

Steve

________________________________

**Comment by SteveCoss** [comment]
Image 1 is how I am loading a background profile. Two shows how it loads up without any event lines showing. Three is the button I am pressing to change line display. Four shows the default desplay for power (the name won't stay set either). Five shows the changes working after I press apply. 6 shows how it looks after I hit okay.

Thanks!
________________________________

**Comment by MAKOMO** [comment]
Steve, there were no images attached. You need to attach images directly on Github by "dragging & dropping or selecting them" in your Web browser. You can see those images being rendered on clicking the "Preview" tab. Replying with images to the emails seems not to work.

Anyhow, it is still unclear (sorry!) what you refer to by "press the line display button". Which dialog, which menu item and/or which button are you operating here?

I assume that you are aware that you have to tick the "Events" flag in the background dialog to have the events of the background profile be displayed (as marked in the pic below).

<img width="688" alt="screen shot 2017-06-20 at 06 37 15" src="https://user-images.githubusercontent.com/13909011/27316882-1a572002-5583-11e7-9c7b-f235f1dfe017.png">

**Comment by SteveCoss** [comment]
![capture1](https://user-images.githubusercontent.com/13835347/27331390-3efc12f2-558b-11e7-8702-de24c9be2e75.PNG)
![capture2](https://user-images.githubusercontent.com/13835347/27331401-4782252e-558b-11e7-8388-e93db347a58f.PNG)
![capture3](https://user-images.githubusercontent.com/13835347/27331398-477f33fa-558b-11e7-97db-882dfd8d4d6b.PNG)
![capture4](https://user-images.githubusercontent.com/13835347/27331400-4781d060-558b-11e7-9766-b901bd664ea7.PNG)
![capture5](https://user-images.githubusercontent.com/13835347/27331402-4785c904-558b-11e7-837a-89937bc24735.PNG)
![capture6](https://user-images.githubusercontent.com/13835347/27331399-478143ac-558b-11e7-9797-0803f289212c.PNG)
Okay, so there's the images. I am selecting the events 'tick'.

**Comment by MAKOMO** [comment]
Dear Steve,

I now have a clear idea what is going on, but still cannot reproduce the effect. It seems that your Artisan configuration is somehow "broken". One indication is the "Background_line7" label in the dialog which should instead indicate the proper event name as set by the user in Artisan. One complication is that this line/curve configuration/dialog is generated/inherited by the underlying graph lib and not part of the Artisan code. I might be able to work around this issue for you by some code changes, but this is only possible if I can reproduce the issue. To enable me to do this, please send me your Artisan configuration file (save via menu Help >> Save Settings) and this profile as alog file per email. As I don't want to disclose my email here to spammers, please use the Contact form on the Artisan blog <https://artisan-roasterscope.blogspot.de/p/contact-me.html> to send me a message (that will indicate your email address to me) and I will reply by email such that you can send me the two files. 

Thanks for your support on this. 
Marko

**Comment by SteveCoss** [comment]
Hey Marko,
Just roasted some and my active roast event weren't plotting. I went into
the event settings, and the event type (power, fan etc.) Pull down menu no
longer has those items either. Just line_7 line_6 and so on.

Cheers,
Steve

**Comment by MAKOMO** [comment]
Turned out to be caused by messed up application settings.
