### ISSUE TITLE
Feature Request: Allow event buttons to have a wider margin at bottom of screen

### ISSUE THREAD

**Issue by fatrabbit-la** [artisan-roaster-scope/artisan#1222]
<img width="1429" alt="Screen Shot 2023-07-06 at 3 38 18 PM" src="https://github.com/artisan-roaster-scope/artisan/assets/94999664/7bb3b9e0-7245-43c4-8376-188981994f46">

I have several event buttons at the bottom of my screen. They take up roughly 70% of the overall graph window horizontally before wrapping to the next line. I would like to define the margins on either side in order to add more buttons without them wrapping to the next line.

I've attached an image showing how I want to add a third FAN event but rather than tagging on to the end next to the other fan events, it awkwardly bumps to the next line.

**Comment by fatrabbit-la** [comment]
Sorry, I take this back. Not sure why I didn’t see it before but I now see a “Max Buttons Per Row” option which helps me accomplish this.

Ignore.

Fat Rabbit Coffee
***@***.*** ***@***.***>
www.fatrabbitcoffee.com <http://www.fatrabbitcoffee.com/>

**Comment by roasterdave** [comment]
Right.  With "Max Buttons per Row" and spacer buttons (buttons that have Visibility=OFF) you can create gaps between buttons and where the next row starts.  From your screenshot it appears you are already using spacers.
