### ISSUE TITLE
Large drop in ROR while processing events

### ISSUE THREAD

**Issue by RickGroszkiewicz** [artisan-roaster-scope/artisan#123]
I have noticed a strange drop in ROR that occurs during all my roasts. I have four events which occur when the temperature reaches 270F, 275F and 280F. I typically turn on the Tools / Extras / DeltaBT after these events occur. It appears that when these events are being handled by artisan, the DeltaBT shows a large drop. I am just curious if this is something unusual, or an expected result.
![bt ror drop when events occur from 2017-06-17 12-17-52](https://user-images.githubusercontent.com/25457554/27512846-ff5550c8-591d-11e7-89a5-1cc54bdd6fb9.png)
![bt ror drop when events occur from 2017-06-24 14-24-10](https://user-images.githubusercontent.com/25457554/27512847-11977c5c-591e-11e7-9ba5-d93e621d5188.png)

**Comment by MAKOMO** [comment]
Should be fixed by the next release.
