### ISSUE TITLE
Blank page after opening Artisan Plus on mobile

### ISSUE THREAD

**Issue by lookingafar** [artisan-roaster-scope/artisan#1250]
**Describe the bug**
Blank page after opening artisan plus website on mobile

**To Reproduce**
1. Launch Opera or Firefox on an Android phone
2. Go to https://www.artisan.plus/
3. Blank page appears

**Expected behavior**
A welcome page is displayed

**Screenshots**

![Screenshot_2023-08-12-08-04-04-836_org mozilla firefox_beta-edit](https://github.com/artisan-roaster-scope/artisan/assets/36126988/9a3c5d56-3f64-4d61-91e3-0fdfe52a74a3)

**Setup (please complete the following information):**
 Xiaomi Redmi K60, Miui 14, Android 13

Safari and Opera on iPad work as expected and the welcome page appears

**Additional context**

Please attach your current Artisan settings file (as exported via menu Help >> Save Settings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
Thanks for your report. Seems that some mobile browsers add a www. prefix in front which made the server fail to serve the page. Should be fixed now.
