### ISSUE TITLE
Doc improvement: .appveyor.yml should mention adding the GITHUB_TOKEN to the environment section.

### ISSUE THREAD

**Issue by gitHub-pbMay2021** [artisan-roaster-scope/artisan#1254]
**Describe the bug**
Doc improvement: .appveyor.yml should mention adding the GITHUB_TOKEN to the environment section.
I suggest adding a step to the CI phase documentation.
In retrospect the cause and solution is obvious, but wasn't at the time.

**To Reproduce**
I will attempt to repro this later, but it is perhaps obvious to roasterdave.

Thank you roasterdave for this documentation!
Note: I am a newbie with AppVeyor

1. After going through the setup steps from the "HowTo" documentation, run a build after a push
2. Build may fail. Click on "current build -> Job Name" in the appveyor web GUI to see the build log 
3. Scroll down to the bottom and you may see "GitHub Action fails with “The GITHUB_TOKEN environment variable was not set”.
4. copy the key from the "Encrypt YAML" AppVeyor setup  step and then.....
5. Edit .appveyor.yml and add the GITHUB_TOKEN copied above to get something like:
    # Include "skip ci" in the commit message to prevent this build process from running
    environment:  
          # Set the Appveyor Python version for windows, macos and linux here. Does not affect windows_legacy.
          PYTHON_V: 3.11
         # Upgrade to specific version (for platforms supporting upgrade). Upgrade skipped if env var is missing or blank.
          PYUPGRADE_V: 3.11.4

    matrix:
    - job_name: windows_legacy
        appveyor_build_worker_image: Visual Studio 2019
     - job_name: windows
        appveyor_build_worker_image: Visual Studio 2022
     - job_name: macOS
        appveyor_build_worker_image: macos-bigsur
    - job_name: linux
        appveyor_build_worker_image: Ubuntu2004
    GITHUB_TOKEN:
        secure: Q5dvUoEX9LGsVgIJxP7cbgeA6XLKNOhMebIfq8VzOb6ptmJ7hmjjXSwkNbDzxNaX

**Expected behavior**
Cheers when the build succeeds

**Screenshots**

**Setup (please complete the following information):**
 - Artisan Version v2.8.4

**Additional context**

**Comment by roasterdave** [comment]
Thank you for the feedback.  Indeed this is a necessary step to publish the build files on GitHub.  You'll notice that in the updated document I recommend adding the token into the Appveyor project's environment settings instead of putting it in .appveyor.yml.  Doing so will allow you to refresh your forked files without requiring an edit to .appveyor.yml..
