### ISSUE TITLE
above&below of alarms/condition are reversed in Japanese language

### ISSUE THREAD

**Issue by hiroyuki2080** [artisan-roaster-scope/artisan#1256]
**Describe the bug**
above&below of alarms/condition are reversed in Japanese language

**To Reproduce**
at any time

**Expected behavior**
the reversed expressions in Japanese  should be fixed

**Screenshots**
added

**Setup (please complete the following information):**
 - Artisan Version 2.8.2
 - Artisan Build (number in brackets shown in the about box) [e.g. 97e6dec]:f525b16
 - Platform (Mac/Windows/Linux + OS version) [e.g. macOS 10.15.3]:Windows10
 - Connected devices or roasting machine [e.g. Probatone 5]:TC4
![ReversedAlarm](https://github.com/artisan-roaster-scope/artisan/assets/40195495/d9f9a11d-cb58-4213-9aff-0258d22ea14c)

**Additional context**

Please attach your current Artisan settings file (as exported via menu Help >> Save Settings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._
![ReversedAlarm](https://github.com/artisan-roaster-scope/artisan/assets/40195495/7919badc-945b-4ca0-b734-c195b2d3efd9)

**Comment by MAKOMO** [comment]
Thank you very much for reporting this issue and for your very clear and detailed report. I just fixed the translations and the update will be available in the next Artisan release.

If you find any there other issues with those translations, please report and we will fix them immediately.

**Comment by hiroyuki2080** [comment]
Thank you very much for your quick action.
