### ISSUE TITLE
Margin Alarm in Background Profile

### ISSUE THREAD

**Issue by Nicodmk** [artisan-roaster-scope/artisan#1260]
When Roasting use background profile as guideline sometimes the value of BT/ET can be up or down compare to BBT/BET due to some condition like roasting in a day then continue to night (different ambient temperature), low pressure in propane tank (mostly happent to me) because the tank almost empty. Can you make alarm guard based on BBT/BET while roasting so we can  changing gas setting quickly. Exampe BT+2°C <> BBT alarm on. Thank You

**Comment by MAKOMO** [comment]
You can make that yourself by adding a Virtual Device. You can access the current background ET/BT data using the [Symbolic Variables B1 and B2](https://artisan-roasterscope.blogspot.com/2019/11/symbolic-formulas-basics-new-variables.html).

For example with this

<img width="1026" alt="Screenshot 2023-09-30 at 16 15 21" src="https://github.com/artisan-roaster-scope/artisan/assets/13909011/af8ed1ff-ae95-478f-9e36-ea850a8e52e2">

you can define an alarm that triggers once BT of the background profile is below 100C like this

<img width="1028" alt="Screenshot 2023-09-30 at 16 13 59" src="https://github.com/artisan-roaster-scope/artisan/assets/13909011/0df93bba-7837-4eb1-9bd6-e15939a00a50">

You can also have the Virtual Device calculate the (absolute) difference between the current BT and the BT of the background profile (or any other functions).

<img width="1026" alt="Screenshot 2023-09-30 at 16 17 23" src="https://github.com/artisan-roaster-scope/artisan/assets/13909011/d0f0a30b-3f1e-4b4b-a401-6afd8273488e">

and trigger an alarm once this difference gets larger than a certain value (here 2)

<img width="1028" alt="Screenshot 2023-09-30 at 16 18 17" src="https://github.com/artisan-roaster-scope/artisan/assets/13909011/aabcb8b9-d8b2-4a8e-a5ea-0e9fe20a8db5">
