### ISSUE TITLE
On clicking Event Button... Are you sure?  YES - CANCEL

### ISSUE THREAD

**Issue by Robjones6146** [artisan-roaster-scope/artisan#1268]
**Not strictly a feature request. It would be very useful to avoid a disaster but not very often.**

 **My issue:**
I have a button **Burner off** 
If this button is clicked by mistake, the roast will be ruined as it takes 37 seconds to re-ignite the Reillo burner (5-minute roast time, fluid bed roaster) I also have a kind of emergency **SHUT DOWN** button that turns everything off and closes everything.

**Solution for Event Pop Up qualify YES/CANCEL:**
Config >> Events >> Buttons >> Tab **Qualify**  >> On/OFF (dropdown options)

Marko, I am sure you already have an elegant solution.
![are you sure](https://github.com/artisan-roaster-scope/artisan/assets/138966151/3a2130f4-b279-419a-a77d-10b59e5d6a70)

**Comment by MAKOMO** [comment]
This project accepts PRs. We are looking forward for your contribution!

**Comment by Robjones6146** [comment]
Thank you.

On a separate issue. The roaster is currently on a ship destined for the
UK. I have requested the owner to make a donation once the roaster is up
and running.

**Comment by maxoliverbr** [comment]
@MAKOMO Hi ! I was checking how this could be done, maybe if we create a event action called "confirm()":
`confirm();button(True); `

That would trigger a confirmation dialog and if "No" is clicked would exit the event. 

Or change the behavoir of the popup() action to add a Yes/No option.

**Comment by Robjones6146** [comment]
Marko would know best.

I really like the popup idea. The message is already there, add OK/CANCEL option. Works with Artisan Command, Multiple Event, and possibly in an Alarm sequence. The first Event is the alarm that pauses or suspends the second Event until the user Accepts or Cancels the second Event in the sequence.

popup(<msg>[,<int>],[<opt>])

popup(Are you sure?, 0, 1) 

Would be great if you could do this Max.

**Comment by MAKOMO** [comment]
Not trivial to impossible. Event actions are evaluated in a parallel thread which is guarded by semaphores. All GUI actions like popups need to be evaluated in the GUI thread. Blocking threads waiting for user actions is problematic. The current popup action is not connecting back to the event thread thus is not problematic
