### ISSUE TITLE
Centre-309, USB - RS232 no log data display

### ISSUE THREAD

**Issue by xiaolaba** [artisan-roaster-scope/artisan#127]
this is an initial test and seems that no data flow through USB-RS232 adapter.
Meter is Centre-309, the original RS232 output port connected to a COM-USB device and then the Windows PC.

any tips or helps.

**Comment by MAKOMO** [comment]
Did you install the SiLab CP201x USB-Serial driver for your OS? I am closing this as this issue tracker is to track issues of the Artisan software not with your external hardware setup.
