### ISSUE TITLE
german translation has a grammatical error in "update status" window

### ISSUE THREAD

**Issue by peterweiser** [artisan-roaster-scope/artisan#1270]
Sie nutzen eine Entwicklungsversion.
Sobald veröffentlicht, werden neue offizielle Versionen werden hier angezeigt.

correct would be:
Sie nutzen eine Entwicklungsversion.
Sobald veröffentlicht, werden neue offizielle Versionen hier angezeigt.

**Comment by MAKOMO** [comment]
Thanks Peter for reporting! Appreciated. Will be fixed for the next release.
