### ISSUE TITLE
wrong display behaviour

### ISSUE THREAD

**Issue by peterweiser** [artisan-roaster-scope/artisan#1283]
**Describe the bug**
Wrong dsplay behaviour when activating / deactivating the checkbox for "beep tone" in Menu "configuration" - "curves" - "UI"

**To Reproduce**
1. Go to 'Menu "configuration" - "curves" - registercard "UI"
2. Click on the checkbox 'beep tone'
3. See error - like as shown in the screenshot - above the background in artisan on the left corner is shown "beep tone on" when you switch it off and in reverse. Eventhough the beep sounds come when they are switched on, the wrong behaviour belongs only to the display above the background.

**Expected behavior**
When I switch on "beep tone" in the menu, the display should also show something like "beep switched on".

**Screenshots**
![screenshot](https://github.com/artisan-roaster-scope/artisan/assets/33603377/9f97409d-5b1f-4f53-a4f4-7faa5ce7f883)

**Setup (please complete the following information):**
 - Artisan Version [e.g. v2.8.5]:
 - Artisan Build (number in brackets shown in the about box) [6b9067f]:
 - Platform (Mac/Windows/Linux + OS version) [Windows 10 22H2]:
 - Connected devices or roasting machine [Dätgen DR12 with Modbus and Phidgets]:

**Comment by MAKOMO** [comment]
Good catch. Just fixed by 2f044ad71e498e9316f42858b7e27322562ecc77.
