### ISSUE TITLE
RPi bookworm version keeps switches back to °Farenheit at each software opening (or loses setting at closure)

### ISSUE THREAD

**Issue by bigl00z3** [artisan-roaster-scope/artisan#1300]
**Describe the bug**
I did not realise during my first tests but the current Artisan [RPi Test](https://github.com/artisan-roaster-scope/artisan/releases/tag/RPi-test) keeps switching back to °Farenheit every time the software is closed and reopened.

**To Reproduce**
1. Open Artisan, Temperature scale is in Artisan is in °F
2. Change scale to °C
3. Close Artisan
4. Open Artisan, the temperature scale is again in °F
5. Starting from blank default settings or my own settings is giving the same behavior
6. Saving settings after changing the temperature unit does not solve the issue

**Expected behavior**
Should stay in the selected temperature unit (°F or °C)

**Setup (please complete the following information):**
 - Artisan Version [e.g. v2.4.4]: Artisan 2.8.5 (5ab340d0) 
 - Artisan Build (number in brackets shown in the about box) [e.g. 97e6dec]: (5ab340d0) 
 - Platform (Mac/Windows/Linux + OS version) [e.g. macOS 10.15.3]: tested on Raspberry pi 4 (and 5) boorworm
 - Connected devices or roasting machine [e.g. Probatone 5]: with or without Phidgets and modbus

**Comment by MAKOMO** [comment]
Resolved by just published Release Candidate
