### ISSUE TITLE
is documentation down?

### ISSUE THREAD

**Issue by jasonwardenburg** [artisan-roaster-scope/artisan#131]
Hi,
from this page:
http://coffeetroupe.com/artisandocs/

all the links at the right direct to a german language mailing list area: 
http://lists.mokelbu.de/listinfo/artisan-user

also, I would have asked this in the mailing list, but when I sent an email to artisan-user@mailman.ghostdub.de it bounced back

Sorry, we were unable to deliver your message to the following address.

<artisan-user@mailman.ghostdub.de>:
550: Unrouteable address

did I send to the right place?

**Comment by MAKOMO** [comment]
Mailing list is fixed by now. Thanks for reporting. The documentation @coffeetroupe.com is not in our hands.
