### ISSUE TITLE
Phidget 1048 Error

### ISSUE THREAD

**Issue by krisklosterman** [artisan-roaster-scope/artisan#135]
When artisan 1.2.0b tries to load my Phidget 1048 4xTC it displays the following error in top left corner.

```
Exception: PHIDGET1048temperature() too many values to unpack (expected 2)@line 33841
```

It shows -1 values for the LCD's

**Comment by MAKOMO** [comment]
Did you instal the Phidgets v22 driver as advised in the download description?

**Comment by slickrecords** [comment]
On both Windows 10 and OSX 10.13 no error is displayed, but the LCDs read -1.0. Artisan 1.2.0b3 and Phidgets22 installed. Reverting back to Artisan 1.1.0 and Phidgets21 doesn't solve it.
