### ISSUE TITLE
Version 2.8.2 no longer available. Version 2.8.4 and 2.10.0 do not launch on Debian GNU/Linux version 11 (bullseye)

### ISSUE THREAD

**Issue by tg1cc** [artisan-roaster-scope/artisan#1351]
**Describe the bug**
Artisan app version 2.8.4 and 2.10.0 will not launch when installed on Debain GNU/Linux 11 (bullseye) via the Terminal. Artisan 2.8.2 was working but is no longer available to roll-back.

**To Reproduce**
1. Go to https://github.com/artisan-roaster-scope/artisan/releases
2. Download version 2.8.4 or version 2.10.0
3. Follow installation instructions on https://github.com/artisan-roaster-scope/artisan/blob/master/wiki/Installation.md for Linux Debian
4. Launch app
5. Nothing happens

**Expected behavior**
Artisan app to launch

**Screenshots**
Icon loads but is just spinning... nothing comes up.
![Screenshot 2023-12-17 16 47 03](https://github.com/artisan-roaster-scope/artisan/assets/154049490/42bee816-58da-4010-aa99-027eaf1e020f)

**Setup (please complete the following information):**
 - Artisan Version [e.g. v2.4.4]: 2.8.4 and 2.10.0 do not work. 2.8.2 worked but no longer available.
 - Artisan Build (number in brackets shown in the about box) [e.g. 97e6dec]: Cannot view because I cannot launch the app.
 - Platform (Mac/Windows/Linux + OS version) [e.g. macOS 10.15.3]: Debian GNU/Linux 11 (bullseye)
 - Connected devices or roasting machine [e.g. Probatone 5]: Bidelli 2.0kg roaster.

**Additional context**

Please attach your current Artisan settings file (as exported via menu Help >> Save Settings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
Bullseye is not supported by current Artisan versions and we do not support older Artisan versions. Sorry.
