### ISSUE TITLE
Artisan v2.10.0 can't load Yoctopuce drivers in Ubuntu

### ISSUE THREAD

**Issue by smaca69** [artisan-roaster-scope/artisan#1368]
Artisan v2.10.0 can't load Yoctopuce drivers in Ubuntu.  

1. Connect Yoctopuce thermocouple via USB
2. Run Artisan and press ON button

Error received:
Unable to import YAPI shared library (/usr/share/artisan/_internal/yoctopuce/cdll/libyapi-amd64.so) 
![Screenshot_2023-12-30_13-46-57](https://github.com/artisan-roaster-scope/artisan/assets/20550292/138b4944-3368-4d7f-bf18-41df14a71ebb)

** Extra info **
I downloaded the latest file from Yoctopuce and copied it to the above location but I still get the error.
If I uninstall v2.10.0 and install v2.8.4 I dont get the error and Artisan is able to communicate with the hardware.

**Setup (please complete the following information):**
 - Artisan Version 2.10.0
 - Artisan Build (c44a180):
 - Platform (Ubuntu 20.04.6 LTS) 
 - Connected Yoctopuce Thermocouple via USB

[artisan-settings-MILL_CITY.zip](https://github.com/artisan-roaster-scope/artisan/files/13791948/artisan-settings-MILL_CITY.zip)

**Comment by MAKOMO** [comment]
Works fine out of the back on Ubuntu 22.04 for me. 

Both, Artisan v2.8.4 and v2.10.0 are build on Ubuntu 20.04. No difference on this side. Source code in regards to the Yoctopuce driver did not change in Artisan neither.

No idea on how to investigate on this one if I cannot duplicate it. Did you try to start Artisan v2.10.0 as super user? Does this issue persist after restarting of the machine?

**Comment by MAKOMO** [comment]
Closing this as it seems to be stall.
