### ISSUE TITLE
No Error and Message after upgrade to 10.2.0

### ISSUE THREAD

**Issue by Robjones6146** [artisan-roaster-scope/artisan#1393]
After upgrading to 2.10.0 both the Help > ERROR and MESSAGE dialog box are always empty.

**Comment by MAKOMO** [comment]
A regression fixed already in the continuous builds.

**Comment by Robjones6146** [comment]
I cant find the file to download

**Comment by Robjones6146** [comment]
Found it thanks, it works now.
