### ISSUE TITLE
dropdown menues not readable

### ISSUE THREAD

**Issue by benoitmathieu** [artisan-roaster-scope/artisan#140]
Hi @MAKOMO and @rcobo ,
In the beta version 1.2.0B3, the dropdown menues related to "Change" in Config>Device>Phidgets are not readable upon dropdown. So you have to choose at random.
Almost all "change" lines are showing this problem in this tab.

**Comment by benoitmathieu** [comment]
![image](https://user-images.githubusercontent.com/34629671/34171477-b5f012a8-e4ee-11e7-9f69-e1c3eb04ad8b.png)

**Comment by benoitmathieu** [comment]
![image](https://user-images.githubusercontent.com/34629671/34171500-c9cd33d2-e4ee-11e7-9c73-ba8a1fefff9b.png)

**Comment by MAKOMO** [comment]
Dear Mathieu, thanks for this report. Seems to be only an issue on Windows. I just fixed this and will roll this in the v1.2 builds to be released tomorrow.
