### ISSUE TITLE
Save to PDF not working in 2.10.0 on Mac

### ISSUE THREAD

**Issue by Sean-Revel** [artisan-roaster-scope/artisan#1430]
**Describe the bug**
Saving a graph to PDF does not produce a PDF. Had to downgrade to a previous version to regain functionality. 

**To Reproduce**
"File > Save Graph > PDF" does not produce a PDF file. 
But "File > Save Graph > JPG" does produce a JPG.

**Expected behavior**
Artisan to produce a PDF version of the graph in the selected file location. 

**Screenshots**
N/A

**Setup (please complete the following information):**
 - Artisan Version: 2.10.0
 - Artisan Build: c44a1802
 - Platform: M3 Max MacBook Pro, MacOS 14.2.1
 - Connected devices: Phidget TMP1101 4xTC 01

**Additional context**

[artisan-settings.aset.zip](https://github.com/artisan-roaster-scope/artisan/files/14144202/artisan-settings.aset.zip)

**Comment by MAKOMO** [comment]
Thanks for your report! This will be fixed in the next release. You can use the current continuous builds where PDF export should work as expected on macOS (thus those builds are Intel-only and run under Rosetta2 on Apple Silicon).
