### ISSUE TITLE
Error installing on MacOS

### ISSUE THREAD

**Issue by dapple17** [artisan-roaster-scope/artisan#1449]
Ok, so as a windows/android user this could totally be on me but I've Googled every way I can think of to solve this issue - MacOS just feels sooo difficult to work around, I just want to download a program and run it

Every time I try to install (I think that's what I'm trying to do?) I get a '"artisan" is damaged and can't be opened. You should eject the disc' prompt. I've tried new downloads, running a pull from the source code through Homebrew on the terminal, reboots...

People keep saying to change the Privacy and Security settings to allow the app to install but I've already allowed app installs from non app store clients

Any help would be appreciated, I've tried figuring out how to download an older version, which is so much easier on a Windows machine, and I can't seem to get anything to work on this one :(

MacOS v. 10.13.6 - 2.3 GHz i5

**Comment by CarefreeBuzzBuzz** [comment]
Are you using the legacy build?Aboutartisan-scope.orgMichael Herbert CarefreeBuzzBuzz On Feb 12, 2024, at 7:00 PM, dapple17 ***@***.***> wrote:﻿
As a note, I know what a corrupted image is but that shouldn't be happening to ONLY me across dozens of downloads right?

**Comment by dapple17** [comment]
yes, legacy build; the non legacy throws some sort of incompatible OS prompt as expected

**Comment by CarefreeBuzzBuzz** [comment]
Maybe try the continuous build legacy version.  Something may have been fixed that was causing you an issue.  ___________________________Michael Herbert, CarefreeBuzzBuzzOn Feb 12, 2024, at 7:23 PM, dapple17 ***@***.***> wrote:﻿
yes, legacy build; the non legacy throws some sort of incompatible OS prompt as expected

**Comment by dapple17** [comment]
Correct, I've tried pulling a few of those and running their txt files through python (in terminal) only to get errors

**Comment by dapple17** [comment]
unless someone has a build that you can download floating around out there, I think the routing is incorrect as the files are probably relocated/gone

If this weren't a work computer I'd have partitioned and dual booted into Ubu or something :crying:

**Comment by MAKOMO** [comment]
It turned out that the Artisan v2.10.0 macOS legacy build had a signing problem. On start macOS check the code signature and rejects it as faulty. I have resigned the build now correctly. You find the fixed download on the [v2.10 download page](https://github.com/artisan-roaster-scope/artisan/releases/tag/v2.10.0) as [artisan-mac-2.10.0-legacy-resigned.dmg](https://github.com/artisan-roaster-scope/artisan/releases/download/v2.10.0/artisan-mac-2.10.0-legacy-resigned.dmg)

Sorry for the troubles.

**Comment by dapple17** [comment]
Morning!

Awesome! Thanks for the update, I would gladly run outdated software seeing
as my own hardware is so old but I know how locked in some people can get
while debugging stuff. Anyways I appreciate it!!!
