### ISSUE TITLE
Could an event execute multiple serial commands?

### ISSUE THREAD

**Issue by YuenJay** [artisan-roaster-scope/artisan#1453]
<img width="909" alt="截屏2024-02-18 下午9 59 23" src="https://github.com/artisan-roaster-scope/artisan/assets/3323534/a0f3101a-9420-41d3-bcf7-49da4f2477d1">

Only the first command can be executed.

**Comment by MAKOMO** [comment]
No. All characters given as documentation to a Serial Command actions are send as one string to the connected device. If the device can interpret this string as separate commands separated by semicolon this is fine. If not you can use a Multiple Event referencing a number of event buttons (using a comma separated list of event button numbers as documentation string) where each of the referenced event buttons issues one of your commands via a corresponding Serial Command action. Note that those event buttons can be hidden and thus with this modeling you have the same effect as if the Serial Command would allow for sequences of commands.

**Comment by YuenJay** [comment]
The matter is exactly as MAKOMO said. Thanks very much. If anyone has similar needs as me, the configuration pictures here are for reference.
<img width="907" alt="截屏2024-02-19 上午8 31 28" src="https://github.com/artisan-roaster-scope/artisan/assets/3323534/10ab8349-e065-4e3f-a483-28de642d7b91">
<img width="908" alt="截屏2024-02-19 上午8 31 09" src="https://github.com/artisan-roaster-scope/artisan/assets/3323534/a5ab14f5-0870-45ee-9ebe-123be1d6fb9d">

**Comment by MAKOMO** [comment]
Thanks for those screenshots. You might want to use the absolute Type "Burner", instead of the relative type "+-Burner", for button 6 and as value the 0 to set the burner slider/event to 0, correspond to your OT1,0 command.
