### ISSUE TITLE
Background profile missing ROR

### ISSUE THREAD

**Issue by RickGroszkiewicz** [artisan-roaster-scope/artisan#147]
I downloaded and installed version 1.2.0(3) under Linux Mint with the LXDE environment. I noticed today that the DeltaBT curve is not shown in my background profile. Those profiles were created using artisan version 1.1.0. Once I press the OFF button, the background does show the DeltaBT curve.

**Comment by MAKOMO** [comment]
Do you have DeltaBT ticked in the background dialog (menu Roast >> Background)? If yes, and you still do not see the DeltaBT of the background profile, please share that alog file.

**Comment by RickGroszkiewicz** [comment]
Yes, I also tried turning that setting on and off during the roast, but it made no difference.
[Background ROR problem.zip](https://github.com/artisan-roaster-scope/artisan/files/1595370/Background.ROR.problem.zip)

**Comment by MAKOMO** [comment]
Hm. They look beautiful as background profile  incl. DeltaBT on my Mac. Something might be different. Could you also share your Artisan settings file (save via menu Help >> Save Setting) to further investigate? I don't have Linux Mint, but I will also check the situation on my build CentOS VM, however, I would be surprised if this is a platform dependent issue.

**Comment by RickGroszkiewicz** [comment]
I checked in both Windows 7 and Linux Mint. The background ROR curve disappears when you press the "start" button.

**Comment by MAKOMO** [comment]
Just checked again, but for me the background RoR curve stays where it belongs also after pressing START. Could you share your Artisan settings file please?

**Comment by RickGroszkiewicz** [comment]
Here is my settings file: 
[artisan-settings.txt](https://github.com/artisan-roaster-scope/artisan/files/1595580/artisan-settings.txt)

**Comment by MAKOMO** [comment]
You have the RoR filter activated (menu Tools >> Extras, 2nd tab Filters, RoR Filter section).

<img width="610" alt="screen shot 2018-01-02 at 17 18 54" src="https://user-images.githubusercontent.com/13909011/34494420-b9d78448-eff0-11e7-84c5-b2f4f83005fe.png">

Just untick that one and your BT RoR should display fine.

**Comment by RickGroszkiewicz** [comment]
This appears to be a side effect of my recent upgrade to version 1.2.0. This did not happen on my Windows machine, where the filters are set at -95 to +95.

**Comment by RickGroszkiewicz** [comment]
I actually have the correct filter settings on my Linux laptop.
![screenshot from 2018-01-02 16-59-20](https://user-images.githubusercontent.com/25457554/34501893-f4f55882-efde-11e7-8af7-efd732239371.png)

**Comment by MAKOMO** [comment]
..and no RoR if that filter is deactivated either? I reopen this.

**Comment by RickGroszkiewicz** [comment]
Now I am totally confused. Marko sent me an interim version 1.2.0 to solve the issue with "crash happens after deleting event". After installing that version, the background ROR displays properly, and does not disappear after I press Start.
![background ror no problem from 2018-01-02 21-23-30](https://user-images.githubusercontent.com/25457554/34507431-d36a59c2-f003-11e7-9fb4-10a771faa655.png)
