### ISSUE TITLE
Phidget ports interferences

### ISSUE THREAD

**Issue by benoitmathieu** [artisan-roaster-scope/artisan#148]
Hi Marko,

I am running the following Phidgets config : HUB0000 + OUT1100 + TMP1101
K-type TC are attached to TMP1101 ports 0 (BT) and 1 (ET)
FAN is attached to OUT1100 port 1 and Heater driver on port 0
Strangely, FAN and heater sliders values are paired with measured ET value.
If I manually put a higher value on the slider, they keep it; but if I set a lower value (i.e. 0), it always set back to ET measured temp after a few seconds. 
That's a safety problem in my case as it fire the heater back on when I do not expect it.

Thanks a lot for your support on that case.

Here are the screenshots of the observation and config of the sliders.
Slider are configured so they allow a stretching of the working zone of each device.

![image](https://user-images.githubusercontent.com/34629671/34471160-8f71f256-ef41-11e7-8995-938cf1d750e3.png)

![image](https://user-images.githubusercontent.com/34629671/34471163-aa7f0106-ef41-11e7-8bdf-f2dfe4f941f3.png)

**Comment by benoitmathieu** [comment]
here are my artisan settings : 
[artisan-settings.zip](https://github.com/artisan-roaster-scope/artisan/files/1596399/artisan-settings.zip)

**Comment by MAKOMO** [comment]
This is because you asked Artisan to do so by defining corresponding event quantifiers. Just untick those quantifiers and you should be good to go.

<img width="964" alt="screen shot 2018-01-01 at 22 48 12" src="https://user-images.githubusercontent.com/13909011/34471307-0c579c90-ef46-11e7-9479-61e5b0065433.png">
