### ISSUE TITLE
Call Program in Alarms not working in 1.2

### ISSUE THREAD

**Issue by georgejk** [artisan-roaster-scope/artisan#150]
Call Program in 1.2 does not call the .bat file having SayStatic text.  It was working with 9.7
![alarms](https://user-images.githubusercontent.com/15264795/34654801-6e4b8dee-f3b5-11e7-8b29-a2460a89b615.JPG)

**Comment by MAKOMO** [comment]
Works for me under Windows. Just tested with a script `Load Beans.bat` placed on my desktop (path `c:\User\luther\Desktop\Load Beans.bat`) next to the SayStatic.exe with just the following line as content

```
c:\User\luther\Desktop\SayStatic.exe Set heat to 95 percent. Set Fan to 2
```
In the Description cell of the alarm I wrote

```
c:\Users\luther\Desktop\Load Beans.bat
```

Try to specify the full path to your *.bat scripts!

**Comment by georgejk** [comment]
Thank you!Geo-----Original Message-----
