### ISSUE TITLE
pidSource cycling between ET and BT on okAction

### ISSUE THREAD

**Issue by dfunni** [artisan-roaster-scope/artisan#1515]
### Problem Description

PID Input (pidSource) cycles between BT and ET when the PID Control dialog's OK button is pressed.

This cycling does not occur if the dialog is closed by the "x" in the upper corner.

I am using a Raspberry Pi with the Raspberry OS (bookworm) to control a TC4 using the Artisan internal PID in background mode.

The desired state is when Input is set to BT it will not change when the OK button is hit.

[artisan-settings.aset.txt](https://github.com/artisan-roaster-scope/artisan/files/14624261/artisan-settings.aset.txt)

### Steps To Reproduce

1. Start Artisan after factory reset
2. Load artisan-settings.aset (attached)
3. Check config settings: Config > Device
- check Control
- set device to TC4
- ET Channel: 2
- BT Channel: 1
- uncheck PID Firmware
4. Click "Control" button, set "Input" to "BT", click "OK"
5. Click "Control" button again, note "Input" reads "ET", click "OK"
6. Click "Control" button again, note "Input" reads "BT", click "OK"
7. Repeat steps 5 and 6 and note "Input" continues to cycle between ET and BT

### Artisan Version

2.10.2

### Computer OS and Version

Raspberry Pi OS - Debian GNU/Linux 12 (bookworm)

### Connected devices or roasting machine

TC4

### Files

- [ ] A sample profile *.alog file, renamed to *.alog.txt is attached.

- [X] A settings file (Help>> Save Settings) *.aset, renamed to *.aset.txt is attached.

- [ ] Screenshots are attached.

- [ ] No files are attached.

**Comment by MAKOMO** [comment]
Thanks for your detailed report! Excellent!

It was reported before that there are some issues with the PID dialog in Artisan v2.10.2 (Issue #1480). Those should be all sorted out by now.

There is no continuous build for the RPi that you could test. Sorry. But maybe you could test the [continuous build](https://github.com/artisan-roaster-scope/artisan/releases) on on any of the other platforms and report back if this is resolved.

Anyhow, we plan to soon make a new release fixing this.
