### ISSUE TITLE
In Roast Properties, unable to change/add a value in "Color, Ground". 

### ISSUE THREAD

**Issue by DennieSch** [artisan-roaster-scope/artisan#1520]
### Problem Description

In Roast Properties, unable to change/add a value in "Color, Ground". 
v2.10.2 release works fine.
'Continuous Build' (2.10.3 (e04c639)) does not. Does not allow me to change the pre-populated 'zero' value to something else.

(I manually enter a number in this field as a way for me to track roast levels.)

### Artisan Version

2.10.3 Continuous Build

### Computer OS and Version

Windows 11 

### Connected devices or roasting machine

N/A

### Files

- [ ] A sample profile *.alog file, renamed to *.alog.txt is attached.

- [ ] A settings file (Help>> Save Settings) *.aset, renamed to *.aset.txt is attached.

- [ ] Screenshots are attached.

- [X] No files are attached.

**Comment by roasterdave** [comment]
Thank you for the detailed report.  This is fixed now in the [continuous builds](https://github.com/artisan-roaster-scope/artisan/releases/tag/continuous).
