### ISSUE TITLE
PID Filters missing

### ISSUE THREAD

**Issue by 2571113** [artisan-roaster-scope/artisan#1539]
### Problem Description

Where are the PID filters?
![PID](https://github.com/artisan-roaster-scope/artisan/assets/132497527/6a107289-2f49-42df-af91-07c684535b14)

### Artisan Version

2.10.4

### Computer OS and Version

Windows 11

### Files

- [ ] A sample profile *.alog file, renamed to *.alog.txt is attached.

- [ ] A settings file (Help>> Save Settings) *.aset, renamed to *.aset.txt is attached.

- [ ] Screenshots are attached.

- [ ] No files are attached.

**Comment by 2571113** [comment]
There were parameters for the PID in the Modbus port settings.

**Comment by 2571113** [comment]
There were parameters for the PID in the Modbus port settings.

**Comment by MAKOMO** [comment]
Those filters apply only to the internal PID. You have configured Artisan to drive an external MODBUS PID.
