### ISSUE TITLE
Alarm seems not be working correctly

### ISSUE THREAD

**Issue by mhsieh66** [artisan-roaster-scope/artisan#1545]
### Problem Description

The alarm seems not to be working correctly. I set the following alarms but both alarms are triggered at 0:00 after charged, I assume the alarm #9 should be triggered 30 seconds after charged. it looks like using "OR" not "AND" for the time and condition. 
#8	True	0	0	CHARGE	00:00	BT	>	120.0	Slider Burner	0
#9	True	0	0	CHARGE	00:30	BT	>	70.0	Slider Burner	70

### Steps To Reproduce

The alarm seems not to be working correctly. I set the following alarms but both alarms are triggered at the time 0:00 after charged, I assume the alarm #9 should be triggered 30 seconds after charged. the time and condition look like using "OR" not "AND" to trigger the alarm.

#8	True	0	0	CHARGE	00:00	BT	>	120.0	Slider Burner	0
#9	True	0	0	CHARGE	00:30	BT	>	70.0	Slider Burner	70

[Colombia Honey Aponte Hugo Agreda 24-04-30_1058.txt](https://github.com/artisan-roaster-scope/artisan/files/15169438/Colombia.Honey.Aponte.Hugo.Agreda.24-04-30_1058.txt)
[M1S.txt](https://github.com/artisan-roaster-scope/artisan/files/15169443/M1S.txt)
<img width="138" alt="After charged" src="https://github.com/artisan-roaster-scope/artisan/assets/19178223/9cfeebcd-18e4-4cc6-9d8d-daf35a5ee89c">
<img width="868" alt="Alarms" src="https://github.com/artisan-roaster-scope/artisan/assets/19178223/6b259ebe-edf3-4170-85a5-01ab18279cdf">

### Artisan Version

2.10.4

### Computer OS and Version

macOS 14.4.1

### Connected devices or roasting machine

Kaleido M1

### Files

- [X] A sample profile *.alog file, renamed to *.alog.txt is attached.

- [X] A settings file (Help>> Save Settings) *.aset, renamed to *.aset.txt is attached.

- [X] Screenshots are attached.

- [ ] No files are attached.

**Comment by Terracotta-6** [comment]
Process control, not following alert rules.
![7ec499356c0ab5a42726bf71a3d6591](https://github.com/artisan-roaster-scope/artisan/assets/149906183/e1718781-394b-4cc2-a471-0c2a62d28505)

**Comment by mhsieh66** [comment]
Sorry, you meant my alarm settings don't follow the rules? Could you please explain it? Thanks!

**Comment by MAKOMO** [comment]
The time and temperature criteria are indeed combined by a disjunction to decide if an alarm triggers or not. If any of the criteria is fulfilled the alarm triggers. Further, a time criteria of 00:00 is never triggered by  a special convention. Use the almost identical 00:01 instead. To model a disjunction of a time and temperature criteria use an alarm chain.

Please refer to [Alarms](https://artisan-roasterscope.blogspot.com/2013/03/alarms.html) and [More Alarms](https://artisan-roasterscope.blogspot.com/2016/08/more-alarms.html) for further details on the mechanism.

**Comment by MAKOMO** [comment]
Try something like this. Alarm 2 triggers 30sec after CHARGE but does not fire any action. Alarm 3 triggers after Alarm 2 has been triggered (by the `If Alarm` condition) and the temperature is higher than 70C and sets the burner to 70%.

<img width="1145" alt="Screenshot 2024-05-01 at 08 51 44" src="https://github.com/artisan-roaster-scope/artisan/assets/13909011/aeb6064b-5534-49a8-85e2-9b610a989e7e">

**Comment by MAKOMO** [comment]
you intended to say "for most users it is more straight forward that the combination of time and temperature is by conjunction instead of disjunction", right? So you thing + is a more straight forward operation than -? That is just dualism as in the case of disjunction and conjunction. In roasting it is often also the combinator that is used most, stating "if either time or temperature is reached do something".

The artisan alarm rule system as is very achieves the full expressivity of propositional logic (incl. negation!).
