### ISSUE TITLE
Custom frequency PWM slider?

### ISSUE THREAD

**Issue by jkfrfr** [artisan-roaster-scope/artisan#1601]
I'm modifying an existing fluid bed roaster to allow control and measurement using various Phidgets.  I'm having an issue controlling the fan with the PWM signal from an OUT1100, in particular the minimum frequency of the OUT1100 is 100Hz, but the fan is controlled by a triac, which is also switching at 100Hz.  I can't sync the two in phase, so I need a longer control period from the OUT1100, ideally something around 20Hz or lower.

I searched the Phidgets forum, and what they suggest is creating a custom script to cycle the output between completely on and completely off for a desired duty cycle and frequency.  So my question is if Artisan is capable of something like this?

Is it currently possible to have a slider with a range of (for instance) 1000ms, and then turn on the output of the OUT1100 with a value of {sv}, and then off for a value of 1000-{sv}, and then repeat?  I've been searching, and haven't found anything, but I'm new to artisan.

I'm a little surprised that Phidgets has such a high minimum, as it seems people often have this issue controlling various high power switches and inductive loads.

**Comment by MAKOMO** [comment]
We do not have any intension to provide PWM in software on the Artisan thus you can attach your own script or module (eg. communicating with Artisan per MODBUS/S7/WebSockets) realising this at any time. 

It seems the [Yoctopuce Yocto-PWM-Tx module](https://www.yoctopuce.com/EN/products/usb-electrical-interfaces/yocto-pwm-tx) supported by Artisan supports slower PWM signals.
