### ISSUE TITLE
Extra files on DMG

### ISSUE THREAD

**Issue by rpaulo** [artisan-roaster-scope/artisan#162]
The DMG includes a directory called "Wheels".  Shouldn't this be under Resources?

**Comment by MAKOMO** [comment]
Those are example Wheels that the user could check out. Users won't find those under Resources. So this is ok. I think I never added those to the Windows builds.

M

**Comment by rpaulo** [comment]
I see.  I never thought those could be opened.

**Comment by MAKOMO** [comment]
What is our feeling? Are those files confusing? Wheels are not that important. We could just remove them from there. Let me know.

**Comment by rpaulo** [comment]
I don't know.  I thought it was something broken in the build script.  I'm fine as it is
