### ISSUE TITLE
Modbus communication issue

### ISSUE THREAD

**Issue by vikramms** [artisan-roaster-scope/artisan#1624]
### Problem Description

The 2.10.5 solved the "Voice/exe" issue but it drew my attention to another problem. First I noticed the temperature readings were off and maybe in "C" even though I selected "F" mode but then the display just got corrupted. Attached are the pictures. The same machine settings file works with 2.4.6, and the Modbus communications is fine. The PLC being used is a Directlogic DL06. However, I am using MODBUS over a UART.

![IMG_2825](https://github.com/user-attachments/assets/7c897a8e-0c44-4471-af83-99c80f5efc6e)
![IMG_2826](https://github.com/user-attachments/assets/790cedf8-84ad-42df-89fa-f4f743b46e1d)

I am also attaching my settings file.
[USR25.aset.zip](https://github.com/user-attachments/files/16188625/USR25.aset.zip)

BTW, I had the same problem with 10.2.4.

Thank you,

Vikram

### Artisan Version

2.10.5 Continuous Build

### Computer OS and Version

Windows 10

### Connected devices or roasting machine

USRoaster with Modbus

### Files

- [ ] A sample profile *.alog file, renamed to *.alog.txt is attached.

- [X] A settings file (Help>> Save Settings) *.aset, renamed to *.aset.txt is attached.

- [X] Screenshots are attached.

- [ ] No files are attached.

**Comment by vikramms** [comment]
More screenshots.

Vikram
![IMG_2825](https://github.com/user-attachments/assets/8d9d4ffe-f267-419f-91f5-646cc7b97bda)
![IMG_2826](https://github.com/user-attachments/assets/7e422f8d-e754-40d8-aab1-4dc322f3e903)

**Comment by vikramms** [comment]
2 more

Vikram
![IMG_2823](https://github.com/user-attachments/assets/aeb6d0c5-2cf6-4a9a-a85f-badbfbdc6c97)
![IMG_2824](https://github.com/user-attachments/assets/8e3bea3c-32ec-42dd-b745-6a918f7173fb)

**Comment by vikramms** [comment]
2 more screenshots.

Thanks,
Vikram

![IMG_2824](https://github.com/user-attachments/assets/5b66424e-594b-4ce1-8f09-a76e335e6e02)
![IMG_2823](https://github.com/user-attachments/assets/f572bd58-30c1-454f-9b80-9a3515597218)

**Comment by MAKOMO** [comment]
Stall

**Comment by vikramms** [comment]
Hello Marko,

Sorry, it took me longer than expected. Here are the log files. Also, this situation persists on the new v3.0 release as well.

I was trying to set this up on my Mac and try as opposed to my production PC. However, I am still having several issues with the FTDI driver. Hence the delay.

Thanks,

Vikram

[artisan.log.txt](https://github.com/user-attachments/files/16625986/artisan.log.txt)
[artisanViewer.log.txt](https://github.com/user-attachments/files/16625987/artisanViewer.log.txt)
