### ISSUE TITLE
Willing to help connect my machine with panel from coffeeroasters.com.au

### ISSUE THREAD

**Issue by DrR0X-glitch** [artisan-roaster-scope/artisan#1627]
**Describe the solution you'd like**
I am experienced in python and willing to help get this implemented, just need guidance on how the app works and how I would add to it.

I have a has garanti machine that has been modified with a different mainboard and control panel from coffeeroasters.com.au. I am looking at connecting it to artisan, it currently connects to Coffee Sweet from CRA through a usb cable. The only issue I can see is if it is all encrypted or locked due to it being closed source.

Where would I start with this? Am I missing another way to do this?

**Comment by MAKOMO** [comment]
Under menu Devices, there is the option to take the readings from an external program (last option at the bottom). Just point this to your Python script delivering the readings. Press the Help button get the documentation on how your script should return the readings (with Python examples).

If there is more demand for such a configuration you can forward your script to us for integration as regular device.

**Comment by DrR0X-glitch** [comment]
Ah perfect, that should work well, I will report back if I'm successful in
reading and controlling the proprietary information.

**Comment by MAKOMO** [comment]
Any success?

**Comment by MAKOMO** [comment]
Stall

**Comment by DrR0X-glitch** [comment]
> Any success?

Sorry for the lack of response, I managed to read some data but couldn't get control of the gas and fan through python due to some encryption and unknown protocols. So just gave up on integration after that. Thanks for your help though!
