### ISSUE TITLE
Stored SV temp value in Celsius converted as if it was Fahrenheit

### ISSUE THREAD

**Issue by upatamby** [artisan-roaster-scope/artisan#1631]
### Problem Description

I have the PID SV (Set Value) set to 180 C. I save the settings and reopen Artisan. The SV setting is now changed to 82 C. But if I open Artisan by double clicking on the previously saved settings file the value is 180 C. It seems that the value of 180 C is interpreted as Fahrenheit in stead of Celsius, but only when I open Artisan without explicitly specifying the settings file. If I open the settings file after opening Artisan the value changes to 180 C.

### Steps To Reproduce

1. Start Artisan after a factory reset.
2. open the attached settings file.
3. Notice that the SV slider has a value of 180 C.
4. Also notice that the value under Control, Set Value, SV equals 180 C.
5. Close Artisan
6. Reopen Artisan 
7. Notice that the SV slider now shows a value of 82 C.
8. Also notice that the value under Control, Set Value, SV now also equals 82 C.
[artisan-settings.aset.txt](https://github.com/user-attachments/files/16324878/artisan-settings.aset.txt)
 

### Artisan Version

2.10.4

### Computer OS and Version

Windows-10-10.0.19045-SP0, 64 bit (AMD64)

### Connected devices or roasting machine

n/a

### Files

- [ ] A sample profile *.alog file, renamed to *.alog.txt is attached.

- [X] A settings file (Help>> Save Settings) *.aset, renamed to *.aset.txt is attached.

- [ ] Screenshots are attached.

- [ ] No files are attached.

**Comment by MAKOMO** [comment]
Fixed by [4ca8c3a](https://github.com/artisan-roaster-scope/artisan/commit/4ca8c3a9b885efa6ae6ac4822957b43bf934ee34)
