### ISSUE TITLE
Yoshan Full Automatic SD-1.5kg Pro

### ISSUE THREAD

**Issue by XMusician** [artisan-roaster-scope/artisan#1638]
Hi, i had install the softwere but i did not found yoshan Full Automatic SD-1.5kg Pro in devices list.
may you add it please.
thank you,

**Comment by MAKOMO** [comment]
We do not have any information about that machine. We need the technical and financial support of Yoshan to add support for this machine. We are awaiting to be contacted by Yoshan on this.
