### ISSUE TITLE
Clean up the src directory

### ISSUE THREAD

**Issue by rpaulo** [artisan-roaster-scope/artisan#164]
Lots of files spread around in the src directory.  We could do some cleanup.

Suggestion:
Move Comm* to a separate directory.
Move icons to the icons directory.
Move build/setup scripts to their own directory.

**Comment by MAKOMO** [comment]
Yep, please go. Also the build scripts could be cleaned up, eg. the build-mac35.sh script could be renamed into build-mac3.sh as it covers both v3.5 and v3.6 now.

**Comment by rpaulo** [comment]
@MAKOMO Can you delete the scripts that are simply not used anymore?  I know the scripts that Travis/AppVeyor uses, but I'm not sure which ones you might use...

**Comment by MAKOMO** [comment]
Yep. One moment I have to check.

**Comment by MAKOMO** [comment]
Done. Did not rename the build-mac35 script not to break anything in your scripts
