### ISSUE TITLE
Modal Curves dialog on Linux prevents curves from being seen

### ISSUE THREAD

**Issue by rpaulo** [artisan-roaster-scope/artisan#165]
On Linux, the Curves dialog is modal and when I try to move it out of the way, it moves all Artisan windows.

**Comment by rpaulo** [comment]
Found out that there's an option in Gnome to revert to the old behavior, where a modal window can move by itself.  However, the behaviour described above is the default so it would be nice if we could find an alternative.

**Comment by MAKOMO** [comment]
Seems to be a windows manager configuration issue
