### ISSUE TITLE
Fan goes to zero after DROP

### ISSUE THREAD

**Issue by RickGroszkiewicz** [artisan-roaster-scope/artisan#1658]
### Problem Description

I am using artisan 2.10.4 under linux Mint. I have a problem that occurs randomly (oh joy!)

In about 40% of my roasts the fan goes to 0% instead of 100% after I click on DROP. I checked, and all of my alarm files set the fan to 100% after the DROP occurs. 

<img width="687" alt="alarm-file-drop-fan-100" src="https://github.com/user-attachments/assets/7406e98f-a4cf-496f-adab-10ad94127d17">
[Costa Rica Tarrazu La Pastora 2022 roasted on 24-07-07.txt](https://github.com/user-attachments/files/16566782/Costa.Rica.Tarrazu.La.Pastora.2022.roasted.on.24-07-07.txt)

### Artisan Version

2.10.4

### Computer OS and Version

linux Mint 21.3

### Connected devices or roasting machine

Hottop B-2K+

### Files

- [ ] A sample profile *.alog file, renamed to *.alog.txt is attached.

- [X] A settings file (Help>> Save Settings) *.aset, renamed to *.aset.txt is attached.

- [X] Screenshots are attached.

- [ ] No files are attached.

**Comment by roasterdave** [comment]
Looks like everything is working according to the alarm setup.

In your example profile FCs is at 9:26 and DROP at 10:44.  Right after DROP alarm 28 sets the Air to 100.  Then right on schedule at 10:56, which is FCs plus 1:30, alarm 26 fires to set the Air to 0.  

You can try conditioning alarm 26 with "But Not 28" to prevent it firing after alarm 28 has fired.

_Note that the alarm numbers referenced here are taken from the alarm table you posted above.  The alarm table used to record your sample profile was different!  Thus, while the alarm actions remained the same, the alarm numbers in the profile itself do not match with those used here._

![image](https://github.com/user-attachments/assets/95c0f0a7-856a-4c3f-b6f7-9f260c9cf3a8)

**Comment by RickGroszkiewicz** [comment]
Thanks, Dave! I have to remember to prune out extraneous alarms which occur after the DROP ...
