### ISSUE TITLE
Request arduino esp32 connection code

### ISSUE THREAD

**Issue by Pond021** [artisan-roaster-scope/artisan#1666]
### Problem Description

Request arduino esp32 connection code

### Artisan Version

2.10.4

### Computer OS and Version

Windows 10 Pro

### Connected devices or roasting machine

Arduino ESP32

### Files

- [ ] A sample profile *.alog file, renamed to *.alog.txt is attached.

- [ ] A settings file (Help>> Save Settings) *.aset, renamed to *.aset.txt is attached.

- [ ] Screenshots are attached.

- [ ] No files are attached.

**Comment by MAKOMO** [comment]
This project is implementing a roast logging software. Developing firmware for microcontrollers is out of scope. However, Artisan implements many standard protocols like MODBUS/TCP and WebSockets which you can use to send in data from your ESP. There is also the [aArtisanESSP](https://github.com/renatoa/TC4-shield/tree/master/applications/Artisan/aArtisanESP) which is implementing the Arduino/TC4 protocol, also accepted by Artisan.
