### ISSUE TITLE
Mac (Intel) Monterey 12.5 No generic serial devices shown

### ISSUE THREAD

**Issue by dprotter** [artisan-roaster-scope/artisan#1697]
### Problem Description

I am trying to send serial commands to an arduino (no specific communication protocol). I am able to connect to the Arduino and send messages through the arduino IDE. However, the artisan Port tab for generic serial com ports is completely unpopulated. As you can see, somewhere Artisan is configured to send over COM4, and is trying to send serial data. 

Interestingly, other tabs DO recognize the arduino (such as the MODBUS tab). Any help would be appreciated!

Finally, I AM capable of communicating over serial if I save the config file, manually assign the correct port in a text editor, and load the settings. Not the worst solution! but a bit inconvenient. 

<img width="1673" alt="Screen Shot 2024-09-16 at 8 39 30 AM" src="https://github.com/user-attachments/assets/3f81a0b8-6f78-4c79-a737-cf7960dc3d7e">
<img width="829" alt="Screen Shot 2024-09-16 at 8 40 00 AM" src="https://github.com/user-attachments/assets/5d61ca1f-41e3-472e-8695-f0f19e43dfd8">
<img width="343" alt="Screen Shot 2024-09-16 at 8 39 49 AM" src="https://github.com/user-attachments/assets/a2d8ea11-0f96-4d49-8874-cf4f5b11469c">
<img width="1208" alt="Screen Shot 2024-09-16 at 8 39 36 AM" src="https://github.com/user-attachments/assets/92348a8c-cce4-40c1-b002-a2c2fb4e4538">
<img width="572" alt="image" src="https://github.com/user-attachments/assets/d8897696-8499-4d07-b896-4f609ab09d51">

### Steps To Reproduce

1. start artisan
2. attach arduino
3. open "ports" tab

### Artisan Version

3.0.2

### Computer OS and Version

Mac OS 12.5.1 (Intel)

### Connected devices or roasting machine

arduino

### Files

- [ ] A sample profile *.alog file, renamed to *.alog.txt is attached.

- [ ] A settings file (Help>> Save Settings) *.aset, renamed to *.aset.txt is attached.

- [X] Screenshots are attached.

- [ ] No files are attached.

**Comment by MAKOMO** [comment]
The "Extra" tab of the Ports dialog is to configure serial ports for extra devices. You might not have configured any extra device in the Device Assignment dialog (menu Config >> Device, 2nd tab).

The serial port of the main device is configured in the first tab ET/BT of the Ports dialog.

**Comment by MAKOMO** [comment]
Could you resolve your issue?

**Comment by MAKOMO** [comment]
Stall
