### ISSUE TITLE
Error on changing some MODBUS PID settings

### ISSUE THREAD

**Issue by 2571113** [artisan-roaster-scope/artisan#1700]
### Problem Description

There is an error when I change some PID settings

```
An unhandled exception occurred. Please report the problem on Github: https://github.com/artisan-roaster-scope/artisan/issues  When reporting this issue, please include your settings file (export  via menu Help >> Save Settings) and the details below.  An entry has been written to the error log (menu Help >> Error).  Version: 3.0.3, revision: 50dc3b3 2024-09-25, 19:54:15 -------------------------------------------------------------------------------- : invalid literal for int() with base 10: '' (line: 22826)
```

### Artisan Version

3.0.3 Continuous Build

### Files

- [ ] A sample profile *.alog file, renamed to *.alog.txt is attached.

- [ ] A settings file (Help>> Save Settings) *.aset, renamed to *.aset.txt is attached.

- [x] Screenshots are attached.

- [ ] No files are attached.

**Comment by 2571113** [comment]
![image](https://github.com/user-attachments/assets/b8146205-6922-4e85-9ff8-adee2e8c4c4c)
If you change the PID settings registers and try to save them, you will receive an error message and the changes will not be saved.

**Comment by MAKOMO** [comment]
Thanks for your report. We could duplicate the issue by leaving fields empty where numbers are expected. Commit 6a5ccefb78b186bc9ae0f060089454fac5f6efb3 should make the data input more robust. 

Does the current [Continuous Build](https://github.com/artisan-roaster-scope/artisan/releases/tag/continuous) fixes this for you? Could you please test?

Thanks!

**Comment by 2571113** [comment]
That's right. If you make the changes one by one using the Tab key, the changes and saving will work.

**Comment by MAKOMO** [comment]
So is this issue now fixed in the new Continuous Build or not?

**Comment by 2571113** [comment]
The new on is 45 minutes old.
I will try it tomorrow

**Comment by 2571113** [comment]
the current build is ok.

**Comment by 2571113** [comment]
Thanks!

**Comment by MAKOMO** [comment]
Thanks for testing and this confirmation!
