### ISSUE TITLE
Unhandled Exception - popup requested this report.

### ISSUE THREAD

**Issue by captainredbutt** [artisan-roaster-scope/artisan#1701]
### Problem Description

version = 3.0.0

1 10:38:13.498 Error: File "artisanlib\main.py", line 23427, in schedule File "plus\schedule.py", line 1741, in __init__ File "plus\schedule.py", line 3042, in updateScheduleWindow File "plus\schedule.py", line 2784, in updateRoastedItems File "plus\schedule.py", line 866, in __init__ File "plus\schedule.py", line 779, in __init__ File "plus\schedule.py", line 925, in getRight File "babel\dates.py", line 683, in format_date File "babel\dates.py", line 352, in get_date_format File "babel\core.py", line 905, in date_formats File "babel\core.py", line 439, in _data File "babel\localedata.py", line 137, in load File "babel\localedata.py", line 143, in load -------------------------------------------------------------------------------- artisanlib\main.py::schedule:23427 self _True plus\schedule.py::__init__:1741 self parent aw activeTab0 remaining_widget layout_remaining remaining_filter_layout remaining_message_layout remaining_filter_layout2 remaining_filter_group2 roasted_widget layout_roasted completed_scrollarea weight_unit_strg density_unit_strg/l moisture_unit_str% color_unit_str# font fontMetrics weight_density_suffix_width15 color_moisture_suffix_width10 roasted_density_suffix roasted_color_suffix roasted_moisture_suffix roasted_first_line_layout roasted_second_line_layout roasted_details_layout lines2 docMargin4.0 lineSpacing16 roasted_notes_doc margins notes_hight44 cupping_notes_doc cupping_notes_hight44 cupping_layout completed_details_layout completed_details_layout2 completed_message completed_message_layout task_type_layout task_weight_layout task_title_layout task_layout task2_layout disconnected_widget disconnected_layout __class__ plus\schedule.py::updateScheduleWindow:3042 self displayed_scheduled_items8 plus\schedule.py::updateRoastedItems:2784 self now2024-09-28 17:38:13.488265+00:00 nodrag_items_first_label_max_width0 nodrag_first_labels[] new_selected_completed_itemNone itemcount=1 scheduleID='66e1dfadd83761aa4544bacc' scheduleDate='2024-09-14' sequence_id=1 roastUUID=UUID('3876535f-e4fd-440f-8d07-7bbf07860f47') roastdate=datetime.datetime(2024, 9, 14, 19, 28, 30, tzinfo=TzInfo(UTC)) roastbatchnr=242 roastbatchprefix='arc_' title='Brazil Super Fine Natural' coffee_label='Super Fine Natural' blend_label=None store_label='Home' batchsize=0.54 weight=0.54 weight_estimate=0.4536 measured=True color=0 moisture=0.0 density=0.0 roastingnotes='' cupping_score=50.0 cuppingnotes='' prefix='arc_242' plus\schedule.py::__init__:866 self datacount=1 scheduleID='66e1dfadd83761aa4544bacc' scheduleDate='2024-09-14' sequence_id=1 roastUUID=UUID('3876535f-e4fd-440f-8d07-7bbf07860f47') roastdate=datetime.datetime(2024, 9, 14, 19, 28, 30, tzinfo=TzInfo(UTC)) roastbatchnr=242 roastbatchprefix='arc_' title='Brazil Super Fine Natural' coffee_label='Super Fine Natural' blend_label=None store_label='Home' batchsize=0.54 weight=0.54 weight_estimate=0.4536 measured=True color=0 moisture=0.0 density=0.0 roastingnotes='' cupping_score=50.0 cuppingnotes='' prefix='arc_242' aw now2024-09-28 17:38:13.488265+00:00 __class__ plus\schedule.py::__init__:779 self layout leftarc_242 __class__ plus\schedule.py::getRight:925 self roastdate2024-09-14 19:28:30+00:00 roastdate_date_local2024-09-14 days_diff14 task_date_str babel\dates.py::format_date:683 date2024-09-14 formatlong localeen babel\dates.py::get_date_format:352 formatlong localeen babel\core.py::date_formats:905 selfen babel\core.py::_data:439 selfen babel\localedata.py::load:147 nameen merge_inheritedTrue dataNone get_global parentroot parts['en'] babel\localedata.py::load:147 nameroot merge_inheritedTrue data{} filenameC:\tools\Artisan\_internal\babel\locale-data\root.dat fileobj 

### Steps To Reproduce

I started the app normally from my desktop shortcut and then tried to open the scheduler feature and got this error pop up.
![artisan-error](https://github.com/user-attachments/assets/051afa80-da9c-4150-be43-c3316611a788)
[artisan-settings.aset.txt](https://github.com/user-attachments/files/17175702/artisan-settings.aset.txt)

### Artisan Version

3.0.0

### Computer OS and Version

Windows 11

### Connected devices or roasting machine

Arc 800 connected but not powered on

### Files

- [ ] A sample profile *.alog file, renamed to *.alog.txt is attached.

- [X] A settings file (Help>> Save Settings) *.aset, renamed to *.aset.txt is attached.

- [X] Screenshots are attached.

- [ ] No files are attached.

**Comment by MAKOMO** [comment]
Fixed in the current Artisan v3.0.2
