### ISSUE TITLE
I have a Santoker R3 Im trying to connect to artisan

### ISSUE THREAD

**Issue by airwavecoffee** [artisan-roaster-scope/artisan#1702]
I recently bought a used santoker r3 
I downloaded the santoker app on iPad, it works but not a huge fan.

I want to connect to artisan via usb. I have downloaded different usb drivers and used my Mac and a pc
cannot figure out how to connect. I downloaded the zip files and extracted them is there anything else that needs to be done? what am I doing wrong?

Currently using Mac 14.6.1
I can use windows 10 if needed (easier)
[artisan-settings.aset.zip](https://github.com/user-attachments/files/17179750/artisan-settings.aset.zip)

**Comment by MAKOMO** [comment]
[Santoker R Series support](https://artisan-scope.org/machines/santoker/) was just improved. Could you please check if the setup `R Series Bluetooth` (menu `Config >> Machines >> Santoker`) of the current [Continuous Build](https://github.com/artisan-roaster-scope/artisan/releases/tag/continuous) works with your machine (assuming it is not a R Master Series and it features Bluetooth communication).

**Comment by MAKOMO** [comment]
Stall

**Comment by MonkeyBeast0113** [comment]
Hello, 

I had the same issue connecting my R3. Did you figure it out? I’m using windows. Thanks

**Comment by MAKOMO** [comment]
The next Artisan version will improve Santoker support and should work fine with the R3. Either test the current Continuous Build or wait until the end of the month for the next version.
