### ISSUE TITLE
Drop label dissappearing

### ISSUE THREAD

**Issue by chuckcoffee** [artisan-roaster-scope/artisan#172]
When I drop my  coffee beans I hit the drop button and the label "drop" shows up however once I hit off the label "drop" disappears. I am on artisan 1.2 in Windows 7, Huky roaster, phidget

![artisan 1 2 about 2018-04-02 07 26 19](https://user-images.githubusercontent.com/38003630/38194713-38a87e3e-3647-11e8-8258-90837fc507a5.jpg)

![drop label](https://user-images.githubusercontent.com/38003630/38194683-ff5421ba-3646-11e8-88d0-2dce40a12f42.jpg)

![after roast1](https://user-images.githubusercontent.com/38003630/38194816-f096c19a-3647-11e8-92dc-6aadbfd0de10.jpg)

**Comment by roasterdave** [comment]
Fixed in the upcoming v1.3 release.  Thanks for reporting.
