### ISSUE TITLE
Yoctopuce meteo 2 is not working

### ISSUE THREAD

**Issue by beanoccio** [artisan-roaster-scope/artisan#1724]
### Problem Description

Is it a bug in artisan, or is incomplete documentation the cause?
The device should automatically enter the ambient temperature, humidity and air pressure into the roasting profile.

![image](https://github.com/user-attachments/assets/1d1e0047-2823-47f0-91bc-0ee695041746)

### Artisan Version

3.0.3 Continuous Build

### Computer OS and Version

Windows 11

### Connected devices or roasting machine

DIY Roaster Arduino Mega

### Files

- [ ] A sample profile *.alog file, renamed to *.alog.txt is attached.

- [ ] A settings file (Help>> Save Settings) *.aset, renamed to *.aset.txt is attached.

- [X] Screenshots are attached.

- [ ] No files are attached.

**Comment by MAKOMO** [comment]
Does a direct USB connection work for you?

**Comment by beanoccio** [comment]
What do you mean by a "direct" USB connection?
The yoctopuce meteo is plugged into a USB port and provides the data via a virtual hub.

**Comment by beanoccio** [comment]
Ok, without virtual hub, it works.
Thanks a lot!

**Comment by beanoccio** [comment]
Thank you very much. Now I can sleep well.

**Comment by MAKOMO** [comment]
Works for me also with the VirtualHub on macOS. There might be a firewall or something in between in your case.

**Comment by MAKOMO** [comment]
Note, the VirtualHub way is to remove access the device.
