### ISSUE TITLE
not full reset

### ISSUE THREAD

**Issue by beanoccio** [artisan-roaster-scope/artisan#1728]
### Problem Description

The reset is not complete
![image](https://github.com/user-attachments/assets/a1e000a0-8096-456b-9f44-17337b0bfc90)

### Artisan Version

3.0.3 Continuous Build

### Computer OS and Version

Windows 11

### Connected devices or roasting machine

DIY Roaster Arduino Mega

### Files

- [ ] A sample profile *.alog file, renamed to *.alog.txt is attached.

- [ ] A settings file (Help>> Save Settings) *.aset, renamed to *.aset.txt is attached.

- [X] Screenshots are attached.

- [ ] No files are attached.

**Comment by MAKOMO** [comment]
You hit a feature. The batch size is by initialized first from the machines max batch size and then remembers the batch size of you last roast.
