### ISSUE TITLE
Config>Event Event description checkbox setting not retained for subsequent sessions

### ISSUE THREAD

**Issue by Tonefish** [artisan-roaster-scope/artisan#180]
## Expected Behavior
setting would remain as set for subsequent session

## Actual Behavior
setting reverts to unchecked

## Steps to Reproduce the Problem

  1.start Artisan
  2. go to Config Events and check the Descr. box for event
  3. complete session and close Artisan
4. start Artisan again and view the setting

## Specifications

  - Artisan Version: 1.3
  - Artisan Build (number in brackets shown in the about box): ca3c5f16
  - Platform (Mac/Windows/Linux + OS version): Win10
  - Connected devices or roasting machine: phidgets 1048
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

**Comment by roasterdave** [comment]
Thanks for the detailed report! This was duplicated and fixed. The fix will be part of a patch release v1.3.1.
