### ISSUE TITLE
Extra 1 and 2 curves and data are deleted ome time after roast

### ISSUE THREAD

**Issue by mcjosh13** [artisan-roaster-scope/artisan#181]
## Expected Behavior
Data to be retained

## Actual Behavior
Data is erased (Extra 1 and 2). Both the curves and the data in the roast properties

## Steps to Reproduce the Problem

  1.Unsure, I finished the roast, saved it. Then I was messing around with themes a bit and noticed the extra curves data was gone.. not sure if this caused it.
  2.
  3.

## Specifications

  - Artisan Version:1.3

  - Artisan Build (number in brackets shown in the about box):
  - Platform (Mac/Windows/Linux + OS version):
  - Connected devices or roasting machine:
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach a

[ROYAL ETHIOPIAN 4.zip](https://github.com/artisan-roaster-scope/artisan/files/1917716/ROYAL.ETHIOPIAN.4.zip)

ny relevant Artisan *.alog profiles.

**Comment by MAKOMO** [comment]
Cannot reproduce this. Maybe you deleted the extra device and re-added it later. Deleting an extra device also deletes the associated data.
