### ISSUE TITLE
Curve width not working with decimal point

### ISSUE THREAD

**Issue by samuellaw178** [artisan-roaster-scope/artisan#186]
## Expected Behavior
The curve thickness/width setting (for BT, delta BT, or ET) should be adjustable and can be saved permanently. 

## Actual Behavior
The curve width is adjustable between 1.0 (too thin) and 2.0 (too thick). When set to 1.5, the curve thickness is perfect. However, upon restarting the software, the curve thickness setting will be reset to 0.0, resulting in non-visible curves. This problem does not exist when the curve width is set to an integer (1.0 or 2.0). 

## Steps to Reproduce the Problem

  1. Click "Edit axis and curve parameters" button on the top left of the Artisan main screen
  2. Click the 'curves' tab
  3. Adjust the 'Width' under line section to 1.5
  4. Click Apply and OK. 
  5. Close the Artisan Software. Optionally, save the Artisan Setting (but did not make a difference)
  6. Restart Artisan Software. The last roast log will be loaded, but the curves are not visible. 

## Specifications

  - Artisan Version: 1.3 
  - Artisan Build (number in brackets shown in the about box): ca3c5f16
  - Platform (Mac/Windows/Linux + OS version): Windows
  - Connected devices or roasting machine: Mastech MS6514 
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file
[artisan-settings.zip](https://github.com/artisan-roaster-scope/artisan/files/1944926/artisan-settings.zip)

Please attach any relevant Artisan *.alog profiles : Non applicable

**Comment by MAKOMO** [comment]
Samuel, thanks for the detailed report. My last commit should fix this. The fix will be part of the next bugfix release v1.3.1 and is already deployed in the bintray builds https://bintray.com/artisan/artisan-artifacts/artisan/master#files.
