### ISSUE TITLE
Artisan 1.3 crash on Raspbian

### ISSUE THREAD

**Issue by testabean** [artisan-roaster-scope/artisan#187]
## Steps to Reproduce the Problem

  1. Open Artisan
  2. make operations 
      Save as 
      Open
      Save Settings as
      
  3. Artisan crash completely

## Specifications

  - Artisan Version: 1.3.0
  - Artisan Build (number in brackets shown in the about box):
  - Platform (Mac/Windows/Linux + OS version): Raspbian Stretch
  - Connected devices or roasting machine: any
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
!!! Can't do this. Artisan Crashing
Please attach any relevant Artisan *.alog profiles.

**Comment by MAKOMO** [comment]
Which hardware are you running Stretch on?

**Comment by MAKOMO** [comment]
Does "Save" work? Just asking as it is not in your list of crashing commands or is it crashing on all operations opening a file selector?

**Comment by testabean** [comment]
Yes, crashing on all operations opening a file selector. It's a new raspberry Pi 3 B+

**Comment by DavidFW1960** [comment]
Same. I was running the Jessie build on a Pi 3B and v1.2 worked fine no problems. 1.3 crashes when I edit alarms.
If I just start a roast with my previous alarms and settings it works fine.

**Comment by bigl00z3** [comment]
I can confirm the same behaviour in 1.3 (and 1.3.1) on Stretch when:

- saving settings
- changing background graph

Artisan crashes (quit)

Moving back to version 1.2 solves the problem. Using 1.3 on OS X works without issues.

**Comment by samtsai5212** [comment]
Artisan 1.3 crashes probably because it tried to save something without permission. Try to run Artisan in terminal with root privilege:
_sudo artisan_

If you want to make it permanent, run the following:
_sudo nano /usr/share/applications/artisan.desktop_
find the line:
_Exec=artisan %U_
Change to:
_Exec=sudo artisan %U_
press ctrl+X then 
press  Y then eneter

**Comment by MAKOMO** [comment]
Thanks @samtsai5212 for this valid workaround which seems to work fine. We are investigating what the cause of this is and try to fix it..
