### ISSUE TITLE
Crash when trying to load brackground on RPI

### ISSUE THREAD

**Issue by peanutyost** [artisan-roaster-scope/artisan#188]
## Expected Behavior
load the background profile

## Actual Behavior
crashed program on click the load button

## Steps to Reproduce the Problem

  1.open artisan
  2.open the brackground window
  3.click the load button

## Specifications

  - Artisan Version:1.3.0
  - Artisan Build (number in brackets shown in the about box):?
  - Platform (Mac/Windows/Linux + OS version):linux stretch
  - Connected devices or roasting machine:serial
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

**Comment by MAKOMO** [comment]
Running via sudo is a valid workaround for this crash for now. We are working on a fix for future releases...

**Comment by MAKOMO** [comment]
I close this one as it seems to have the same cause then Issue #187
