### ISSUE TITLE
Add Support for Diedrich Roasters

### ISSUE THREAD

**Issue by thecardinelli** [artisan-roaster-scope/artisan#189]
If this ticket is too vague, or for some reason this isn't the correct way to document it, then I will delete it, but the goal of this post is to eventually support Diedrich roasters. Is there a reason they aren't currently supported?

**Comment by MAKOMO** [comment]
Yes, we still wait for technical details and an ok from their side. Request was sent quite a while ago and they received several pings. Maybe if customers bug them...

**Comment by MAKOMO** [comment]
added in v1.5
