### ISSUE TITLE
Mastech MS6514 Bytes Issue

### ISSUE THREAD

**Issue by BeanMonkey** [artisan-roaster-scope/artisan#190]
## Expected Behavior
Mastech thermometer to read correctly whilst roasting.

## Actual Behavior
From the third roast today it randomly started to state '18/35 bytes received, 18 bytes needed' intermittently and not displaying any graphic or temperature read in data. 

## Steps to Reproduce the Problem

  1. Have tried and successfully reinstalled uart drivers
  2. Upgraded to 1.3 artisan and back to 1.1 both with no effect. 
  3. Almost threw it out the window to see if that would help

## Specifications

  - Artisan Version: 1.1
  - Artisan Build (2):
  - Platform (Windows):
  - Connected devices or roasting machine: Mastech MS6514

**Comment by MAKOMO** [comment]
Most likely a hardware or setup problem external to Artisan. As nothing can do about this on the Artisan side I close this
