### ISSUE TITLE
v1.3 Negative value do not work anymore in Event/Button/Value

### ISSUE THREAD

**Issue by bigl00z3** [artisan-roaster-scope/artisan#191]
## Expected Behavior
When creating buttons in Config/Events/Buttons negative value should be possible in the "Value" field (works in Artisan 1.1 and 1.2)

## Actual Behavior
In Artisan 1.3, it is not possible to enter a negative value in the "Value" field of Config/Events/Buttons 

## Steps to Reproduce the Problem

  1. Open Config/Events/Buttons  
  2.In "Value" negative "-" is not possible anymore

## Specifications

  - Artisan Version: 1.3.0 
  - Artisan Build (number in brackets shown in the about box): (ca3c5f1) 
  - Platform (Mac/Windows/Linux + OS version): OS X 10.13.4 and Raspberry Stretch
  - Connected devices or roasting machine: Phidget 1048

  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

**Comment by MAKOMO** [comment]
Fixed by Commit #42a4609f3a614d86dc5c9e378869eee8b2ce4b92

Could you please verify using the current [bintray builds](https://bintray.com/artisan/artisan-artifacts/artisan/master#files)?

Thanks for reporting!
