### ISSUE TITLE
Roast properties: weight & volume to allow hundredths not tenths?

### ISSUE THREAD

**Issue by InvisibleOrdinary** [artisan-roaster-scope/artisan#198]
## Expected Behavior
To be able to enter x.xx when entering initial and ending weight… it would be really nice to be able to record the same accuracy for

## Actual Behavior

weight & volume only allow to enter to tenths of a unit

## Specifications

  - Artisan Version: 1.3.0 
  - Artisan Build (number in brackets shown in the about box): (ca3c5f1)
  - Platform (Mac/Windows/Linux + OS version): Mac OS 10.13.4
  - Connected devices or roasting machine: phidgets 1048 

  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.

[180508_artisan-settings.aset.zip](https://github.com/artisan-roaster-scope/artisan/files/1988499/180508_artisan-settings.aset.zip)

Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
You should be able to enter begin and end weight to the tenths of a unit. See the attached screen shot using your settings file with weight unit set to lb.

<img width="776" alt="screen shot 2018-05-11 at 12 07 38" src="https://user-images.githubusercontent.com/13909011/39919507-1eff6312-5514-11e8-8f4f-91389d362a73.png">

What is exactly missing?

**Comment by roasterdave** [comment]
I see the problem  The field input validator allows only one decimal place to be entered.   However, the result from a conversion or calculation is displayed with multiple decimal places.
