### ISSUE TITLE
Start up Artisan with fullscreen as default

### ISSUE THREAD

**Issue by samtsai5212** [artisan-roaster-scope/artisan#199]
## Expected Behavior
Since Artisan is the only app I care to run on my RPi with a 10" touch screen, I hope the future version can start up the program with fullscreen as an option in default.
## Actual Behavior
Try to touch the tiny menu on the touch screen to activate the full screen function with my fat finger.
## Steps to Reproduce the Problem

  1. 
  2. 
  3. 

## Specifications
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

  2a02082

Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
Fixed by Commit 8f3c3b398bed442ce227c0ae9c259556332f10a2
