### ISSUE TITLE
Save pdf preview or log graph with .alog 

### ISSUE THREAD

**Issue by InvisibleOrdinary** [artisan-roaster-scope/artisan#210]
## Expected Behavior
Dunno whether there is a comparable action in other os's but for mac, in the finder, hitting space when the file is selected give a quick view if its contents… I don't know how it actually works, but generally there is a pdf (jpg, png?) attached to the file that allows you to see it without opening it

## Actual Behavior
nothin'

## Steps to Reproduce the Problem

  1. 
  2. 
  3. 

## Specifications

Artisan Version:1.3.0
Artisan Build (number in brackets shown in the about box):(ca3c5f1)
Platform (Mac/Windows/Linux + OS version): Mac OS 10.13.4 (17E202)
Connected devices or roasting machine: Proaster 10K w/ phidgets 1048 (2 probes)
https://github.com/artisan-roaster-scope/artisan/files/2029498/180522_artisan-settings.aset.zip

Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
This Quick Look features is only offered by OS X and not available cross-platform. It works by installing a rendering engine for the corresponding file type in the operating system and not by storing a pre-rendered PDF. This is very difficult to achieve for Artisan profiles as one would need to install half of Artisan as part of such a rendering system.

However, Artisan automatically store a PDF version of a profile along the .alog profiles in the same directory if the flag "Save PDF also" under menu Config >> Autosave is ticked.
