### ISSUE TITLE
No Translations work on Linux/RPi  (artisan 1.3.1) 

### ISSUE THREAD

**Issue by testabean** [artisan-roaster-scope/artisan#211]
## Expected Behavior
Artisan start in German or other Translation

## Actual Behavior
Artisan starts in english 

## Steps to Reproduce the Problem

  1. start artisan 
  2. config: transalation in german
  3. start artisan again: artisan open in english

## Specifications

  - Artisan Version: 1.3.1
  - Artisan Build (number in brackets shown in the about box):
  - Platform (Mac/Windows/Linux + OS version): Ubuntu 16.04 on PC, Raspian Stretch on Raspberry Pi 3B+
  - Connected devices or roasting machine: any
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
The Artisan binary couldn't find the translations as a path was set wrong. I fixed that in source. The patch will be part of the upcoming v1.4 release and is already in the v1.4 pre-build binaries on bintray: https://bintray.com/artisan/artisan-artifacts/artisan/master#files (the updated RPi binary might take another hour to appear).
