### ISSUE TITLE
Ghibli 15 Coffee-tech

### ISSUE THREAD

**Issue by Bocono** [artisan-roaster-scope/artisan#216]
Hi,
I'm trying to conect a Ghibli 15 with artisan but I can't. coffee-tech send me the setting for that but modbus comunication error appears

Thanks
Carlos

**Comment by MAKOMO** [comment]
Hm. An empty report. So everything fine with the Ghibli 15 Coffee-tech and I can close this?

**Comment by Bocono** [comment]
Hi,

No, I need help to conect the ghibli 15 with Artisan.

Carlos
