### ISSUE TITLE
Coffee-tech Ghibli 15 : Modbus comunication error

### ISSUE THREAD

**Issue by Bocono** [artisan-roaster-scope/artisan#217]
## Steps to Reproduce the Problem

  1. 
  2. 
  3. 

## Specifications

  - Artisan Version: 1.3.1 (1)
  - Artisan Build (number in brackets shown in the about box):
  - Platform (Mac/Windows/Linux + OS version): **Windows 10**

[artisan-settings - ghibli 15.aset (3).zip](https://github.com/artisan-roaster-scope/artisan/files/2083715/artisan-settings.-.ghibli.15.aset.3.zip)

  - Connected devices or roasting machine: **Coffee-tech Ghibli 15**
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
Ghibli support has been added and will be part of the next release. For now you could unzip and load the attached settings file via Help >> Load Settings.

[Ghibli.aset.zip](https://github.com/artisan-roaster-scope/artisan/files/2172812/Ghibli.aset.zip)
