### ISSUE TITLE
Sliders updated by serial values

### ISSUE THREAD

**Issue by Dathdealer** [artisan-roaster-scope/artisan#218]
Is it possible to update a slider with a serial readed value? (for example from TC4) 

So you could adjust a value on the control board and the silder in Artisan will be updated. 

## Specifications

  - Artisan Version: 1.3
  - Platform: Windows 
  - Connected devices or roasting machine: TC4 with costom firmware

**Comment by MAKOMO** [comment]
by sending data via an extra channel and configuring an event quantifier

**Comment by Dathdealer** [comment]
oh simple.
Thanks!
