### ISSUE TITLE
Hottop B-2K+ right-click and Blue Control button

### ISSUE THREAD

**Issue by RickGroszkiewicz** [artisan-roaster-scope/artisan#220]
## Requested Behavior
Is there any chance you can add a pop-up reminder message when you forget to right-click on the timer LCD, and click on the Blue Control button. Something like "to control the Hottop, you first must right click on the Timer LCD" 

## Actual Behavior
To make the Blue Control button active, you first have to right click on the Timer LCD. This seems rather obscure to me.

**Comment by MAKOMO** [comment]
Rick, thanks for this suggestion. I just added a corresponding information popup. Just note that the "super user mode right click on the Timer LCD" is rather obscure on purpose to add a minimal attention layer to this rather dangerous control mode. Large commercial roasters have a number of safety features that try to keep the machine in a safe operating state independent what input it receives from the operator or via a connected software. This is not the case for this little Hottop.
