### ISSUE TITLE
Ambiant condition (temperature) in Roast Properties does not accept negative values.

### ISSUE THREAD

**Issue by bigl00z3** [artisan-roaster-scope/artisan#221]
## Expected Behavior

As discussed with Marko, in Roast/Properties settings, "Ambient Conditions" the value for the temperature does not accept negative values (in the winter I had negative values in the room.. not fun working conditions). Both negative and positive values should work for this specific field.

## Actual Behavior

Only positive values are working

## Steps to Reproduce the Problem

  1. try to type a values with "-" in front of the number
  2. 
  3. 

## Specifications

  - Artisan Version: Artisan 1.3.1  (but it has been an issue on previous versions too)
  - Artisan Build (number in brackets shown in the about box): 3001eb9
  - Platform (Mac/Windows/Linux + OS version): all
  - Connected devices or roasting machine: Ambrobe and/or Phidget
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by roasterdave** [comment]
Fixed for the next release of Artisan.
