### ISSUE TITLE
Report > Ranking nomenclature isn't obvious

### ISSUE THREAD

**Issue by InvisibleOrdinary** [artisan-roaster-scope/artisan#222]
## Expected Behavior
I don't understand what the term ranking means, and why it is how to compare roasts

## Actual Behavior
choose ranking > web… to see compared roasts in browser window

## Steps to Reproduce the Problem

  1. select file > reports > ranking > web…
  2. select files
  3. look at browser window

## Specifications

  - Artisan Version: Artisan 1.3.0 (ca3c5f1) 
  - Platform (Mac/Windows/Linux + OS version): Max OS 10.13.5 (17F77)
  - Connected devices or roasting machine: Phidgets 1048 (2 probes)
  
[180626_artisan-settings.aset.zip](https://github.com/artisan-roaster-scope/artisan/files/2139884/180626_artisan-settings.aset.zip)

Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
The ranking report allows you to compare the selected profiles w.r.t. key parameters. You can click on the table headers to change the sorting order. That way you can for example easily find out which of the roasts was the longest or hottest or darkest.
