### ISSUE TITLE
Report > Ranking multiple file limit

### ISSUE THREAD

**Issue by InvisibleOrdinary** [artisan-roaster-scope/artisan#223]
## Expected Behavior

To use File > Report > Ranking > Web… to compare multiple roasts. 

## Actual Behavior
It works for a few files, but not for a lot of files… when just a few, it shows both the spreadsheet & visual comparison, however when selecting a lot of files, it only shows the spreadsheet.

## Steps to Reproduce the Problem

  A1. select File > Report > Ranking > Web…
  A2. select 2 files
  A3. see comparison in web browser : spreadsheet, visual graph, & stage comparison

  B1. select File > Report > Ranking > Web…
  B2. select 10+ files (?) I didn't test to see what the actual limit was
  B3. see only the spreadsheet listing of the files, but not any additional visualization or the comparison of stages

## Specifications

  - Artisan Version: Artisan 1.3.0 (ca3c5f1)
  - Platform (Mac/Windows/Linux + OS version): Mac OS 10.13.5 (17F77)
  - Connected devices or roasting machine: Phidgets 1048 + 2 probes (though not al all times, and with & without makes no difference to this issue)

[180626_artisan-settings.aset.zip](https://github.com/artisan-roaster-scope/artisan/files/2139890/180626_artisan-settings.aset.zip)

  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
Yes, this is the intended behavior as from a certain number of selected profiles on it gets impossible to compare them on the graph.
