### ISSUE TITLE
PID Control Duty %

### ISSUE THREAD

**Issue by blondica73** [artisan-roaster-scope/artisan#224]
## Expected Behavior
I expected to be able to set the Duty % in the PID Control window to a value of my choice.  I have a stepper motor valve that controls the roaster and it has 400 steps. 

## Actual Behavior
The duty % is limited to 100%.
## Steps to Reproduce the Problem

  1. Enable Control 
  2. Select "Control"
  3. In the Duty section try changing 100 to 400

## Specifications

  - Artisan Version:1.3.1
  - Artisan Build (number in brackets shown in the about box):
  - Platform (Mac/Windows/Linux + OS version):MAC
  - Connected devices or roasting machine: BC Roaster
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
The PIDs duty ranges between 0-100% by definition. However, now that the Artisan sliders can have a min/max range beyond 0-100 I just changed the code to ensure the mapping of the duty range to the full range of the selected target slider.
