### ISSUE TITLE
Confirmation dialog before exiting active roast

### ISSUE THREAD

**Issue by mgerstgrasser** [artisan-roaster-scope/artisan#225]
## Expected Behavior
While in the middle of an active roast, especially with PID control turned on, Artisan should display a confirmation dialog before exiting this roast, for instance after CMD-N or CMD-Q is pressed.

## Actual Behavior
Artisan immediately and irrevocably stops the active roast. When CMD-N is pressed, for instance, Artisan will ask to save the logged roast, but there is no way to go back and continue the active roast. This can easily happen on accident. For instance, a user might intend to open a new window in a different program, not realising that Artisan has keyboard focus.

## Steps to Reproduce the Problem

  1. Start a new roast, optionally turn on PID control.
  2. Press CMD-N.

## Specifications

  - Artisan Version: 1.3.1
  - Artisan Build (number in brackets shown in the about box): 1
  - Platform (Mac/Windows/Linux + OS version): Mac OS 10.13.5
  - Connected devices or roasting machine: Arduino + TC4

**Comment by MAKOMO** [comment]
CMD-Q opens a popup confirmation dialog if at least 3 readings have been logged and CHARGE is set. The behavior of CMD-N was restricted for the next version to only perform if CHARGE and DROP was already set. A save confirmation dialog is issued in this case if autosave is not active.
