### ISSUE TITLE
Report > Ranking notification (wasReport > Ranking multiple file limit #223)

### ISSUE THREAD

**Issue by InvisibleOrdinary** [artisan-roaster-scope/artisan#226]
## Expected Behavior

This is a followup to issue #223. The reasoning is fair and makes sense [
https://github.com/MAKOMO: "Yes, this is the intended behavior as from a certain number of selected profiles on it gets impossible to compare them on the graph."] given the difficulty of reading a large number of files at the same time, however… for usability's sake, the same command shouldn't result in different views / different sets of data without some indication… There several ways of controlling this… and I'm not advocating for any specific user experience, only that it should be clear what the limitations are and what will result so they they are choosing.

give an indication of the limit for seeing complete data, vs. summary data prior to the user selecting the files to compare 

If the user selects more than the allowable limit, a dialogue with a notification stating that only a summary will be shown… proceed? Y/N

possibly only show a result if the number of files is below that number

## Actual Behavior

It works for a few files, but not for a lot of files… when just a few, it shows both the spreadsheet & visual comparison, however when selecting a lot of files, it only shows the spreadsheet.

## Steps to Reproduce the Problem

A1. select File > Report > Ranking > Web…
A2. select 2 files
A3. see comparison in web browser : spreadsheet, visual graph, & stage comparison

B1. select File > Report > Ranking > Web…
B2. select 10+ files (?) I didn't test to see what the actual limit was
B3. see only the spreadsheet listing of the files, but not any additional visualization or the comparison of stages

## Specifications

  Artisan Version: Artisan 1.3.0 (ca3c5f1)
Platform (Mac/Windows/Linux + OS version): Mac OS 10.13.5 (17F77)
Connected devices or roasting machine: Phidgets 1048 + 2 probes (though not al all times, and with & without makes no difference to this issue)
180626_artisan-settings.aset.zip

Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

Note that you need either add a .txt extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading.

**Comment by MAKOMO** [comment]
resolved by adding a popup dialog that informs the user that ranking report graphs are only generated for up to 10 profiles
