### ISSUE TITLE
NEW REQUEST-INVENTORY

### ISSUE THREAD

**Issue by tpellizzer** [artisan-roaster-scope/artisan#231]
Is anyone working on an integrated inventory system with Artisan? I would love to see one.

**Comment by RickGroszkiewicz** [comment]
I think everyone wants this feature!

**Comment by MAKOMO** [comment]
Work on this has started. Will be available latest next January. Pre-releases will be available earlier.

**Comment by MAKOMO** [comment]
Register for beta at https://artisan.plus/

**Comment by aleprovencio** [comment]
Hello, are there any updates on the development/release of this feature? Does this `v2.0` label means the feature will be merged on the regular artisan?

**Comment by MAKOMO** [comment]
artisan.plus to be released next week
