### ISSUE TITLE
x axis 17 minute limitation

### ISSUE THREAD

**Issue by arkenamun** [artisan-roaster-scope/artisan#234]
Is there a reason why the time axis displays a maximum of 17 minutes? Is it possible display more time indications up to the actual duration of the roast/ warm-up?

Thanks

![17 minutes](https://user-images.githubusercontent.com/22232379/43752548-15138760-9a34-11e8-9984-aaac4df6a08f.jpg)

**Comment by MAKOMO** [comment]
Very strange. How did you manage to end up in this state? What are your axis settings? Could you please attach your Artisan settings file .aset (export via menu Help >> Save Settings) and this profile as alog file?

No there is no limit. You can easily set any time axis max limit you want and the time axis labels should expand to this limit.

**Comment by MAKOMO** [comment]
I'll have to close this as I didn't receive any advice on how to reproduce this.
