### ISSUE TITLE
No 32bit version?

### ISSUE THREAD

**Issue by TravisEvashkevich** [artisan-roaster-scope/artisan#236]
Just wondering if there is a big reason why there isn't a 32 bit version of the installer?

**Comment by MAKOMO** [comment]
32bit systems are not supported any more by some underlying software packages. That does not mean that in principle it would not be possible to run Artisan on 32bit system, but I requires a lot of extra work. You are free to run Artisan from source on a 32bit system. That's the fine thing on open-source. However, there will never be a 32bit installer and also older OS versions will not be supported anymore for the very same reason. However, in case you want to help out and add 32bit installers back to the project you are welcome.
