### ISSUE TITLE
Add folders for pics of green and roasted coffee - for quality contorl and defect  identification 

### ISSUE THREAD

**Issue by brettpavia** [artisan-roaster-scope/artisan#240]
## Steps to Reproduce the Problem

  1. 
  2. 
  3. 

## Specifications

  - Artisan Version:
  - Artisan Build (number in brackets shown in the about box):
  - Platform (Mac/Windows/Linux + OS version):
  - Connected devices or roasting machine:
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
Unrealistic considering the projects resources, but you are free to provide a pull request that we can integrate.
