### ISSUE TITLE
Artisan 1.3.1 on Raspberry pi 3b+

### ISSUE THREAD

**Issue by alansusee** [artisan-roaster-scope/artisan#241]
## Expected Behavior
> I have installed Artisan 1.3.1 on a Raspbery pi 3 b+ updated to newest release, etc.with the 7" touch screen which is an 800 x 480 resolution display.  Artisan works as expected with one issue. when in the "ON" mode and the three LCD's display Dry% Dry>> and FC between the "Edit Axis" icon and the Reset Button they are all cut off on the right edge so one digit is missing/hidden.ie:  

## Steps to Reproduce the Problem

  1. Select start so that Dry%, >>Dry, >>FC lcds are displayed. 
  2. 
  3. 

## Specifications

  - Artisan Version: 1.3.1
  - Artisan Build (number in brackets shown in the about box): (1)
  - Platform (Mac/Windows/Linux + OS version):Raspian 9 Stretch
  - Connected devices or roasting machine: 
Phidgets 1048
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
The RESET button has been hidden to make more room during recording to allow to fully render the PhasesLCD on such small displays.
