### ISSUE TITLE
Quicker save sequence (for batch roasting)

### ISSUE THREAD

**Issue by InvisibleOrdinary** [artisan-roaster-scope/artisan#246]
## Expected Behavior
A smooth and quick way to transition between sequential batches

## Actual Behavior
I am not sure whether I am missing a technique, setting,, or if others have just made up workable work-arounds,… but as I currently understand it, the number of steps to move from one batch to the next is hindering my workflow… Are there tabs that I am not aware of, to set up each batch before roasting, then just move from tab to tab? I read one person who switched back and forth between two installations 
 by moving between MacOS and Parallels/Windows, but that limits at 2…

I would love for the sequence to be a single click that saves the file in the background and (with the same click) moves to the next batch. Probably starts recording as well, since 'charge' resets the timer.

## Steps to Reproduce the Problem

  1. Click dump
  2. Click Reset
  3. Affirm Save
  4. Save file
  5. Click Start
  6. Roast

This sequence takes roughly 15 seconds, which is enough time for the roaster to over-heat, requiring the need to cool it down, etc…

## Specifications

  - Artisan Version:1.3.1
  - Artisan Build (number in brackets shown in the about box): (1)
  - Platform (Mac/Windows/Linux + OS version): MacOS 10.14
  - Connected devices or roasting machine: Phidgets 1048 w/ 2 probes
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Settings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
Use the autosave and new roast (menu File >> New) feature. Check online documentation for those, the Artisan blog or just experiment with those.
