### ISSUE TITLE
cmd-N doesn't work in all cases (relates to profile bg dialogue)

### ISSUE THREAD

**Issue by InvisibleOrdinary** [artisan-roaster-scope/artisan#247]
## Expected Behavior
pressing cmd-n begins new roast

## Actual Behavior
NOTE: I haven't test all possible cases, so this is just how I have discovered it, but not necessarily how the bug is triggered: 

autosave is on, as is save pdf

after the first roast - whether you load a profile in the background or not - you can type cmd-n to begin new roast (autosave current roast)

if you change the profile, or possibly adjust anything in the cmd-b dialogue, or maybe just open that dialogue, then cmd-n ceases to open new roast/autosave current roast. 

When this happens, the menu file/new/new continues to work as expected

## Steps to Reproduce the Problem

see above

## Specifications

  - Artisan Version: 1.3.1
  - Artisan Build (number in brackets shown in the about box): (1)
  - Platform (Mac/Windows/Linux + OS version): 10.14
  - Connected devices or roasting machine: none currently - I wil test later today when connected to phidgets 1048 & update ticket
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

[181002_artisan-settings.aset.zip](https://github.com/artisan-roaster-scope/artisan/files/2440112/181002_artisan-settings.aset.zip)

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
Unclear report that cannot be reproduced. The NEW roast feature is independent of the background profile. However, during recording a new roast is only started if the existing one is completed, thus already has a CHARGE and DROP event established. I improved the message from the brief "Incomplete profile" into "NEW ROAST canceled: incomplete profile lacking CHARGE and DROP found". Found also that after a factory reset, the NEW/NEW action was missing from the menu. Fixed that too.

Note that the keyboard shortcut CMD-N is always bound to the corresponding menu action by the operating system and if one works the other works too.
