### ISSUE TITLE
Snap Events check box does not persist

### ISSUE THREAD

**Issue by arkenamun** [artisan-roaster-scope/artisan#251]
Choosing "Snap" check box under Config/Events does not persist when settings saved then reloaded.

## Specifications

  - Artisan Version: 1.3.1 and 1.4.0
  
[artisan-settings simple with Step-plus and Snap.aset.txt](https://github.com/artisan-roaster-scope/artisan/files/2449044/artisan-settings.simple.with.Step-plus.and.Snap.aset.txt)

**Comment by MAKOMO** [comment]
Confirmed and fixed in source. Thanks for reporting.
