### ISSUE TITLE
Charge Temp Options

### ISSUE THREAD

**Issue by bleeg10** [artisan-roaster-scope/artisan#261]
## Expected Behavior
Would be awesome if there was an option to base the automatic charge temp displayed on the graphs with ET or BT. 

## Actual Behavior
Currently the automatic charge temp is marked on the graph as BT.

## Steps to Reproduce the Problem

  1. Add an option in the config menu
  2. Make a radio button to choose BT or ET for the charge temp
  3. 

## Specifications

  - Artisan Version: 1.3.1
  - Artisan Build (number in brackets shown in the about box): 1
  - Platform (Mac/Windows/Linux + OS version): Windows
  - Connected devices or roasting machine: San Franciscan 25
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

[artisan-settings_for_HoC.zip](https://github.com/artisan-roaster-scope/artisan/files/2469853/artisan-settings_for_HoC.zip)

**Comment by MAKOMO** [comment]
stall
