### ISSUE TITLE
Feature Request: Allow for an offset wrt to individual temp probes

### ISSUE THREAD

**Issue by InvisibleOrdinary** [artisan-roaster-scope/artisan#266]
## Expected Behavior

( I'll note that this is either already available and I just can't a find reference to it, or a feature request…)

To be able to set an offset for any probe reading in Artisan so that they are in sync with readings on any other external display of the same probe

## Actual Behavior

BT at Artisan reads +5° (F) from reading at phidgets
ET at Artisan reads +4-4° (F) from reading at phidgets

Longer explanation:

While my BT in Artisan reads pretty close (~ +5° F) to the readout on the phidgets 1048… the ET in Artisan display is about 404° F above what the phidgets reads (both probes have digital displays attached to the roaster. 

There are two issues that this produces:

1 - The recording temps are out of alignment with the temp of one probe but not both. and while they are consistently out of sync, so are still useful, it's sloppy recording

2 - Since the max reading in Artisan is 1000°. when the ET temp (phidgets) is above 600, Artisan registers a .1° because it can't go above 1000. And so plots a straight line @ 1000° F until the temp drops below 596° F

## Specifications

  - Artisan Version: from at least V1.1 to current (including 1.5)
  - Artisan Build (number in brackets shown in the about box): (1)
  - Platform (Mac/Windows/Linux + OS version): mac OS 10.14, but goes back to at least 10.13.x
  - Connected devices or roasting machine: phidgets 1048 w/two probes (K-type)
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.

[181016_artisan-settings.aset.zip](https://github.com/artisan-roaster-scope/artisan/files/2486033/181016_artisan-settings.aset.zip)

Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
"(both probes have digital displays attached to the roaster." sounds scary to me. Phidgets do not have any displays, so you might have connected those probes to both, a device on your roaster that has a display (like a PID) and at the same time to a Phidget. This is not recommended an can lead to all kind of interaction problems on those sensitive measuring systems. An offset of 404° F sounds scary to me!

Anyhow, you can enter a symbolic formula to every channel in Artisan where the variable x is bound to the current reading of the device. Thus a formula like x+10 would add a constant offset to the reading of that channel. Way more complex formulas are possible. Check the Artisan blog on symbolic formulas (there is a search field).
