### ISSUE TITLE
feature request: workspaces (selectable multiple profile settings)

### ISSUE THREAD

**Issue by InvisibleOrdinary** [artisan-roaster-scope/artisan#268]
## Expected Behavior

It would be extremely useful to workflow to be able to switch between multiple profile settings (workspaces) from the main menu or other in-app selectable method (rather than loading various files) to be able to move quickly between different roasters (i.e. 1-barrel sample, 4-barrel sample, batch 10K, batch 15k…) Allowing them to be saved, updated etc… 

Would also allow ease to have different workspaces to be used for different roaster-operators for the same machine. 

As an example, if you are familiar with how Adobe uses these workspaces in CC Creative Cloud. It helps there with moving between different type of workflows, monitor setups (single monitor (laptop) and dual screen…) etc. Adobe also allows export of these settings as a separate file that includes all settings & workspaces so you can transfer set-ups setting between machines

## Actual Behavior

Settings need to be saved and loaded from their respective files when switching between set-ups or roasters or roaster-operators. 

Currently, because of the 

## Steps to Reproduce the Problem

  1. Set up Artisan as needed for Roaster/workspace 1
  2. menubar -> Help -> Save Settings…
  3. Save file with memorable name
  4. Change settings to work for Roaster/workspace 2
  5. menubar -> Help -> Save Settings…
  6. Save file with memorable name
  7. When beginning to roast on Roaster 1…
  8. menubar -> Help -> Load setting…
  9. Navigate to & select settings file
  10. begin roasting as normal
  11. When changing to roast on Roaster 2…
  12. menubar -> Help -> Load setting…
  13. Navigate to & select settings file
  14. begin roasting as normal

## Specifications

  - Artisan Version: 1.5
  - Artisan Build (number in brackets shown in the about box): fc6ebda
  - Platform (Mac/Windows/Linux + OS version): Mac OS 10.14
  - Connected devices or roasting machine: Phidgets 1048 w/2 thermocouple on a Proaster 10K; Phidgets VINT w/ 2 thermocouples + air & gas pressure on a Pinhalense sample roaster
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
Loading a complete Artisan setting is available via the main menu under Help, which is just one click. Thanks for comparing Artisan with Adobe products. I assume Adobe have slightly more resources as this project to optimize the workflow for their users. WONTFIX. Sorry.
