### ISSUE TITLE
mac 1.4 and 1.5 not interacting with Aillio Bullet, 1.3 does work

### ISSUE THREAD

**Issue by tjburtones** [artisan-roaster-scope/artisan#270]
## Expected Behavior
I expected version 1.4 and 1.5 to communicate with my Aillio Bullet. Version 1.3 does work

## Actual Behavior
Software has a message that there is "no backend"

## Steps to Reproduce the Problem

  1.  Start Artisan> new> 
  2. 
  3. 

## Specifications

  - Artisan Version: 1.5
  - Artisan Build (number in brackets shown in the about box): (fc6ebda) 
  - Platform (Mac/Windows/Linux + OS version): Mac 10.13.6
  - Connected devices or roasting machine: Aillio Bullet R1

[artisan-settings_issue.aset.txt](https://github.com/artisan-roaster-scope/artisan/files/2494434/artisan-settings_issue.aset.txt)

  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
It turned out to be a build error resulting in a USB lib missing from the Mac OS X app. Build scripts have been fixed now and a new v1.5 Mac OS X build has been uploaded. Thanks for reporting!
