### ISSUE TITLE
Crashing on Multiple Event Button

### ISSUE THREAD

**Issue by reizao** [artisan-roaster-scope/artisan#271]
## Expected Behavior
Not Crash

## Actual Behavior
Crash

## Steps to Reproduce the Problem

  1. Click on a combined event button
  2. Crash
  3. 

## Specifications

  - Artisan Version: 1.5
  - Artisan Build (number in brackets shown in the about box): fc6ebda9
  - Platform (Mac/Windows/Linux + OS version): Windows 8.1
  - Connected devices or roasting machine: Phidgets
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

[artisan.zip](https://github.com/artisan-roaster-scope/artisan/files/2497245/artisan.zip)

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by reizao** [comment]
It happens on the Raspberry Pi too.

**Comment by MAKOMO** [comment]
Fixed by Commit 23080851ad41f7fd3438d426fa8e4ccee77f457d

**Comment by MAKOMO** [comment]
You can test this using a current build from BinTray https://bintray.com/artisan/artisan-artifacts/artisan/master#files
