### ISSUE TITLE
Windows Scaling High DPI devices

### ISSUE THREAD

**Issue by Keltbear** [artisan-roaster-scope/artisan#272]
## Expected Behavior
To View entire application

## Actual Behavior
Cannot get entire application on the screen.
Device needs to be at 200% scaling due to high DPI
Application fine at lower scaling rates, however everything else is then Tiny, and application is still large

## Steps to Reproduce the Problem

  1.  Turn Windows Scaling Up to 200%
  2.  
  3. 

## Specifications

  - Artisan Version: 1.5
  - Artisan Build (number in brackets shown in the about box):
  - Platform (Mac/Windows/Linux + OS version): Windows
  - Connected devices or roasting machine:
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by poundy** [comment]
I actually can't repro this on 1.5.  In fact, the last few releases have improved the high DPI support in my view. My only Artisan device is a Surface Book, which runs at 200% and 3000x2000 resolution. The Artisan screen, the menus, the reset/on/start etc buttons, and the buttons at the bottom of the screen when in a roast are all much more usable than they were back near 1.0 when I last asked Marko about this. 
I'm running Windows 10 1809 and in the Insiders Fast stream, but this improvements have been seen even prior to Win10 1803 builds.

**Comment by MAKOMO** [comment]
Support for high DPI screens depends on the GUI lib underlying Artisan, which improved dramatically on moving from Qt v4 to Qt v5 for Artisan v1.2 for all platforms (OS X was on v5 already a bit before) and updating the graph lib matplotlib. I close this issue as we cannot improve here ourself, but depend on Qt/matplotlib. However, we keep on always including the latest stable versions of those libs in our builds.
