### ISSUE TITLE
Request: Custom Events

### ISSUE THREAD

**Issue by reizao** [artisan-roaster-scope/artisan#277]
## Expected Behavior

Can in the future versions add events, and alarms can be fired by this events?

Can the Default events name be modified?

For example, can you add an event between Dry End and FC? And this event can start any alarm. For example, can 2 minutes after this event or 20 degrees after this event an alarm be fired?

## Steps to Reproduce the Problem

  1. 
  2. 
  3. 

## Specifications

  - Artisan Version:
  - Artisan Build (number in brackets shown in the about box):
  - Platform (Mac/Windows/Linux + OS version):
  - Connected devices or roasting machine:
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
This will be possible in the next version using an event button that sets the event value of one type to a certain value, an additional Virtual Device to map event values to curves, and an alarm that triggers based on that the data in that additional curve. What is missing from v2.0 to enable this is mostly the mapping between event values and curve data which is broken in v2.0 and now has been fixed for v2.1.
