### ISSUE TITLE
Modbus Communication Error

### ISSUE THREAD

**Issue by Daveveif** [artisan-roaster-scope/artisan#283]
Hello,

when I try to use Artisan on my macbook, I get "Modbus Communication Error". On my Imac I do not get this error, things are working.
I've copied the settings from my Imac to my macbook, still getting the error message. 

Specifications (on both devices)

  - Artisan Version: 1.5.0. 
  - Artisan Build (number in brackets shown in the about box): (fc6ebda)
  - Platform (Mac/Windows/Linux + OS version): Mac
  - Connected devices or roasting machine: BSC 05 Manual

[Daveveif artisan settings.zip](https://github.com/artisan-roaster-scope/artisan/files/2615001/Daveveif.artisan.settings.zip)

Any idea how I can fix this issue?
(I made already a clean installation of my macbook, to make sure I do not have old drivers etc)

thanks
Dave

**Comment by MAKOMO** [comment]
This looks like a request for supporting you in your setup and not as an issue in the Artisan software, thus I close this issue.

Both setups are different in several aspects. However, they both link to the same serial port in the MODBUS tab (menu Config >> Port; 3rd tab). Serial ports are unique per machine. If you transfer settings from one machine to the next you need to update the serial port. Plug-in your device and select the corresponding port from the popup.
