### ISSUE TITLE
Feature request: second extra background curve

### ISSUE THREAD

**Issue by mcjosh13** [artisan-roaster-scope/artisan#285]
Hi,

I thought I would like to humbly request a feature.. It would really be a benefit (to me at least, and I would assume others) if you could add in more than one extra background thermocouple graph. I currently have 5 thermocouples ( Bean T, Environmental T,  Drum T, Incoming air T 1, Incoming air T 2) but need to choose between displaying the Drum T or the Incoming air T from the previous roast. If both could be displayed it would be a nice improvement. Thanks for your consideration!

**Comment by mcjosh13** [comment]
Hi,

I thought I would like to humbly request a feature.. It would really be a benefit (to me at least, and I would assume others) if you could add in more than one extra background thermocouple graph. I currently have 5 thermocouples ( Bean T, Environmental T,  Drum T, Incoming air T 1, Incoming air T 2) but need to choose between displaying the Drum T or the Incoming air T from the previous roast. If both could be displayed it would be a nice improvement. Thanks for your consideration!

**Comment by mike-roaster55** [comment]
Hi,
Strangely Version 1 displayed both my Extras curves in the Background.  Now Version 2 only displays one Extra in the Background.  I plot Air Speed and Heater potentiometer positions in Artisan so it's very important to me to see both Extras in the Background.  In Version 2, I can only select one Extra to display.  Can we have the Options - None, One Extra, All Extras in the drop-down box in the Load Background dialogue box please?  cheers Mike

**Comment by MAKOMO** [comment]
added a second extra background curve
