### ISSUE TITLE
Add support for Phidgets REL1100 (trivial)

### ISSUE THREAD

**Issue by AlexGS74** [artisan-roaster-scope/artisan#286]
This is a feature request.

The already supported OUT1100 and REL1100 both have the same exact API and differ only in "electrical" part. The REL1100 is able to switch on more powerful lines.

If I understand the code right, adding these two lines will enable support for both devices:
![image](https://user-images.githubusercontent.com/8890708/50171978-9562db80-02b9-11e9-8d4f-0a13107e1406.png)

Thank you!

**Comment by MAKOMO** [comment]
Thanks for the suggestion. Added also support for REL1000 and first 4 ports of REL1101. Note that only one of those output devices is supported at a time as the out commands do not allow to choose to which device the commands are to be send.

Fixed by f25c0beb700d4d12735781f89f5c0ef36e5b7841.
