### ISSUE TITLE
Sampling rate is to high (several point per seconds) in beta build 9162e3a

### ISSUE THREAD

**Issue by bigl00z3** [artisan-roaster-scope/artisan#292]
## Expected Behavior
Sampling rate was set at 1 second (and also to test at 3 seconds) with latest beta. There should be 1 data per second. Not more

## Actual Behavior
Sampling rate is much higher than expected (probably linked with actual Phidget sampling rate and not Artisan). With the setting at 3 seconds (or even 10seconds), the actual sampling rate is 4 points per seconds. (see attached .alog file).
Note with a sampling rate set at 10.0s I got 107 data points in 15 seconds log.

[Sampling rate at 3s.alog.txt](https://github.com/artisan-roaster-scope/artisan/files/2719266/Sampling.rate.at.3s.alog.txt)

--> Raspberry pi is not powerful to manage the different connected Phidgets at that speed.

## Steps to Reproduce the Problem

  1. Install Artisan 1.6.0 (build 9162e3a)
  2. Set sampling rate to 3 seconds ( just to make sure it is clearly slower than the usual 1sec)
  3. Start a roast, after 1 few seconds 
  4. Check sampling rate in Roast/Properties/Data Sampling is of around 4x per seconds

## Specifications

  - Artisan Version: 1.6.0 (beta bintray)
  - Artisan Build (number in brackets shown in the about box): 9162e3a
  - Platform (Mac/Windows/Linux + OS version): Raspberry Raspbian, OS X
  - Connected devices or roasting machine: Phidgets (Ambiants HUM, 1048, 1135, VINT HUB0000)
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
Another typo. Don't code in between the years! Commit 72dba748d479c5152f58d6d1e24f05cf6c25b975 fixes this. New builds should be up on BinTray latest in 2h. Thanks for the quick test and reporting of this one.
