### ISSUE TITLE
Device support - Fluke

### ISSUE THREAD

**Issue by pj47** [artisan-roaster-scope/artisan#294]
## Expected Behavior
Is there a way to connect a Fluke thermocouple data logging device to Artisan?  Such as the 54 II B dual channel datalogger with the IR to USB data cable. 

## Steps to Reproduce the Problem

  1. 
  2. 
  3. 

## Specifications

  - Artisan Version:
  - Artisan Build (number in brackets shown in the about box):
  - Platform (Mac/Windows/Linux + OS version):
  - Connected devices or roasting machine:
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
No Fluke is supported. Check https://artisan-scope.org/ for the list of supported devices and machines. In case you want to add support for the Fluke, please submit a corresponding Pull Request with your code for integration.
