### ISSUE TITLE
Smooth ROR

### ISSUE THREAD

**Issue by MKRoaster** [artisan-roaster-scope/artisan#301]
## Expected Behavior

ROR graph should me smooth, even if "Sampling Interval" <= 1s

## Actual Behavior

ROR is not smooth (Interval 1s or 0.5s)

![image](https://user-images.githubusercontent.com/36403678/51609009-50197580-1f19-11e9-97c7-006800740814.png)

## Steps to Reproduce the Problem

  1. Just roast coffee
  2. 
  3. 

## Specifications

  - Artisan Version: 1.3, 1.4, 1.5 (All versions)
  - Artisan Build (number in brackets shown in the about box):
  - Platform (Mac/Windows/Linux + OS version): Windows
  - Connected devices or roasting machine: Coffed SR5
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

[Artisan.zip](https://github.com/artisan-roaster-scope/artisan/files/2787456/Artisan.zip)

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
Your profile shows significant noise on the bean temperature (BT) signal. You see this if you turn smoothing completely off. 

<img width="1174" alt="screen shot 2019-01-23 at 16 04 14" src="https://user-images.githubusercontent.com/13909011/51615918-4435af80-1f29-11e9-8ee6-fce2e9ed8f15.png">
<img width="584" alt="screen shot 2019-01-23 at 16 06 57" src="https://user-images.githubusercontent.com/13909011/51615921-44ce4600-1f29-11e9-9d2e-36b7a0fd0501.png">


Further your BT signal has only a resolution of one decimal thus computing a RoR at short intervals leads to a lot additional digital noise. So either you increase your sampling interval to compensate for this low resolution, or you increase the smoothing parameters ("Smooth Deltas" and "Delta Span"). I did that for you here.

<img width="584" alt="screen shot 2019-01-23 at 16 10 17" src="https://user-images.githubusercontent.com/13909011/51615984-6fb89a00-1f29-11e9-874d-57dd4f860812.png">
<img width="1392" alt="screen shot 2019-01-23 at 16 10 19" src="https://user-images.githubusercontent.com/13909011/51615985-721af400-1f29-11e9-956f-2c945908476d.png">


I will close this as I do not see that this is a software issue. Shorter sampling interval of low-resolution signals require more smoothing to achieve the same representation as with larger sampling interval. There is no way around that.

Btw. the settings you attached in that archive (which defines all phases limits as 0) do not correspond to the ones on taking your screenshot (that comes with proper phases limits).
