### ISSUE TITLE
Stop making changes from playback

### ISSUE THREAD

**Issue by MKRoaster** [artisan-roaster-scope/artisan#302]
## Expected Behavior

If i want to run roasting based on background (Playback event) and somewhere "coolingend" shows, artisan stops making auto changes (change power, airflow)

## Actual Behavior

Even if in background there is coolingend, artisan should make changes based on background

## Steps to Reproduce the Problem

  1.  Run roasing, change power few times till 2 minutes, after 2 minutes push "coolingend", make additional power changes
  2. Save the profile and load in background with "playback events"
  3. After coolingend event from background next events from background won't occur

## Specifications

  - Artisan Version: 1.3, 1.4, 1.5
  - Artisan Build (number in brackets shown in the about box):
  - Platform (Mac/Windows/Linux + OS version): Windows
  - Connected devices or roasting machine: Coffed SR5
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

[Artisan2.zip](https://github.com/artisan-roaster-scope/artisan/files/2787508/Artisan2.zip)

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
Fixed by commit 1de3b69ded3971407c299e4c7fb1bba52a620117. Thanks for reporting!
