### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by InvisibleOrdinary** [artisan-roaster-scope/artisan#303]
## Desired Behavior

Option to add additional LCD data to the large LCD window. An additional 1-2 data points, writ large would be helpful during roasting… alternately, larger LCD of the right of the main window would work too

## Actual Behavior

only able to see time, BT, & ET

**Comment by MAKOMO** [comment]
Added large Delta, PID and Extra LCDs in commit 362da4b8861a18e81655d00c01bba79fc4819b7a

**Comment by InvisibleOrdinary** [comment]
Thank you

can the current beta build include a mac OS version? sometimes they do, sometimes they don't, but this one didn't

cheers

Dave

**Comment by MAKOMO** [comment]
Dave, sorry for this. It seems that sometimes our automatic build system is overwriting already uploaded artifacts. There seems to be a race condition. I manually triggered a new build for Mac OS and now the build is online (until we trigger another build by another commit).
