### ISSUE TITLE
Display temp more precisely

### ISSUE THREAD

**Issue by MKRoaster** [artisan-roaster-scope/artisan#304]
## Expected Behavior
On LCD, temp could display temp after "dot" 192.1

## Actual Behavior

Maybe i cant find wright settings, but:

Curently display temp not so precisly -> 192, but after roasting is finished, in selected places of first crack and dry it shows temp after "dot"

## Steps to Reproduce the Problem

  1. 
  2. 
  3. 

## Specifications

  - Artisan Version: 1.4, 1.5
  - Artisan Build (number in brackets shown in the about box):
  - Platform (Mac/Windows/Linux + OS version): Windows
  - Connected devices or roasting machine: Coffed SR5
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

[Artisan.zip](https://github.com/artisan-roaster-scope/artisan/files/2791681/Artisan.zip)

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
Under menu Config >> Curves, UI tab you find the option "Decimal Places". Once ticked, Artisan displays one decimal in various places incl. the LCDs.
