### ISSUE TITLE
libglib bundled in the rpm package prevents artisan to start

### ISSUE THREAD

**Issue by marcov** [artisan-roaster-scope/artisan#305]
Hi, I installed artisan on openSUSE x64 using the rpm package from [here](https://github.com/MAKOMO/artisan/releases/latest).

When trying to start up artisan, I get the following error (NOTE: go get this output, I had to drop `2> /dev/null` from `/usr/bin/artisan` script):
```
Gtk-Message: Failed to load module "canberra-gtk-module"
/usr/share/artisan/artisan: symbol lookup error: /usr/lib64/libgio-2.0.so.0: undefined symbol: g_canonicalize_filename
```

The first failure is non fatal and it's because `LD_LIBRARY_PATH` for gtk modules is not pointing to the right lib folder on my system.

The second failure happens because the symbol `g_canonicalize_filename` is not found. This symbol should be included by `libglib`, and the  `libglib` installed on my system has it:
```
 $ nm -D /usr/lib64/libglib-2.0.so.0 | grep g_canonicalize_filename 
000000000003d8b0 T g_canonicalize_filename
```
However, another version of `libglib` is bundled in the  artisan rpm package, and this version does not contain the symbol:
```
$ nm -D /usr/share/artisan/libglib-2.0.so.0 | grep g_canonicalize_filename
```
This `libglib` file takes precedence over system's `libglibg`, as it is placed in the same directory where the artisan directory resides:
```
$ LD_DEBUG=libs /usr/bin/artisan 2>&1 > /dev/null| grep libglib 
     32527:     find library=libglib-2.0.so.0 [0]; searching
     32527:       trying file=/usr/share/artisan/libglib-2.0.so.0
     32527:     calling init: /usr/share/artisan/libglib-2.0.so.0
```

## Specifications
  - Artisan Version: artisan-1.5.0-1.x86_64
  - Platform (Mac/Windows/Linux + OS version): Linux x64

**Comment by MAKOMO** [comment]
Done. New builds are on BinTray https://bintray.com/artisan/artisan-artifacts/artisan/master#files
