### ISSUE TITLE
Request : Autosave as JPG

### ISSUE THREAD

**Issue by samuellaw178** [artisan-roaster-scope/artisan#307]
Dear Artisan team,

First of all, thanks for your continuous great work! I would like to make a small feature request if it is not unreasonable.

**Request:** To be able to autosave roast logs as JPEG (on top of .alog) OR an additional option to simultaneously save as JPG when choosing to save as .alog (under file>save as).

**Motivation:**
Currently, the autosave function allows the roast log to be saved as .alog automatically and as .pdf if chosen. However, I prefer to save my logs as .alog and JPEG. With JPEG, I can just open the JPEG file and scroll to the next profile by clicking right keyboard arrow. This operation is not possible with either PDF or alog, where I need to close Artisan-then-double-click in order to view the next log.

**Comment by MAKOMO** [comment]
added 4c9ebbb9099795ec72fdb081192dd59ea9f7a13f
