### ISSUE TITLE
Feature request - database connection

### ISSUE THREAD

**Issue by aasssddd** [artisan-roaster-scope/artisan#308]
## Expected Behavior
add nosql database connection options might be useful for analysis roasting logs
e.g. MongoDB

## Actual Behavior
save JSON files

**Comment by InvisibleOrdinary** [comment]
I think this would actually satisfy my request for batch editing post-roast (#322).

**Comment by MAKOMO** [comment]
artisan.plus to be released next week (based on MongoDB;)
