### ISSUE TITLE
Custom button event which send certain values to other softwares

### ISSUE THREAD

**Issue by yaminhamyd** [artisan-roaster-scope/artisan#313]
Just a feature request, kind of a weird one but think it might be of use. Is it possible to have a custom button event where when pressed it sends a specific parameter's value to another program like excel.
What we normally do is we have a profile of a certain roast written in a table and we manually fill in the values of the current roast  at the predetermined times - so that we can compare it against the profile etc. This sheet contains other information of the batch as well. 
Anyway I thought it would be nice to have a button on artisian so that when pressed it'll send the Bean temperature value to excel and goes on filling the table. I know exporting a CSV file and importing it into excel  is an option, but for us it has to be a real time thing where we could just send the values. 
Any way of doing it, work around, tips and tricks would be greatly appreciated. 
Thanks

**Comment by MAKOMO** [comment]
Supporting the sending of data to other applications cross-platform is all but simple and sounds as a very specific request. This goes way beyond what Artisan is about to provide. Note that Artisan has all the means to compare the current roast with a previous profile by loading it into the background.

Artisan is open source. If you need such a feature, just hire a software developer that adds it to a specific build for you. Remember that by the GPL licence you need to also publish all those modifications and extensions than as Open Source as well.
