### ISSUE TITLE
Show Artisan batch # before / during roasting

### ISSUE THREAD

**Issue by InvisibleOrdinary** [artisan-roaster-scope/artisan#318]
This might be a feature request, it might be that I'm missing how to do this, but - assuming you have auto batch turned on - is there a way to show the batch number that before or at least during roasting that batch? 

I need to record batches for a client (food safety) and it would ease my workflow to be able to record it while or before I set up the days roasts… 

## Specifications

  - Artisan Version: 1.6.0 
  - Artisan Build (number in brackets shown in the about box): (435ba27)
  - Platform (Mac/Windows/Linux + OS version): Mac OS
  - Connected devices or roasting machine: Proaster, Phidgets 1048 (and others on a Pinhalense sample roaster)
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
The batch number will be shown in the title from the next version on

**Comment by InvisibleOrdinary** [comment]
thank you!
