### ISSUE TITLE
ability to edit saved roast properties

### ISSUE THREAD

**Issue by InvisibleOrdinary** [artisan-roaster-scope/artisan#320]
## Expected Behavior

have the ability to edit or delete the list of coffees in the roast properties dialogue - this would be either changing the batch size, name or whatever… and the either saving over that coffee profile, or saving as a new profile

:: and :: this is maybe a separate issue, but is it by design that we cannot add a coffee to the list when recording?

## Actual Behavior

unable to change the list - or I just don't see where this is possible

## Steps to Reproduce the Problem

  1. 
  2. 
  3. 

## Specifications

  - Artisan Version: 1.6.0 (435ba27) 
  - Artisan Build (number in brackets shown in the about box):
  - Platform (Mac/Windows/Linux + OS version): Mac OS 10.14.3
  - Connected devices or roasting machine: either phidgets 1048 or VINT
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

[190227_artisan-settings.aset.zip](https://github.com/artisan-roaster-scope/artisan/files/2912045/190227_artisan-settings.aset.zip)

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
Recently a "-" button has been added next to this "+" button, which allows to delete the current selected item (then one with same title and weight-in). You might want to test a new v1.6 beta build.
