### ISSUE TITLE
Decaf tagging in roast properties

### ISSUE THREAD

**Issue by goatShaver** [artisan-roaster-scope/artisan#323]
I realize this will make many people cringe, but I drink too many espressos a day to have caffeine. I purchased Hottop so that I could have fresh decaf because it isn't readily available to me elsewhere. It would be great to have a means to log beans as decaf and then the type of decaf processing. 

I modified v1.5 to  have this support. It took me about 2 hours (I struggled to understand pieces of the code.) Reality is, it should have taken me about 30 minutes or less as it was rather straight forward. 

I believe the real value is once people start sharing roast profiles. Having a binary option as to decaf or not will be valuable because it roasts so differently. 

## Expected Behavior
Correctly record/log decaf or not and type of decaf processing.

## Actual Behavior
No simple steps for tagging coffee as decaf except in title, however it would be nice to save this as true/false option along with some predefined types so that filtering and processing of shared profiles can be performed.

**Comment by MAKOMO** [comment]
I reject this for now. Sorry. Please use the beans field to describe your green beans in all detail. Note that you would also want a mean to distinct different processing like natural, wet, honey processed beans, extra fermented beans, beans dried differently, or even grown differently. Artisan is not trying to characterize your green beans beyond this text field. An external solution is upcoming that allows to track green beans in quite some detail. I prefer not to overload this roast software even more with such details.
