### ISSUE TITLE
Unable to connect MET with Phidget 1048_0

### ISSUE THREAD

**Issue by DJS1582** [artisan-roaster-scope/artisan#324]
## Expected Behavior
Being able to connect MET probe with new Phidget 1048_0 (Phidgets 1048 4xTC 01).

## Actual Behavior
You're able to set up ET and BT, but unable to set up MET. If you try, you get readings of 700 degrees F when ET and BT are at 75.

## Steps to Reproduce the Problem

  1.  Click on Config then Device
  2. Click on Tab 'Extra Device' to set up MET
  3. Options are Phidget 1048 4xTC 01, 23, and AT. 01 and 23 dont work and AT doesn't give actual MET.

## Specifications

  - Artisan Version: 1.5.0
  - Artisan Build (number in brackets shown in the about box): fc6ebda9
  - Platform (Mac/Windows/Linux + OS version):Windows 10
  - Connected devices or roasting machine: Phidget 1048_0 and Huky 500t
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
The Phidget 1048 works as expected with all versions of Artisan. Configure your main device using the meter popup to select "Phidgets 1048 4xTC 01" in the first tab "ET/BT of the Device Assignment dialog (menu Config >> Devices).  In the second tab of the same dialog add one extra device and select "Phidget 1048 4xTC 23" to read in the channels 2+3 of the 1048. I assume you connected your MET probe to either channel 2 or 3. The device type "Phidget 1048 4xTC AT" is to read the additional ambient temperature sensor of the 1048. Please consult in the future the documentation or use a public forum for configuration questions. This tracker is to track software issues only. Thanks.
