### ISSUE TITLE
Artisan discards profile when not asked to do so

### ISSUE THREAD

**Issue by peppersass** [artisan-roaster-scope/artisan#329]
## Expected Behavior
Artisan should never discard the profile unless explicitly requested and confirmed by the user.

## Actual Behavior
After a roast, hitting the OFF button displays the green ON and START buttons. If the ON button is hit, Artisan displays a dialog offering to save or discard the profile, or to cancel the command. If Cancel is selected, Artisan returns to the previous state, as it should, If Save is selected, Artisan opens a file save dialog. If the user hits Cancel in that dialog, Artisan closes the file save dialog and re-displays the dialog asking whether the user wishes to Save, Discard or Cancel. If Cancel is selected in that dialog, the profile disappears! If START Is then selected, the previous profile is lost forever. I lost several profiles before I discovered that hitting OFF before START would return to the previous profile (I think - that's what it does when I do a test without the roaster connected.) If course, recovery of the profile shouldn't depend on the user discovering this hidden behavior. Instead, the Cancel command in the second dialog (and all subsequent displays of that dialog while the profile is still loaded) should return Artisan to the previous state, just like it does the first time the dialog is displayed, and the previous profile should be displayed.

Further, whenever the user selects Discard, Artisan should ask, "Are you sure?". In other words, Artisan should never discard the profile unless explicitly asked to do so, with confirmation.

## Steps to Reproduce the Problem

  1. Hit ON
  2. Hit START
  3. Hit a few event buttons, like Charge, Dry End, FC Start, Drop, etc. to create a small test profile.
  4, Hit OFF
  5. Hit ON
  6. Select Save
  7, Hit Cancel in save dialog
  8, Hit Cancel in Artisan Save, Discard, Cancel Dialog (profile disappears)
  9. Hit START (profile is lost)
 10, -or- Hit OFF (profile is re-displayed)

## Specifications

  - Artisan Version: 1.5
  - Artisan Build (number in brackets shown in the about box):
  - Platform (Mac/Windows/Linux + OS version): fc6ebda9
  - Connected devices or roasting machine: Quest M3 with Arduino TC/4, but can be driven without roaster connected.

[artisan-settings.txt](https://github.com/artisan-roaster-scope/artisan/files/2949872/artisan-settings.txt)
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
Thanks for reporting. The last commit should resolve this critical issue just in time for the v1.6.1 release.
