### ISSUE TITLE
Feature Request - Artisan Command addition; Channel Tare

### ISSUE THREAD

**Issue by arkenamun** [artisan-roaster-scope/artisan#331]
A nice to have feature to automatically tare LCDs that I think would be simple to implement. If not simple, then existing manual tare operation is simple, effective and sufficient.
-----------------------------------------------------------------------------------------------------------

Add the possibility of being able to create a custom button using a new Artisan Command type action that sets the tare value of a channel as if a right-click of the LCD had taken place.

e.g. Artisan Command "tare(a)" : tare value of channel (a=T1...T22) 

In my use case this would allow a rule to be created to tare the channel of the extra device (Phidget IO) that has gas burner pressure . Then gas pressure can be tared automatically at the start of each roast before gas valve is opened and phidget sensor may (often) drifts from zero.

## Specifications

  - Artisan Version:1.6.1

**Comment by MAKOMO** [comment]
added in Commit 47c2478d7f30fed0f7181bbf6115ca19dc392544
