### ISSUE TITLE
Maximum Pulse Length Changed in 1.6.1, advisory; unlikely to affect user experience

### ISSUE THREAD

**Issue by arkenamun** [artisan-roaster-scope/artisan#335]
Advising noticed change in pulse operation (from previous undocumented 5000 max) that may cause in-operative event buttons and necessitate user configuration changes for work-around, e.g.by reducing n to 1000 or using set(n,x) or toggle(n) in place of pulse(n,t)

## Expected Behavior

Phidget IO digital output pulse(n,t) functions up to pulse length 5000 (5s)

## Actual Behavior

Phidget IO digital output pulse(n,t) functions up to pulse length 1000 (1s)

(it's ok, really, due to work-arounds)

## Steps to Reproduce the Problem

  1. Configure event button for pulse
  2. push button
  3. observe message bar, note "Pulse out of range (t)"

## Specifications

  - Artisan Version:1.6.1
  - Artisan Build (number in brackets shown in the about box): c23da469
  - Platform (Mac/Windows/Linux + OS version): w10
  - Connected devices or roasting machine: Phidgets 8/8/8

**Comment by MAKOMO** [comment]
This change was not intensional (and thus not documented). It got inherit from a PR together with other changes (mostly enhancements). I just increased the limit from 5s to 999999ms which should be long enough for all use cases. Sorry for the troubles and thanks for reporting.
