### ISSUE TITLE
Delta Exhaust LCD only displays when Delta Exhaust Curve is on.

### ISSUE THREAD

**Issue by cathos** [artisan-roaster-scope/artisan#343]
## Expected Behavior
Delta Exhaust LCD should be on when the setting for 'Config>Curves>ROR>Rate of Rise LCDs>Delta ET' is Checked.

## Actual Behavior
Delta Exhaust LCD only appears if the Curve is also turned on, or in roasts after the curve has been turned on, then off again, prior to restarting the program. This worked in Windows version 1.5.0, but does not consistently work in 1.6.2. Sometimes it will turn on after opening and closing the settings window, but not always.

## Steps to Reproduce the Problem

  1. Turn off Exhaust Curve
  2. Restart Program
  3. Run a Roast

## Specifications

  - Artisan Version: 1.6.2
  - Artisan Build (number in brackets shown in the about box): 9d1202a4
  - Platform (Mac/Windows/Linux + OS version): Windows 10
  - Connected devices or roasting machine: Phidgets 1048_0

  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.    [artisan-settings 2019-04-09.aset.txt](https://github.com/artisan-roaster-scope/artisan/files/3060082/artisan-settings.2019-04-09.aset.txt)
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
fixed in 191f18d12529e1d60d7c92188502cbce5e76b158
