### ISSUE TITLE
Why one gigantic main.py?

### ISSUE THREAD

**Issue by FilePhil** [artisan-roaster-scope/artisan#346]
What are the reasons for the huge main.py, containing mostly all of the code?
In my Opinion splitting the file could bring some improvements in readability and maintenance.

**Comment by rpaulo** [comment]
Historical reasons.  We've started the process of splitting up the code but due to its fragility, there is a risk for regressions which we want to avoid.  You're welcome to help with making the code more modular!  (PRs welcome 😀)
