### ISSUE TITLE
Option To Use Event Labels On Graph And Not Just Value

### ISSUE THREAD

**Issue by TLP007** [artisan-roaster-scope/artisan#347]
## Expected Behavior
Added a Burner Event button
Label: 3.5kPa
Desc: 3.5 Gas
Type: Burner
Value 135

I made the value 135 because my axes are set to 100 min to 500 max (Artisan defaults). I want to be able to see the burner changes without resizing my graph, so I made the value "135" to keep it viewable.

I would like to be able to set the value however to ensure it stays visible on the graph, but instead of showing the value on the line when using Combo, have the option of showing the marked event's label.

## Actual Behavior
The Event value is shown as opposed to the Event label.

## Steps to Reproduce the Problem

  1. Create an Event and fill in a value, etc.
  2. Turn on Combo viewing
  3. See the value rather than the label

## Specifications

  - Artisan Version: 1.6.1
  - Artisan Build (number in brackets shown in the about box): c23da46
  - Platform (Mac/Windows/Linux + OS version): Mac
  - Connected devices or roasting machine: Mill City 1kg
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
Tick "Descr." and adjust the number of characters to display.
