### ISSUE TITLE
Missing delta ET LCD on the right of the screen

### ISSUE THREAD

**Issue by rmongiovi** [artisan-roaster-scope/artisan#351]
Since I upgraded to Artisan 1.6.2 (9d1202a4) the delta ET LCD on the right side of the window has gone missing.  The Rate of Rise button is clicked on the Curves window.  If I deselect it the space between my BT LCD and delta BT LCD gets smaller, so when selected it seems to think there's something displayed there.  There's just no actual LCD box or label; just ET. BT, and delta BT.

Both Rate of Rise Curves are selected, and both display.  It's just the LCD.

**Comment by MAKOMO** [comment]
Duplicate Issue #343. This has already resolved. If you have an urgent need for this LCD check out the continuous builds https://github.com/artisan-roaster-scope/artisan/releases/tag/continuous
