### ISSUE TITLE
Artisan+ green storage $$/lb is inconsistent…

### ISSUE THREAD

**Issue by InvisibleOrdinary** [artisan-roaster-scope/artisan#368]
## Expected Behavior

(is there a separate github for the online portion of artisan+?)
Same price/weight remains same across all places it shows…

## Actual Behavior

When origionally input, the units were  kg / C ⁄ € then changes profile settings to be lb / F / $. Price per lb of green coffee after the update is showing inconsistently - actually not sure if it was consistent before changing units, however. 

In the examples below - the correct purchase price is 2.80/lb

<img width="488" alt="Screen Shot 2019-06-26 at 7 23 11 AM" src="https://user-images.githubusercontent.com/16738749/60188190-bd407800-97e3-11e9-8b4d-e0903baa9796.png">
<img width="311" alt="Screen Shot 2019-06-26 at 7 23 20 AM" src="https://user-images.githubusercontent.com/16738749/60188218-c893a380-97e3-11e9-9442-0c3bbe45e4c7.png">
<img width="336" alt="Screen Shot 2019-06-26 at 7 23 31 AM" src="https://user-images.githubusercontent.com/16738749/60188224-ccbfc100-97e3-11e9-8195-f41b68586ee3.png">

**Comment by MAKOMO** [comment]
Fixed by now. Thanks for reporting!
