### ISSUE TITLE
Artisan+ / Can't save new green in store

### ISSUE THREAD

**Issue by InvisibleOrdinary** [artisan-roaster-scope/artisan#369]
## Expected Behavior

Can save entered beans in store.

## Actual Behavior

the screen does nothing, and if I navigate away, all entries for that bean are lost, including adding a new producer… I had entered on soe time before, and had no issue with updating it's info through interfaces (sections of the site) but this won't seem to save at all

**Comment by MAKOMO** [comment]
Hm. Does this issue persist. Could you show a screen shot of this or anything that helps us to duplicate this? Thanks!

**Comment by InvisibleOrdinary** [comment]
Hmm, I tried to reproduce, but can't so maybe this was a glitch from the account issue?

**Comment by MAKOMO** [comment]
We might have fixed this in one of the recent deploys. I tried too, but couldn't duplicate this anymore. I close this for now
