### ISSUE TITLE
Roast Properties "Title" Font Color problem.

### ISSUE THREAD

**Issue by PapasCup** [artisan-roaster-scope/artisan#371]
## Steps to Reproduce the Problem

  1. Go to Config-Colors-Graph (tab)-Title and set the color to #ffffff (white)
  2. Then go to Roast-Properties-Title (field) and the title will be blank (white font against white background).
  3. 

## Specifications

  - Artisan Version:  2.0.0 
  - Artisan Build (number in brackets shown in the about box):  (a0a1face)
  - Platform (Mac/Windows/Linux + OS version): Windows 7 and Windows 10
  - Connected devices or roasting machine:  Aillio Bullet R1 (ver 1.5)
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by roasterdave** [comment]
Thanks for reporting.  Confirmed on Windows.  Investigating the other platforms.

**Comment by MAKOMO** [comment]
Fixed by 33f9979e19aac65b015027e51fe4b471aa98059c

**Comment by PapasCup** [comment]
Hi Marko, thank-you for fixing the problem.  I’m new to GitHub and this process.  Do I wait for a future release of Artisan 2.0.x or is this fix available in some sort of interim release?  If there is a web-page that I missed that answers these questions or where interim releases are help, I’d appreciate knowing it.

 

Rick
