### ISSUE TITLE
The Roast title is invisible

### ISSUE THREAD

**Issue by reizao** [artisan-roaster-scope/artisan#375]
## Expected Behavior
Roast title visible

## Actual Behavior
Roast title invisible

## Steps to Reproduce the Problem

  1. Open Roast / Properties
  2. Try to type roast title
  3. 

## Specifications

  - Artisan Version: 2.0.0
  - Artisan Build (number in brackets shown in the about box): a0a1face
  - Platform (Mac/Windows/Linux + OS version): Windows 10
  - Connected devices or roasting machine: Phidgets 1048
![white text](https://user-images.githubusercontent.com/44176203/60814884-dbf02880-a16c-11e9-905f-de03d28ed68a.jpg)

  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
This should be fixed by the current trunk. You could test by using the beta versions of the next release available here https://github.com/artisan-roaster-scope/artisan/releases/tag/continuous
