### ISSUE TITLE
Artisan Command (Button) tare(3) not functioning

### ISSUE THREAD

**Issue by arkenamun** [artisan-roaster-scope/artisan#376]
## Expected Behavior

Trying to write current LCD reading to T3 on channel3/first extra device with command tare(3)

## Actual Behavior

T3 apparently unchanged

## Steps to Reproduce the Problem

  1. Create button Artisan Command tare(3)
  2. Press button (39 in my jpeg below)
  3. Compare with right click on LCD
4. Double-check configuration vs v2.0 blog post, seems correct.

## Specifications

  - Artisan Version: v2.0.09
  - Artisan Build (number in brackets shown in the about box):a0a1face
  - Platform (Mac/Windows/Linux + OS version):W10
  - Connected devices or roasting machine:Phidgets 1018 888 for this channel
  
![30 button example](https://user-images.githubusercontent.com/22232379/60859875-ac155380-a246-11e9-8819-733b492f42fd.jpg)

![extra devices](https://user-images.githubusercontent.com/22232379/60859924-dff07900-a246-11e9-9024-df7467f6ba81.png)

**Comment by MAKOMO** [comment]
Sorry. On introducing the Artisan Command "tare" I also introduced 2 typos that prevented it to work properly. This should be fixed by Commit 9d16347dadec2397b5706e95aeeeefb954a3d6f1

**Comment by MAKOMO** [comment]
Thanks for that detailed report (again)!
