### ISSUE TITLE
cursor coordinantes pt 1

### ISSUE THREAD

**Issue by InvisibleOrdinary** [artisan-roaster-scope/artisan#377]
Am I missing where there is a what to select what values are shown in the cursor coordinates? 
Right now, it shows X (time) & Yr (F/min - the right vert axis) I would rather see the F, or be able to choose which I see. 

## Specifications

  - Artisan Version:Artisan 2.0.0 (a0a1fac)
  - Platform (Mac/Windows/Linux + OS version): Mac OS 10.14.5 (18F132)
  - Connected devices or roasting machine: 

[Buckman-10K.aset.zip](https://github.com/artisan-roaster-scope/artisan/files/3383233/Buckman-10K.aset.zip)

  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
Press key 'd' to toggle between time/temp and time/RoR axis cursor values (this shortcuts, among others, is listed under menu Help >> Keyboard Shortcuts
