### ISSUE TITLE
Autosave function saving with wrong date and time

### ISSUE THREAD

**Issue by lucapinello** [artisan-roaster-scope/artisan#378]
## Expected Behavior
I used the Autosave option you have described (see attached screenshoot). My local time is 9:51AM Jul 13 2019. 

## Actual Behavior
But the file get saved to:
1) artisan_log_19-07-10_2013.alog 
and
2) artisan_log_19-07-10_2013.pdf

So the date is wrong and the time is missing

![image](https://user-images.githubusercontent.com/1081322/61172601-85139600-a554-11e9-8807-7fe5ca932e33.png)

## Specifications
![image](https://user-images.githubusercontent.com/1081322/61172609-9a88c000-a554-11e9-9601-2fe706262604.png)
Windows 10 machine

**Comment by roasterdave** [comment]
Can you tell me the steps you took?  Was this a roast in progress or a completed roast?

**Comment by lucapinello** [comment]
Thanks for the quick reply! I tried with a new one and it worked as expected. I was fooled by the date format and assumed 2013 was the year. 
![image](https://user-images.githubusercontent.com/1081322/61175446-b6ed2280-a57d-11e9-975a-850c172377ef.png)
