### ISSUE TITLE
Artisan close Debian10

### ISSUE THREAD

**Issue by wbh16** [artisan-roaster-scope/artisan#379]
Good morning Marko, I would like to thank for the work done in artisan, I am very motivated to contribute with codes, but I need to study a little more programming. Meanwhile I am helping in other ways. At the moment I would like to report that in the recent version of Debian10 the software closes abruptly when we try to restore or save configurations.

Bom dia Marko, gostaria muito de agradecer pelos trabalhos executados no artisan, estou muito motivado a contribuir com codigos, mas preciso estudar mais um pouco programação. Enquanto isso vou ajudando de outras maneiras. No momento gostaria de relatar que na versão recente do Debian10 o software fecha abruptamente ao tentarmos restaurar ou salvar configurações.

## Specifications

  - Artisan Version: 2.0.0 e 2.0.1
  - Artisan Build (number in brackets shown in the about box):
  - Platform (Mac/Windows/Linux + OS version):
  - Connected devices or roasting machine:
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
Might be an issue of the underlying Qt libs used by Artisan on that specific platform. Nothing we can do about. Might be fixed by using future Qt libs.
