### ISSUE TITLE
midnight theme text color

### ISSUE THREAD

**Issue by InvisibleOrdinary** [artisan-roaster-scope/artisan#381]
## Expected Behavior

That title text is visible

## Actual Behavior

(cmd-t) text is too light against background to read

## Steps to Reproduce the Problem

  1. 
  2. 
  3. 

## Specifications

  - Artisan Version: 2.0 (a0a1fac) 
  - Artisan Build (number in brackets shown in the about box):
  - Platform (Mac/Windows/Linux + OS version): Mac OS 10.14.5
  - Connected devices or roasting machine:
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
Duplicate to #375. Fixed in current trunk. Check the continous builds.
