### ISSUE TITLE
Request for rate of rise / 30 seconds

### ISSUE THREAD

**Issue by grebdnul** [artisan-roaster-scope/artisan#383]
I would really like if you could change the Rate of rise (Delta BT) from being displayed as degrees/minute to degrees/30 seconds. The reason is that I come from professional roasting at a big company, and most people use ror/30sec since that is the standard in Cropster. At least here in Sweden, Norway and Denmark, as far as I'm concerned. It is just a matter of doubling the numbers, I know, but when you worked with it for several years, the think around is really big. Is there any possibility to incorporate this? For example you could have a box to choose between 60 & 30s on the Curves - Ror page.

#303

**Comment by MAKOMO** [comment]
Commit 1147514b4a174b38b3ce5516a705a846a1576fa7 adds symbolic formulas for Delta curves. You can now put "x/2" there to have the RoR values and curve displayed at C/30sec (or F/30sec). I still insist that those are not proper units and should not be used nowhere.
