### ISSUE TITLE
"DELETE roast properties on RESET" keep setting

### ISSUE THREAD

**Issue by InvisibleOrdinary** [artisan-roaster-scope/artisan#385]
## Expected Behavior

that the setting sticks when opening / closing artisan and / or custom setting files

## Actual Behavior

This is reset to 'on' (true) with each loading of a settings file regardless of where it was set before. This is also true when closing and reopening artisan.

## Steps to Reproduce the Problem

  1. 
  2. 
  3. 

## Specifications

  - Artisan Version: 2.0.0 (a0a1fac)
  - Artisan Build (number in brackets shown in the about box):
  - Platform (Mac/Windows/Linux + OS version):
  - Connected devices or roasting machine:
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by roasterdave** [comment]
Thanks for reporting.  This should be fixed in the current trunk.  You can test by using the beta versions of the next release available here https://github.com/artisan-roaster-scope/artisan/releases/tag/continuous
