### ISSUE TITLE
Temperature reading problem (installation)

### ISSUE THREAD

**Issue by roastku** [artisan-roaster-scope/artisan#387]
## Expected Behavior

Display temperature on Artisan

## Actual Behavior

No temperature reading
On Phidgets.prefPane temperature reading look okay.

## Steps to Reproduce the Problem

  1. Following installation guide.
  2. 
  3. 

## Specifications

  - Artisan Version: Artisan 2.0.0
  - Artisan Build (number in brackets shown in the about box): (a0a1fac) 
  - Platform (Mac/Windows/Linux + OS version): Mac 10.14.2
  - Connected devices or roasting machine:
Phidget 1048 (Diedrich) - USB C - MacBook Pro

  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

[artisan-settings.aset.zip](https://github.com/artisan-roaster-scope/artisan/files/3484197/artisan-settings.aset.zip)

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
Artisan requires the v22 of the Phidget driver and control panel. You need to close the Phidget Control Panel in order to allow Artisan to access the connected devices. The Phidgets driver allows access only to one app and the Phidget Control Panel counts as an app too.
