### ISSUE TITLE
Network folder are not accessible in Ubuntu

### ISSUE THREAD

**Issue by yuvalhadas** [artisan-roaster-scope/artisan#388]
## Expected Behavior
Network folders should be accessible, similar to other applications (i.e., files, writer) via the open dialog in Linux.

## Actual Behavior
With "File/Open", only local folders are accessible

## Steps to Reproduce the Problem

  1. 
  2. 
  3. 

## Specifications

  - Artisan Version: 2.0.0
  - Artisan Build (number in brackets shown in the about box): a0aa1fac
  - Platform (Mac/Windows/Linux + OS version): Uubuntu 18.04.3 LTS
  - Connected devices or roasting machine:
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
This seems to be an OS related issue we can not do anything about. Might be fixed with new Qt versions.
