### ISSUE TITLE
Artisan Not Opening

### ISSUE THREAD

**Issue by rapport123** [artisan-roaster-scope/artisan#389]
I am operating on Windows and after installation I try to open the file.  It then immediately pops up artisan.exe has stopped working.  I am not the greatest with computers and am unsure how to resolve this.

**Comment by MAKOMO** [comment]
Could you give more information on your setup and what exactly you are doing?

**Comment by rapport123** [comment]
Marko,
Thank you for the reply but we got it figured out.  It was a driver issue.  Thanks again!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by MAKOMO** [comment]
Thanks for the notice. I am closing this here.
