### ISSUE TITLE
Artisan+ enhancement request: filtering

### ISSUE THREAD

**Issue by InvisibleOrdinary** [artisan-roaster-scope/artisan#391]
Dropping this here, 

The current view order buttons are useful, but it would also be useful to be able to filter the list of beans in store to have only certain criteria visible: ie. stock >0, stock > x bags, received in last 30 days, received >90 days, by name… etc.

Similar to the Roasts section, but slightly more options.

Thanks

Dave

**Comment by MAKOMO** [comment]
[Filters have been added to the beans tab](https://doc.artisan.plus/updates/filtering-beans/) in the just released [v1.5 of artisan.plus](https://doc.artisan.plus/updates/)
