### ISSUE TITLE
Roast Summary Information Not Displaying Consistently

### ISSUE THREAD

**Issue by DennieSch** [artisan-roaster-scope/artisan#402]
## Expected Behavior
When 'Summary' is ticked for summary information to be displayed. 

## Actual Behavior
Some of my previously completed roast do not display roast summary information.
Some of my previously completed roast do display roast summary information (and therefore do not generate the error message shown below.

## Steps to Reproduce the Problem

  1. Open .alog file
  2. Tick and un-tick Summary 
  3. 

"Messages" information -- 
6 22:54:28.042 Exception: statsSummary() list index out of range@line 6578

5 22:54:25.645 Exception: statsSummary() list index out of range@line 6578

4 22:53:40.848 Exception: statsSummary() list index out of range@line 6578

3 22:53:13.467 C:/Users/Dennis/OneDrive/Coffee/Artisan/Guatemala - Huehuetenango B13477_C35_19-10-01_1408.alog loaded 

2 22:53:13.258 Exception: statsSummary() list index out of range@line 6578

1 22:53:11.913 Scope has been reset

Un-ticking and then ticking Summary causes the error message to be regenerated (see "Messages" above.

## Specifications
version = 2.0.1 (6e17cb8d)
Architecture = ('64bit', 'WindowsPE')
Machine = AMD64
Platform name = Windows-10-10.0.18362-SP0
Processor = Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
Python Branch = tags/v3.7.4
Python Build = ('tags/v3.7.4:e09359112e', 'Jul 8 2019 20:34:20')
Python Compiler = MSC v.1916 64 bit (AMD64)
Python Implementation = CPython
Python Revision = e09359112e
Python version = 3.7.4
Release = 10
System = Windows
Version = 10.0.18362
Win32 = ('10', '10.0.18362', 'SP0', '')
  - Connected devices or roasting machine:N/A
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by roasterdave** [comment]
Thanks for your report.  This is now fixed.   If you find additional issues please include a sample *.alog file.  It saves time reproducing the problem.
