### ISSUE TITLE
Cup Profile generates Unhandled Exception

### ISSUE THREAD

**Issue by DennieSch** [artisan-roaster-scope/artisan#403]
## Expected Behavior
Access cup profile features

## Actual Behavior
Unhandled Exception is generated. (See attached for error information.)

## Steps to Reproduce the Problem

  1. Start Artisan (no profile loaded)
  2. Select Roast/Cup Profile...
  3. 

## Specifications

[error details.zip](https://github.com/artisan-roaster-scope/artisan/files/3722208/error.details.zip)

 version = 2.0.1 (7806cedd)
Architecture = ('64bit', 'WindowsPE')
Machine = AMD64
Platform name = Windows-10-10.0.18362-SP0
Processor = Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
Python Branch = tags/v3.7.4
Python Build = ('tags/v3.7.4:e09359112e', 'Jul 8 2019 20:34:20')
Python Compiler = MSC v.1916 64 bit (AMD64)
Python Implementation = CPython
Python Revision = e09359112e
Python version = 3.7.4
Release = 10
System = Windows
Version = 10.0.18362
Win32 = ('10', '10.0.18362', 'SP0', '')
  - Connected devices or roasting machine: N/A
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
Thanks for reporting! The just introduced new signalling again caused issues. Fixed the typos in commit cd0a22e93e98fba2340d6d70ce654d91a2ce0e41.

New beta builds should soon be online.
