### ISSUE TITLE
Mapping of text to Summary for Roasting Notes is different than Beans

### ISSUE THREAD

**Issue by DennieSch** [artisan-roaster-scope/artisan#411]
## Expected Behavior
Same mapping logic for Roasting Notes as that used for Beans 

## Actual Behavior
- Summary appears to have two lines allocated for the Beans field versus one line for the Roasting Notes field.
- Multiple lines (up to what will fill the two lines in summary) from Beans is 'mapped' to Summary.
- Only the first line of Roasting Notes is mapped to Summary.
  (see attached)

## Steps to Reproduce the Problem

  1. Enter text in both the Beans and Roasting Notes fields
  2. Complete minimum event necessary to establish a vaild roast
  3. Enable display of Summary (Config/Statistics - Summary ticked)

## Specifications

[Summary.zip](https://github.com/artisan-roaster-scope/artisan/files/3747471/Summary.zip)

version = 2.0.1 (e7606fd4)
Architecture = ('64bit', 'WindowsPE')
Machine = AMD64
Platform name = Windows-10-10.0.18362-SP0
Processor = Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
Python Branch = tags/v3.7.4
Python Build = ('tags/v3.7.4:e09359112e', 'Jul 8 2019 20:34:20')
Python Compiler = MSC v.1916 64 bit (AMD64)
Python Implementation = CPython
Python Revision = e09359112e
Python version = 3.7.4
Release = 10
System = Windows
Version = 10.0.18362
Win32 = ('10', '10.0.18362', 'SP0', '')
  - Connected devices or roasting machine: none
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
Added a second line for roasting notes and up to two lines for cupping notes (Commit 0d322e04b6a69dacc2e1289f483475a2d539d72e)
