### ISSUE TITLE
Config|Curves|HUD (position of information in Scope window)

### ISSUE THREAD

**Issue by DennieSch** [artisan-roaster-scope/artisan#417]
## Expected Behavior
HUD information positioned on Scope window with improved readability

## Actual Behavior
HUD information is currently positioned in the lower left. Viewing this information is a bit difficult since there is all ready several things being presented in this same area --- like: graph lines, Charge temp & time, and TP temp & time.
As a suggestion; HUD information might be better presented in a 'less busy' position so it is easier to read. Like...upper left of the scope window. Maybe... provide several location choices like is provided for graph legend (Legend Location).

## Steps to Reproduce the Problem

  1. Enable display of HUD information.
  2. 
  3. 

## Specifications

version = 2.0.1 (0a9f5e1e)
Architecture = ('64bit', 'WindowsPE')
Machine = AMD64
Platform name = Windows-10-10.0.18362-SP0
Processor = Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
Python Branch = tags/v3.7.4
Python Build = ('tags/v3.7.4:e09359112e', 'Jul 8 2019 20:34:20')
Python Compiler = MSC v.1916 64 bit (AMD64)
Python Implementation = CPython
Python Revision = e09359112e
Python version = 3.7.4
Release = 10
System = Windows
Version = 10.0.18362
Win32 = ('10', '10.0.18362', 'SP0', '')

  - Connected devices or roasting machine: none
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
The HUD feature is to be removed completely in a future version and thus it will not be update. Most of it is covered by the PhasesLCDs.
