### ISSUE TITLE
ranking/web 'theme' issue

### ISSUE THREAD

**Issue by InvisibleOrdinary** [artisan-roaster-scope/artisan#426]
I am not sure if this is the right place to bring this up, or if what I am seeing is mid-stream to something else. If so, then cool.

Up until sometime within the last couple days, the ranking/web… to compare roasts. But whether this is an attempts to implement the dark mode, or something else, the current way it looks isn't working at all. The profile curves each have a white outline. Maybe so they stand out against the dark background, but it make seeing the relationship between close profile curves rather impossible. And it just makes the whole thing difficult to use at all. 

In addition, there are labels that are black on the charcoal background. These should be white or light grey so that they have enough contrast to be seen.

Perhaps this is a mid-stream state, and this will be corrected in due course. If so, great. If this is an intended change then please remedy the legibility of the curves. Finer lines so that the details isn't obscured by unnecessary extra outlines. 

## Specifications

  - Artisan Version: 2.0.1 (94daacb)
  - Artisan Build (number in brackets shown in the about box):
  - Platform (Mac/Windows/Linux + OS version): Mac 10.14.16
  - Connected devices or roasting machine: none for this
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
Thanks for reporting. Fixed via commit 9f02e3f576a8b2d266076a23cdefae0a7dfd3366.

Note that the white outlines line width can be configured via menu Config >> Curves >> UI, parameter Path Effects. Set this to 0 to turn those off. The commit above now deactivates those path effects for drawing the graph in Ranking Reports
