### ISSUE TITLE
Ranking Report, Additional Information (Beans, Roasting & Cupping Notes fields)

### ISSUE THREAD

**Issue by DennieSch** [artisan-roaster-scope/artisan#431]
## Expected Behavior
It would be very helpful if the Beans, Roasting Notes and Cupping Notes text fields (Roast|Properties) were included in the Ranking Report. This would place all the relevant information in one place/report. One can then review and compare attributes (e.g. - Roasting Notes) of previous roasts of a particular coffee (including the before and after characteristics/measurements currently provided). For example, when I prepare to roast a coffee I have previously roasted I really want to review the Beans information, Roasting Notes and measurements from previous roasts of this particular coffee in order to develop a 'roasting-plan' for the roast I'm about to perform. This would allow me to anticipated any peculiarities the coffee exhibited (and were noted) in previous roasts. It would be really helpful if this information were included...at least in the Excel version of the Ranking Report. 

## Actual Behavior
The above is not currently provided and would be an enhancement.

## Steps to Reproduce the Problem

  1. N/A
  2. 
  3. 

## Specifications

version = 2.0.1 (76fb93be)
Architecture = ('64bit', 'WindowsPE')
Machine = AMD64
Platform name = Windows-10-10.0.18362-SP0
Processor = Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
Python Branch = tags/v3.7.5
Python Build = ('tags/v3.7.5:5c02a39a0b', 'Oct 15 2019 00:11:34')
Python Compiler = MSC v.1916 64 bit (AMD64)
Python Implementation = CPython
Python Revision = 5c02a39a0b
Python version = 3.7.5
Release = 10
System = Windows
Version = 10.0.18362
Win32 = ('10', '10.0.18362', 'SP0', '')

  - Connected devices or roasting machine: N/A
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by roasterdave** [comment]
added for v2.4.4
