### ISSUE TITLE
2.0.1 Background Profile Loading

### ISSUE THREAD

**Issue by arkenamun** [artisan-roaster-scope/artisan#432]
## Expected Behavior

Load background:, accessed by h keyboard shortcut or menu.

1. only .alog files shown, .pdf files masked
2. dialogue loads background

## Actual Behavior

1. all files shown
2. background does not change, no error messages

## Steps to Reproduce the Problem

Request load background, accessed by h keyboard shortcut or menu.

## Specifications

  - Artisan Version: 2.0.1
  - Artisan Build (number in brackets shown in the about box): sorry, reverted to 2.0.0 already, downloaded 21/11/2019
  - Platform (Mac/Windows/Linux + OS version): W10
  - Connected devices or roasting machine: Custom config, Proaster sample roaster
[Proaster v3.1.0 [autoCHARGE control].aset.txt](https://github.com/artisan-roaster-scope/artisan/files/3884969/Proaster.v3.1.0.autoCHARGE.control.aset.txt)
[v2.0.1 aborted warm-up. no power. 19-11-25_1310.alog.txt](https://github.com/artisan-roaster-scope/artisan/files/3884971/v2.0.1.aborted.warm-up.no.power.19-11-25_1310.alog.txt)

  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

**Comment by MAKOMO** [comment]
Thanks for reporting. This is the intended behavior as requested by some users. This allows to select non .alog files like pdf renderings of roast profiles, those are nicely rendered as preview by the macOS finder.
