### ISSUE TITLE
Continuous Build - Win.zip file name 

### ISSUE THREAD

**Issue by DennieSch** [artisan-roaster-scope/artisan#435]
## Expected Behavior
Would expect the link-text and actual file for the (Windows) build available under 'Continuous build' to be artisan-win-2.1.1.zip

## Actual Behavior
artisan-win-2.1.0.zip (This name is the current release.)
When this file is installed 'About' shows "Artisan 2.1.1"

## Steps to Reproduce the Problem

  1. 
  2. 
  3. 

## Specifications

  - Artisan Version:
  - Artisan Build (number in brackets shown in the about box):
  - Platform (Mac/Windows/Linux + OS version):
  - Connected devices or roasting machine:
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
Thanks for reporting. Fixed!
