### ISSUE TITLE
raspberry pi phidget22 driver not updated?

### ISSUE THREAD

**Issue by samtsai5212** [artisan-roaster-scope/artisan#440]
## Expected Behavior
When I compile the phidget22 drivers, it looks like the version should be 1.5
I also add phidget driver repository by the following way
https://wbcoffee.blogspot.com/2018/03/install-phidgets22-drivers-on-raspberry.html

## Actual Behavior
It shows phidgets22 ver 1.0.0 built April 8, 2018 which seems quite dated.
![rasp_phidgets](https://user-images.githubusercontent.com/39081922/70376316-a2516280-1942-11ea-8eba-42dd40f30c95.png)

I tested it with the Hellow World example and it seems normal. The system runs well with the ver 1.0.0, too.
Just curious if the driver is not updated.

## Steps to Reproduce the Problem

  1. 
  2. 
  3. 

## Specifications

  - Artisan Version:2.1.1
  - Artisan Build (number in brackets shown in the about box):
  - Platform (Mac/Windows/Linux + OS version):
  - Connected devices or roasting machine:
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
Unclear. Did you check again after a reboot?

**Comment by MAKOMO** [comment]
stall
