### ISSUE TITLE
issue with follow background, artisan is sending wrong data to pid.

### ISSUE THREAD

**Issue by tyrtok** [artisan-roaster-scope/artisan#441]
## Expected Behavior
SV(blue line) to rise gently towards target value of 207C as per background(adsg/alog file file)

## Actual Behavior
at approx 7mins plus, the SV strangely became 207C and flat line all the way. 

any idea caused the flat line?

## Steps to Reproduce the Problem

  1.  load .alog as background, 
  2.  start and follow
 

## Specifications

  - Artisan Version: 2.0.0
  - Platform (Mac/Windows/Linux + OS version): mac
  - Connected devices or roasting machine: Fuji controller FXR
  
[buggy.zip](https://github.com/artisan-roaster-scope/artisan/files/3936023/buggy.zip)

**Comment by MAKOMO** [comment]
Unclear. The issue might be caused by the device configuration. For a lack of hardware we cannot investigate this one.
