### ISSUE TITLE
Opening file does not populate graph data

### ISSUE THREAD

**Issue by dreibergecoffee** [artisan-roaster-scope/artisan#445]
## Expected Behavior
Without Artisan open double clicking on a previous roast to open all the information would populate in Artisian.

## Actual Behavior
When you open a file nothing shows on the graph.  If you have artisan open and go to the file - open then select the file the graph is populated.

## Steps to Reproduce the Problem

  1. Double click a previous roast
  2. Artisan opens
  3. No graph data is populated

## Specifications

  - Artisan Version: 2.1.1
  - Artisan Build (number in brackets shown in the about box): 3c115a0
  - Platform (Mac/Windows/Linux + OS version): Mac 10.15.1
  - Connected devices or roasting machine: Diedrich IR-7 (Phidgets 1048)
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.
[artisan-settings.txt](https://github.com/artisan-roaster-scope/artisan/files/3963984/artisan-settings.txt)

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
Thanks for reporting! I just fixed this one in commit 79ce7907c8277604125dda264573e9d62a587c52. New beta builds of v2.1.2 should be online soon here https://github.com/artisan-roaster-scope/artisan/releases/tag/continuous for testing. We hope to release v2.1.2 as a bug-fix release later this year.
