### ISSUE TITLE
Not plotting/logging "Drop" event on graph

### ISSUE THREAD

**Issue by brendon16** [artisan-roaster-scope/artisan#446]
## Expected Behavior
Once button is clicked event should be logged/plotted onto graph

## Actual Behavior
Click button and event isn't logged/plotted. I have to turn OFF the current roast, right click at the end point on the graph and select "Drop" from the right click menu to finalize the roast and get the Summary.

## Steps to Reproduce the Problem

  1. Complete a roast
  2. Try to select the Drop button at the end of the roast
  3. Nothing happens

## Specifications

  - Artisan Version: V2.1.0
  - Artisan Build (number in brackets shown in the about box): 73534dc3
  - Platform (Mac/Windows/Linux + OS version): Windows
  - Connected devices or roasting machine: TC4
[artisan-settings 16-12-19.zip](https://github.com/artisan-roaster-scope/artisan/files/3966655/artisan-settings.16-12-19.zip)

  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
This is a known issue in v2.1 and has been fixed in v2.1.1. Thus you might want to install directly the v2.1.2 beta which will be released soon as v2.1.2 which fixes some more minor bugs reported in v2.1. Get it from here: https://github.com/artisan-roaster-scope/artisan/releases/tag/continuous
