### ISSUE TITLE
Help Menu - include link to latest downloads

### ISSUE THREAD

**Issue by stinsonddog** [artisan-roaster-scope/artisan#447]
Self explanatory -
Mentioned here on HB
https://www.home-barista.com/home-roasting/artisan-auto-charge-not-consistent-t61149-10.html#p690157

**Comment by MAKOMO** [comment]
I added a link to the homepage of Artisan that contains the link to the downloads among others. Commit 786918d6e2c04cb5774c7939cca65f367bb1186e
