### ISSUE TITLE
External sensors triggering events. 

### ISSUE THREAD

**Issue by edisuc** [artisan-roaster-scope/artisan#448]
Hi. 

I guess this is a feature request - or I'm just unable to find the right way to do it. 

For me it would be great if Artisan would automatically record events based on external sensors. Eg. I would like to put a switch on the drop lever and Artisan would automatically trigger the event DROP. For me it would be enough if Artisan would periodically call an external application and if the application returns a specific string (eg. DROP), Artisan would trigger the DROP event. 

Kind regards,
Edi

**Comment by MAKOMO** [comment]
You need to add an extra device curve to monitor your sensor (you can hide the LCD and its curve) and use and alarm rule to trigger the event you like on changes in readings of that sensor.
