### ISSUE TITLE
Feature Request: Shaded Range ROR curves

### ISSUE THREAD

**Issue by EauRougeRoasters** [artisan-roaster-scope/artisan#452]
A Shaded Range feature that provides min and max ROR temperatures in a given time period, to be overlaid on the RoR curve.

Currently the Rate of Rise Filter allows us to measure rate of rise over a certain Delta Span, then smooths that information through the Smoothing settings. The smoothness of the resulting curve is a balance between accuracy and noise, but does not fully display the range of temperatures within that Delta Span.

Adding a Shaded Range option that provides min and max RoR values within the Delta Span timeframe gives a better visual cue of how the curve is trending. Overlaying the existing RoR feature would compliment the shaded range data, giving instant visuals of the average and instantaneous probe temps.

Example of a shaded range curve: https://imgur.com/Wteh7yp

**Comment by MAKOMO** [comment]
As the values averaged to smooth the RoR have been sampled at different time points, providing a min/max over them does not make much sense. What might be more productive is to run/draw RoR curves at different smoothing / delta-span levels. This is already possible via symbolic formulas. Check the Section 3.2 Computing RoR in this post: https://artisan-roasterscope.blogspot.com/2019/11/symbolic-formulas-basics-new-variables.html
