### ISSUE TITLE
Alarm triggerred, yet condition not valid

### ISSUE THREAD

**Issue by arkenamun** [artisan-roaster-scope/artisan#454]
## Expected Behavior
Using Artisan v2.0.0 alarm rules function as expected.

## Actual Behavior
Using Artisan V2.1.2 my alarm rules relating to BT do not seem to be working correctly. Alarm 34 (see message log line 18  in section pasted  below- (N.B. has my annotations as to alarm rule contents in brackets) which fires even though BT is above 150, temp comfirmed as above 150 in roast/properties/data.

Query whether this is otherwise un-reported due to my use of a symbolic BT formula, which might be uncommon?

----------------------------------------------------------

19 10:42:51.857 Alarm 28 triggered (IF ALARM 27 +00:01 say preheating)

18 10:42:50.840 Alarm 34 triggered  (IF ALARM 27, BT below 150 burner OFF)

17 10:42:49.780 Alarm 27 triggered  (START, ET below 181 BUTTON 15 Burner ON)

16 10:42:49.049 Event # 1 recorded at BT = 162.8 Time = 00:00

15 10:42:49.048 Alarm 29 triggered  (START, ET below 181 gas 35)

14 10:42:49.048 Pressure: 1031.4hPa

13 10:42:49.048 Temperature: 18.1C

12 10:42:49.047 Humidity: 52.3%

11 10:42:49.047 Phidget IO 8/8/8 attached

10 10:42:49.047 Phidget Temperature Sensor IR attached

9 10:42:49.046 Phidget Temperature Sensor 1-input attached

8 10:42:48.633 Phidget Temperature Sensor 4-input attached

7 10:42:44.190 Scope recording...

6 10:42:43.785 Connected via MODBUS

5 10:42:43.471 Scope monitoring...

4 10:42:42.886 Scope has been reset

3 10:41:42.381 Background C:/Users/roaster/Dropbox/Stash/Roasting/Artisan Data/H - Profile/h3731_20-02-10_1033.alog loaded successfully 12:27

2 10:41:42.380 Loaded watermark image C:/Users/roaster/Dropbox/Stash/Artwork/Porsha/STASH/branding/logos/print resolution/STASH logo email tag 1.png

1 10:41:42.380 

-----------------------------------------------------------------------------

## Steps to Reproduce the Problem

  1. Install 2.1.2
  2. Start roasting, unexpected alarm event occurs
  3. Re-install v2,0,0; performs as expected

## Specifications

  - Artisan Version:   2.1.2
  - Artisan Build (number in brackets shown in the about box):   2d7c9951
  - Platform (Mac/Windows/Linux + OS version):  w10 Pro
  - Connected devices or roasting machine: Phidgets multiple devices, including symbolic BT formula. MODBUS motor and valve control. Has Garanti lump of iron.

[Alarm rule 34 issue, BT not below 150C 20-03-02_1056.pdf](https://github.com/artisan-roaster-scope/artisan/files/4305338/Alarm.rule.34.issue.BT.not.below.150C.20-03-02_1056.pdf)
[Alarm rule 34 issue, BT not below 150C 20-03-02_1056.alog.txt](https://github.com/artisan-roaster-scope/artisan/files/4305340/Alarm.rule.34.issue.BT.not.below.150C.20-03-02_1056.alog.txt)
[~~~HEROES~~~  v2.107.0  .aset.txt](https://github.com/artisan-roaster-scope/artisan/files/4305341/HEROES.v2.107.0.aset.txt)

**Comment by MAKOMO** [comment]
There was a change in interpretation of Alarm rules introduced in v2.1 not well documented between (only the line "ALARMS: adds (If Alarm) alarms triggered by temperature differences" in the detailed change log refers to this). If you have a dependent alarm rule (like your alarm 34 which depends on alarm rule 27 as defined by the 27 in the IfAlarm column of rule 34) that one will not trigger before the alarm rule that it links to triggered. Thus alarm 34 will only trigger after alarm 27 is triggered. Additionally, you set the "From" value of alarm 34 to "IfAlarm", and here comes the change in interpretation. Now also the temperatures (before only the time) is interpreted relative to the selected temperature of when the dependent alarm triggered (in your case the BT at the time alarm 27 triggered, maybe 200C in your example). Artisan now calculates the temperature difference between the current temperature (in your example about 190C) and the one at the moment the dependent alarm triggered which calculates to (190C - 200C = -10C). Now Artisan compare that value to the condition set for the alarm rule (which is "below 150" for rule 34). Now -10C is clearly below 150C and thus the rule 34 triggers.

What you might want to do, change rule 34 (and similar rules) to use absolute temperature conditions, by selecting a different "From" condition like "START". Then the "blow 150C" condition will be interpreted as in older Artisan version as absolute temperature condition.

Or you might want to keep the relative interpretation for rule 34, but change the condition say, "below -20C" with the interpretation "trigger as soon the BT falls more than 20C w.r.t. the BT at the moment rule 27 triggered.

Impressive setup!
