### ISSUE TITLE
The decimal place is one place out on LCDs. That is it shows 17degrees instead of 170deg?

### ISSUE THREAD

**Issue by krametoof** [artisan-roaster-scope/artisan#458]
## Steps to Reproduce the Problem

  1. Always there 
  2. 
  3. 

## Specifications

  - Artisan Version:
  - Artisan Build (number in brackets shown in the about box):
  - Platform (Mac/Windows/Linux + OS version):
  - Connected devices or roasting machine:
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
This report lacks all necessary information on your setup. Which Artisan version are you using, on which platform, which hardware is connected, what is your exact Artisan setup (as .aset file). Please add this information or I will have to close this issue. Thanks.

**Comment by krametoof** [comment]
Yes sure. The operating system is windows 10 connecting to a dongyi dy-1ky. Ive just installed artisan 2.1.2.

**Comment by MAKOMO** [comment]
The dongyi dy-1ky is not a supported machine. You need to ask the producer of this machine for support.

**Comment by krametoof** [comment]
Unfortunately i dont imagine any help from them. Interestingly the lcds showed correctly on the earlier version of artisan

**Comment by krametoof** [comment]
I'll ask a blog group for info. I imagine its in the settings and a simple change but i have not yet discovered it.

**Comment by krametoof** [comment]
Thanks
