### ISSUE TITLE
Add the new device.

### ISSUE THREAD

**Issue by takusroaster** [artisan-roaster-scope/artisan#464]
## Expected Behavior
To whom it may concern
Currently, the CENTER series(CENTER 300 to 309) can be select in this Artisan :2.1.2. according to device page.

I have a CENTER 521 thermometer.
But there is no CENTER 521 in list of device page.
So, I would like to add CENTER 521 here.
How can I add the device at this Artisan ?
Is it can use CENTER 521 as a thermometer device?

CENTER 521's web page↓
(http://www.centertek.com/product_d.php?lang=en&tb=1&id=383&cid=67)

## Steps to Reproduce the Problem

  1. 
  2. 
  3. 

## Specifications

  - Artisan Version:2.1.2
  - Artisan Build (2d7c9951):
  - Platform (Windows 10):
  - Connected devices or roasting machine: Fuji Royal Discovery
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
We do not have access to this device thus we cannot provide support for it ourself, but we will happily accept your Pull Request providing the require code after a successful review.
