### ISSUE TITLE
Some Advise 

### ISSUE THREAD

**Issue by reynwouda** [artisan-roaster-scope/artisan#467]
## Expected Behavior
Hi Guys more a question then a issue i need 2 things 

1. need to know how i can get the value of the event slider pushed to a external python script 
as i need it to be able to adjust my controller i have build based on that 

2. how does the device --> prog output work how do a catch the output in a out.py file 

## Specifications

  - Artisan Version: 2.1.2
  - Artisan Build (number in brackets shown in the about box): 2d7c9951
  - Platform (Mac/Windows/Linux + OS version): windows and Linux Rasbian
  - Connected devices or roasting machine: self build roaster using raspberry controller and python  
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
Please do not abuse our issue tracker for questions. Either read the code or ask your questions on a public forum like home-barist.com or the Artisan mailing list. Thanks!

on 1. : the specified script is simply called with the slider value on changes. Your script has just to read it from the sys.argv

on 2. : the specified script is called with arguments <ET>,<BT>,<ETB>,<BTB> values on each sampling
