### ISSUE TITLE
xlsx_to_artisan_help.py/writehtmlFile variables

### ISSUE THREAD

**Issue by vw2013** [artisan-roaster-scope/artisan#469]
## Expected Behavior
in function def:
def writehtmlFile(fname_in, fname_htm):
fname_in and fname_htm are used.
But actually fname_out and fname_htm are used in implementation

## Steps to Reproduce the Problem

  1. 
  2. 
  3. 

## Specifications

  - Artisan Version: latest git pull
  - Artisan Build (number in brackets shown in the about box):
  - Platform (Mac/Windows/Linux + OS version):
  - Connected devices or roasting machine:
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
Thanks for reporting! Fixed by commit 34bc267301e19694de9ae931c7dd6a651b4a1a07
