### ISSUE TITLE
Comparator should open with last compared roasts

### ISSUE THREAD

**Issue by InvisibleOrdinary** [artisan-roaster-scope/artisan#489]
## Expected Behavior
When opening the comparator (which is awesome, by the way), it should open with the last roast loaded into it. 

## Actual Behavior

It always opens with the same roasts (2 for me)

## Steps to Reproduce the Problem

open comparator
remove current comaratored roasts
add a couple other roasts
close out
quit artisan
open artisan
open cpmparator

## Specifications

  - Artisan Version: 2.4.0 (5afdae1) 
  - Artisan Build (number in brackets shown in the about box):
  - Platform (Mac/Windows/Linux + OS version): Mac 10.15.5
  - Connected devices or roasting machine: doesn't matter
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

[artisan-settings.aset.zip](https://github.com/artisan-roaster-scope/artisan/files/4867123/artisan-settings.aset.zip)

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
Well, this is a design decision. The Comparator opens with the current foreground and background profile. This is what people expect.
