### ISSUE TITLE
Curves Fonts Problem

### ISSUE THREAD

**Issue by wuyi-levard** [artisan-roaster-scope/artisan#493]
Windows：Curves text is not supported Traditional Chinese
Linux：Curves text is not supported Traditional Chinese and Simplified Chinese

Change font doesn't work
![121](https://user-images.githubusercontent.com/1681252/88369112-e609b700-cdc1-11ea-957f-a1981630dbd8.JPG)

**Comment by wuyi-ligux** [comment]
Can add open source fonts：wqy？ http://wenq.org/ https://sourceforge.net/projects/wqy/files/

**Comment by MAKOMO** [comment]
Added this font and also the open-source Adobe "Source Han Serif" font in all its language specific variants. Could you give this a quick test and report if this works as expected?

Also I wonder if you would be possible for you to update the traditional Chinese translations in artisan_zh_TW.ts along the lines you did in artisan_zh_CN.ts? Note that you can edit those .ts files using the Qt Linguist app that you  can download. The .qm files are generated automatically from the .ts files via the Artisan build scripts.

**Comment by wuyi-ligux** [comment]
OK, let me test it first. I have finished the translation file of TW, but like CN, some words need to be optimized and modified, and then I submit them together.

**Comment by wuyi-ligux** [comment]
Wonderful！All fonts can work，wen quan yi no need to distinguish between simplified and traditional Chinese！

**Comment by wuyi-levard** [comment]
> Added this font and also the open-source Adobe "Source Han Serif" font in all its language specific variants. Could you give this a quick test and report if this works as expected?
> 
> Also I wonder if you would be possible for you to update the traditional Chinese translations in artisan_zh_TW.ts along the lines you did in artisan_zh_CN.ts? Note that you can edit those .ts files using the Qt Linguist app that you can download. The .qm files are generated automatically from the .ts files via the Artisan build scripts.

Translation completed！ Pull requests: update Chinese translations(CN and TW) #494
