### ISSUE TITLE
Minor typo & easy fix: Found 337 times in 38 files

### ISSUE THREAD

**Issue by darrenaddy** [artisan-roaster-scope/artisan#497]
## Expected Behavior

Message dialog: "Now, choose a serial port"

## Actual Behavior

"Now chose a serial port"

## Steps to Reproduce the Problem

  1.  Search all files in artisan master for "chose "  (note: the space after the word is important) this will find 337 hits in 38 files, including several .qm files
  2.  Explanation: "chose" is the past tense form of the word "choose". If you are asking someone to do it NOW, you ask them to "choose". If you asked someone to choose either your right or left hand, and they selected your right hand, the proper response to them would be: "I see you chose my right hand". Also proper: "I see you have chosen my right hand."
  3. "Chosen" is also a proper English word and is used (properly) in the code. Therefore it is important to have the space after the word "chose " when Searching/Replacing for this error

## Specifications

  - Artisan Version: 2.4.0
  - Artisan Build (number in brackets shown in the about box): N/A
  - Platform (Mac/Windows/Linux + OS version): N/A
  - Connected devices or roasting machine: N/A
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.    <-- "Setings" should be "Settings". 
*********************This (second) typo is found 3 times in 2 files (ISSUE_TEMPLATE.md & main.py)********************

Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
Excellent Contribution! Thanks for reporting this. Carl was sending in a PR that I just accepted that will resolve this one for the next release.
