### ISSUE TITLE
ReQ : Delta DTK connect to artisan plsss

### ISSUE THREAD

**Issue by apichoksornta** [artisan-roaster-scope/artisan#501]
ReQ : Delta DTK connect to artisan plsss
now, I can't connect to artisan with rs485 from Delta DTK or Who have way to set up I will be thank you so much.

## Specifications

  - Artisan Version: 2.4.0
  - Platform Mac
  - Connected devices or roasting machine: Tempresta Roaster
  
Thank You!

**Comment by MAKOMO** [comment]
Which roasting machine do you try to connect?

**Comment by MAKOMO** [comment]
You could try the Nordic Delta DTK support just added to the continous builds.
I close this as it is stall.
