### ISSUE TITLE
Artisan only uses endpoints when calculating BT or ET RoR, but should use all available samples in window.

### ISSUE THREAD

**Issue by PDWest** [artisan-roaster-scope/artisan#502]
## _Desired_ Behavior
Assuming independent, noisy, data samples over a moving window, the optimal method to estimate the slope of the data is to perform a least squares fit to a straight line. 

## Actual Behavior
Artisan subtracts the most recent data sample in the window from the oldest data sample in the window and divides by the time interval.  Although unbiased, this is a high variance estimator of the slope. 

## Disclaimer
I realize that Artisan is very complicated, and that I may have missed where/how this is done differently somewhere else in the code...
 
## Results

The first figure below shows the standard RoR processing from my roaster (no beans, 0.5 second sample interval and a 30s window), the second shows a simulation replay of that data using the proposed LS processing.  

I'll try to submit a PR with the very simple change needed to do this.

![NoBeans_OriginalRoR_Method_30s](https://user-images.githubusercontent.com/8768844/92291964-03fe2780-eee9-11ea-998c-39ac72845297.png)
![NoBeans_LeastSquaresRoR_Method_30s](https://user-images.githubusercontent.com/8768844/92291972-095b7200-eee9-11ea-9885-72992c2c7c8c.png)

**Comment by MAKOMO** [comment]
added
