### ISSUE TITLE
Quick Load Background in Roast Properties Dialog

### ISSUE THREAD

**Issue by stinsonddog** [artisan-roaster-scope/artisan#507]
## Expected Behavior
Roast Properties should contain the sole place to prepare to roast a particular bean/batch.  Currently you have do multiple steps to load a background roast.  

## Actual Behavior

Once your Roast Properties is set you have to 
Close Roast Properties
Open Roast Background
Load the Roast
Close Roast Background

Shortcuts make it easier, yet for the new user and experienced user there should be only one dialog to input the info for a roast.  The current setup can be left in place for advanced use of the background function.  So basically there would be two places to load a background.  On the Roast Properties page its really "Quick Load Background". 

Hopefully more people will use backgrounds. Also using Analyzer makes it necessary to use this more often and the greater need for it.  After using Analzyer the background needs to be reloaded at times.  

It's a workflow issue.  

There is space to add the Quick Load line at the bottom of Roast Properties.  Images are from a 13" Mac.  If not the second image is a start to adjust spacing. 

  - Artisan Version: 2.4
 
<img width="770" alt="Screen Shot 2020-09-25 at 6 06 31 AM" src="https://user-images.githubusercontent.com/36549872/94272812-74043a00-fef8-11ea-80d6-9306145fbe3b.png">

Move Density and Moisture over.  Adjust where Calc goes and you pick up two lines.  
![roast propeties 2](https://user-images.githubusercontent.com/36549872/94272852-82eaec80-fef8-11ea-9050-96688bd910cd.png)

**Comment by MAKOMO** [comment]
Mine looks like this:

<img width="783" alt="Screenshot 2020-09-26 at 16 40 01" src="https://user-images.githubusercontent.com/13909011/94343239-1adef800-0017-11eb-958d-528cbbf92661.png">

Quite crowded already. Why not use the Recent Roast feature to load a background profile with one click in this dialoog and even set the batch size along?

**Comment by InvisibleOrdinary** [comment]
I second this request, even though this page is pretty crowded.
Consider that when running through a series of batches that contains more than one coffee, you often need to make this update while the batch is already started. The Recent Roast, or the saved roasts dropdown from the "title' are good (are they the same thing?) so why not be able to attach the profile to that, so when you select the batch, it also loads the correct profile. It would be automatic, and errors would really only be if it can't find the profile.
Of course you need a place to select the correct profile in the first place, but it's an important tool when roasting, so seems finding a place is worth it.

**Comment by stinsonddog** [comment]
Ok yours looks more crowded.
Your suggestion is great for many instances especially a similar bean, but often there is a need to look and find other roasts for backgrounds.  Simple example is trying something different like a light roast and dark roast to blend. 

So two suggestions
Why can't it be like Recent Roast at the bottom with a + or - to choose it so it only takes up one line?  OR
Why does Beans need 4-5 lines.  Why not just take 2 from there and seems to be plenty.

**Comment by MAKOMO** [comment]
> The Recent Roast, or the saved roasts dropdown from the "title' are good (are they the same thing?) so why not be able to attach the profile to that, so when you select the batch, it also loads the correct profile

Adding a roast to the Recent Roast list does load it in the background on selecting the generated entry. So this behavior is exactly what you are asking for, right?

**Comment by InvisibleOrdinary** [comment]
Where do you choose the background profile? When I change coffees in the middle of a session, I always also have to choose the correct background...

**Comment by stinsonddog** [comment]
@InvisibleOrdinary You choose it under Roast>Background, bottom of dialog box.  This is what I am asking for a Quick Load in the Properties dialog.  If you save a profile to Recent Roast as Marko suggested and there is a background profile, it will load that background when you choose the same bean to roast in the future.  That helps but doesn't cover all the scenarios.  For example you did an improved roast since the one you saved and you now wish to use that one.


![image](https://user-images.githubusercontent.com/36549872/94350201-d9435280-0000-11eb-8660-6716de8b2c56.png)

**Comment by InvisibleOrdinary** [comment]
Sorry, I wasn't clear in my question… yeah, that is where you load the roast - but I meant to ask, where does it get attached to the 'Recent Roast' profile in Roast Properties?  from what I see, it doesn't attach any background profile to that… so I still don't understand Marko's reply.

**Comment by MAKOMO** [comment]
` If you save a profile to Recent Roast as Marko suggested and there is a background profile, it will load that background when you choose the same bean to roast in the future.`

That is not fully correct. If you add a Recent Roast the current loaded profile (not its background) is associated with this new entry. On selecting that entry, that profile is loaded in the background. The profile is attached "internally". This is not visible in any UI, but on selecting that entry it loads that associated profile into the background.

Adding a Recent Roast entry with the name and batch size of an already existing one, just updates the existing one (incl. the profile association) instead of adding a new one covering your scenario. 

Anyhow, you can at any moment press the h key to quickly load a different background profile or press ALT-H to remove the currently loaded profile.

**Comment by stinsonddog** [comment]
I had not used Recent Roasts that way.  I think you can close this and the shortcuts are fine for now.
