### ISSUE TITLE
Running Artisan locally

### ISSUE THREAD

**Issue by joebalancio** [artisan-roaster-scope/artisan#509]
I'm new to Artisan and I was curious about running it locally, but didn't see any build instructions on how to do that. I was able to get it running on a Mac though. Thought I'd share my instructions. Maybe they will be helpful for future contributors.

Note: make sure you have `pyenv` and `pipenv` installed.

1. `git clone git@github.com:artisan-roaster-scope/artisan.git`
1. `cd artisan/src`
1. `pyenv install 3.8.5`
1. `pipenv install --python 3.8.5 -r requirements-osx.txt`
1. `pipenv run python artisan.py`

**Comment by MAKOMO** [comment]
Not an issue thus I close this. Better shared on the Artisan mailing list or a public forum.
