### ISSUE TITLE
Hottop: close door when turning on

### ISSUE THREAD

**Issue by rlabbe** [artisan-roaster-scope/artisan#512]
I've been caught by this more than once when doing several roasts in a row. I'll finish a roast and eject the beans, let the Hottop cool down, then do another cycle. The problem is at this point the door is still open if I didn't close it after ejecting the beans. So when I load the beans the beans just fall into the tray. 

My suggestion is to automatically send a close door command when the on button is pressed. Perhaps this doesn't work with somebody else's work flow, but I can't imagine what that would be. 

I believe the code change would be in main.py, def HottopControlOn(), change

    setHottop(drum_motor=True)

to

    setHottop(drum_motor=True, solenoid=False)

**Comment by MAKOMO** [comment]
Dear Roger,

> On 13. Oct 2020, at 16:41, Roger Labbe <notifications@github.com> wrote:
> 
> 
> I've been caught by this more than once when doing several roasts in a row. I'll finish a roast and eject the beans, let the Hottop cool down, then do another cycle. The problem is at this point the door is still open if I didn't close it after ejecting the beans. So when I load the beans the beans just fall into the tray.
> 
> My suggestion is to automatically send a close door command when the on button is pressed. Perhaps this doesn't work with somebody else's work flow, but I can't imagine what that would be.
> 
> I believe the code change would be in main.py, def HottopControlOn(), change
> 
> setHottop(drum_motor=True)
> 
> to
> 
> setHottop(drum_motor=True, solenoid=False)

HottopControlOn() is only called on taking control (pressing the blue Control button).

You might prefer to close the solenoid door on starting a new roast with START. Luckily Artisans is quite flexible. Just add a corresponding HOTTOP Command action to the START button: solenoid(0). See screenshot below.

M
