### ISSUE TITLE
unhandled exception when changing color pattern 

### ISSUE THREAD

**Issue by greenjay** [artisan-roaster-scope/artisan#516]
## Expected Behavior
Values other than 0 accepted by color pattern number entry widget (config>events>buttons)

## Actual Behavior
When value for color pattern is changed, an unhandled exception occurs --
  File "artisanlib/events.py", line 1933, in colorizebuttons

--------------------------------------------------------------------------------
artisanlib/events.py::colorizebuttons:1933
	                self = <artisanlib.events.EventsDlg object at 0x7f04291d0280>
[artisan-settings-error.aset.txt](https://github.com/artisan-roaster-scope/artisan/files/5399364/artisan-settings-error.aset.txt)

	             pattern = 1
	            ncolumns = 15
	            nbuttons = 34
	         initbuttons = 6
	               nrows = 2
	               extra = 13
	                step = 5
	              bcolor = ['#e60400', '#da0400', '#ce0300', '#c20300', '#b60300', '#aa0300', '#9e0300', '#920200', '#860200', '#7a0200', '#6e0200', '#620200', '#560100', '#4a0100', '#3e0100', '#e60c00', '#da0b00', '#ce0a00', '#c20a00', '#b60900', '#aa0900', '#9e0800', '#920700', '#860700', '#7a0600', '#6e0600', '#620500', '#560400', '#4a0400', '#3e0300']
	                 gap = -12
	                   i = 30
	                   f = 62
	               color = <PyQt5.QtGui.QColor object at 0x7f04291e9660>
	              tcolor = ['yellow', 'yellow', 'yellow', 'yellow', 'yellow', 'yellow', 'yellow', 'yellow', 'yellow', 'yellow', 'yellow', 'yellow', 'yellow', 'yellow', 'yellow', 'yellow', 'yellow', 'yellow', 'yellow', 'yellow', 'yellow', 'yellow', 'yellow', 'yellow', 'yellow', 'yellow', 'yellow', 'yellow', 'yellow', 'yellow', 'yellow', 'yellow', 'yellow', 'yellow']
	         visualIndex = 30

## Steps to Reproduce the Problem

  1. open config>events dialog
  2. select buttons pane
  3. change value for color pattern (either by typing a number or clicking on arrows)

## Specifications

  - Artisan Version: 2.4.2
  - Artisan Build (number in brackets shown in the about box): 22ab78d
  - Platform (Mac/Windows/Linux + OS version): Linux ubuntu
  - Connected devices or roasting machine: arduino
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Settings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by roasterdave** [comment]
Thanks for reporting!  Now fixed, you can test using the continuous build available here [https://github.com/artisan-roaster-scope/artisan/releases/tag/continuous](https://github.com/artisan-roaster-scope/artisan/releases/tag/continuous)
