### ISSUE TITLE
How to participate in the list of Artisan configurations, in the next updates?

### ISSUE THREAD

**Issue by Filipe-Medeiros** [artisan-roaster-scope/artisan#522]
I don't know if this is the right place. I'm from Brazil and I developed a circuit to integrate roasters with Artisan, I would like to integrate the configuration of our product in the list of pre-configured devices contained in Artisan. We are already serving some roaster manufacturers here in Brazil, such as Atilla, Rural Mac, Kaffe among others. Thanks.

**Comment by MAKOMO** [comment]
Dear Filipe-Medeiros,

support for commercial machines is added only in turn of a considerable contribution to the Artisan project and only if resources allow for. Please contact us via our [contact form](https://artisan-roasterscope.blogspot.com/p/contact-me.html).
