### ISSUE TITLE
The translation of abbreviations is indeterminate

### ISSUE THREAD

**Issue by wuyi-levard** [artisan-roaster-scope/artisan#529]
https://github.com/artisan-roaster-scope/artisan/blob/master/src/artisanlib/main.py
![image](https://user-images.githubusercontent.com/1681252/100719904-35a76180-33f8-11eb-8687-4cf867b6920b.png)
This translate "Label", "min".
It is suggested to change it to “minutes”
The reason is that minutes and minimum share the same abbreviation, which will cause errors when translated into other languages

**Comment by MAKOMO** [comment]
Thanks for the hint! I added a discriminator to have the translation system produce two separate entries which can also be translated separately. This escaped my eyes as by accident "min" is a valid abbreviation in English AND German for both, minutes and minimum. But those are of course totally different things and should be separated.
