### ISSUE TITLE
adjustSV(<int>) and PID SV "+/-" buttons do not seem to work with Fuji PXF PID

### ISSUE THREAD

**Issue by bigl00z3** [artisan-roaster-scope/artisan#547]
## Expected Behavior
usage of custom made button using _adjustSV(<int>)_ or with the built in PID +/-5 buttons, the SV value should change

## Actual Behavior
SV value does not change when using the above functions. However it works when using the slider or sending an SV value as _write(1,240,2400)_

## Steps to Reproduce the Problem

  1. Start Roast
  2. Changing SV value by moving the slider or using pidSV(<int>) are changing the SV value on the PXF PID
  3. Pressing on the buttons _adjustSV(<int>)_ or with the built in PID +/- do not change the SV value on the PID
  4. No text displayed in _Messages
[artisan-settings PID Fuji 3.11c.aset.txt](https://github.com/artisan-roaster-scope/artisan/files/5772656/artisan-settings.PID.Fuji.3.11c.aset.txt)
_

Note: Currently testing the PID by itself to configure (not mounted yet in the roaster). OID is connected to a thermocouple TC K and connected to Artisan by USB using a USconverter RS485 interface

## Specifications

  - Artisan Version: 2.4.4 pre release
  - Artisan Build (number in brackets shown in the about box): 8362ed6
  - Platform (Mac/Windows/Linux + OS version): Mac OS  
  - Connected devices or roasting machine: PID only
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Settings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
Fixed by Commit 481d18284f36af7fe4d63a80787330fc5abe4c1d
