### ISSUE TITLE
ENHANCEMENT - replace libusb-win32 with WinUSB for Aillio Bullet

### ISSUE THREAD

**Issue by stuartmcknight** [artisan-roaster-scope/artisan#549]
Happy New Year Marko and team!

As you know, in order for Artisan to talk to the Bullet up to now, has required the old USB driver from RoasTime 1.0 to be preloaded (libusb ?) and this is not compatible with RoasTime 2.x onwards as they changed the driver requiring the removal of libusb.

As part of the Beta testing of RoasTime 3.x I asked whether there could be a way to bring Artisan up to date and live harmoniously with RoasTime. I was advised that Aillio changed to WinUSB. Is it possible to update Artisan’s Bullet support to use this driver instead of requiring libusb ?

Thanks!

Stuart

**Comment by MAKOMO** [comment]
Dear Stuart,

> On 11. Jan 2021, at 23:24, stuartmcknight <notifications@github.com> wrote:
> 
> 
> Happy New Year Marko and team!

Thanks! Happy New Year also to all Artisan users from the Artisan team.

> 
> As you know, in order for Artisan to talk to the Bullet up to now, has required the old USB driver from RoasTime 1.0 to be preloaded (libusb ?) and this is not compatible with RoasTime 2.x onwards as they changed the driver requiring the removal of libusb.
> 
> As part of the Beta testing of RoasTime 3.x I asked whether there could be a way to bring Artisan up to date and live harmoniously with RoasTime. I was advised that Aillio changed to WinUSB. Is it possible to update Artisan’s Bullet support to use this driver instead of requiring libusb ?

As far as I know WinUSB is only supported on (newer) Windows machine via pywinusb on Python. I am not aware of any cross-platform lib for this. Anyhow, I am not a USB expert and have no hardware (neither a Windows machine nor a Bullet) to develop and test. The only hope here is that someone with more knowledge (and hardware) steps in here and will come up with a Pull Request.

Marko
