### ISSUE TITLE
artisan+ blend price calculation

### ISSUE THREAD

**Issue by scotthue** [artisan-roaster-scope/artisan#550]
First off, I'm not sure if this is the best place to submit an issue for artisan+ but I didn't see a better place.

It seems to me that artisan+ is incorrectly calculating the price for a blend. For example:

<img width="261" alt="Screen Shot 2021-01-12 at 8 34 51 PM" src="https://user-images.githubusercontent.com/3074091/104403517-e59edd00-5515-11eb-876b-258a9f3c4ce6.png">

In this blend, the first coffee (Ethiopian) is $4.81/lb and the second coffee (Brazil) is $2.09/lb. At a 50/50 ratio, that should yield a cost of $3.45/lb for the blend. But you can see in the screen shot, that's not what's displaying.

I am seeing this issue in multiple blends, not just in the example posted here.

Please let me know if I can provide any additional information.

**Comment by MAKOMO** [comment]
Dear Scott,

thanks for your report! The shown price was indeed incorrect. It was the price per kg and not per lb. After a browser reload (CTRL-SHIFT-R or CMD-SHIFT-R), the error should be fixed and the correct $3.45/lb should no be shown. 

Marko

PS: You can at anytime also write to info@artisan.plus to contact us on issues around the artisan.plus service.
