### ISSUE TITLE
Adding Siemens S7 to Roaster, to control via Artisan

### ISSUE THREAD

**Issue by Indo2021** [artisan-roaster-scope/artisan#561]
Hi there, 

I'm Roasting with a Kuban Roaster which has 3 potentiometer connected to 3 Siemens Sinamics V20 (one for Fan speed, one for drum speed and one for the Gas settings) to control the roast. The roaster is also equipped with 2 Thermocouples connected to the artisan software via a phidget 1048 for logging BT/ET.
I was wondering if i could get a siemens s7 (which is supported by artisan) to directly control the roaster via artisan. The main Issue is that i have to log the settings (Gas, Fan, Drum) manually and I would be nice to set up a couple buttons/events to have it a little more automated.
Unfortunately this is new territory for me and I don't know too much about automation

## Specifications

  - Artisan Version: Artisan 2.4.2
  - Artisan Build 3
  - Platform Mac OS 10.13.6 version):
  - Connected devices or roasting machine: Kuban Supreme (without PLC)

**Comment by MAKOMO** [comment]
Dear Indo2021, what you report here sounds to me like a considerable development project that requires an extensive experience in automation technology (hard- and software). It might be way cheaper to just buy a machine that has all of this already build in. Anyhow, as this tracker is to report issues on Artisan and not a forum to report on user projects I will close this one. Please discuss related items on public roasting forums like home-roaster.org.
