### ISSUE TITLE
Enhancement Config section export/import Buttons Sliders

### ISSUE THREAD

**Issue by davparker** [artisan-roaster-scope/artisan#563]
I'm a member of a large Facebook Group dedicated to the Fresh Roast models of coffee roasters. Their newer roasters have 9 settings for Fan and 9 for Power (Heat). So basically we've created a guide to define all those buttons, their colors and associated event marker colors and even sliders. The group is getting new users almost daily, It seems like a large percentage of the user base prefer Artisan especially now that Buttons and Sliders can be defined  for Fan and Power settings. To ease their adoption, we had created a vanilla default aset config they could import to define all the Buttons, Sliders Markers etc but this is problematic as importing a predefined config overwrites any other values already set. So now we refer then to a step by step PDF to define this. We were trying to figure out a method where certain sections of the config could be imported with overwriting the entire config. Like only importing the [ExtraEventButtons] section and/or [Sliders] section. And (I believe) even a single variable from the [events] section EvalueColor to match marker colors with Buttons/Sliders.  I think this could prove highly useful and speed adoption to using Artisan software.

**Comment by FilePhil** [comment]
To create a stripped down version of a settings file you need to have the as minimum this:
```
[General]
Mode=
```
Artsian is probing if the File contains this Mode Tag.
```python
# a proper artisan-settings.aset file needs at least to contain a Mode tag
if not (theme or machine) and not settings.contains("Mode"):
    aw.qmc.adderror(QApplication.translate("Error Message","Exception: {} not a valid settings file",None).format(str(filename)))
    return False
```
Then you can add the settings you want to change, anything you not include will not be changed.


It is also possible to save and restore only the Buttons and Sliders by using the Load and Save functions of the Button Palettes.
This can be done quite easy. Other Event Settings like the Config and Quantifiers are not saved by this method.
1. Go to the Events Dialog (Config -> Events)
2. Create Your Buttons and Sliders
3. Goto the Tab "Palettes"
4. Store the Palette by select a Number and Click  "<< Store Palette"
![image](https://user-images.githubusercontent.com/16101101/107382380-14e24300-6af0-11eb-829f-94e09c8a09bc.png)
5. Click on Save and choose a filename
![image](https://user-images.githubusercontent.com/16101101/107381770-79e96900-6aef-11eb-9ba8-2020299ebcf8.png)

To Import the Buttons and Silders do the reverse.
1. Click "Load" and select your file
2. Select the Number you stored the palette and click ">>Activate Palette"

Now the Buttons and Sliders should be loaded.
