### ISSUE TITLE
I'm Brazilian as I do to acquire artisan pro.

### ISSUE THREAD

**Issue by fmpc** [artisan-roaster-scope/artisan#569]
## Steps to Reproduce the Problem

  1. 
  2. 
  3. 

## Specifications

  - Artisan Version:
  - Artisan Build (number in brackets shown in the about box):
  - Platform (Mac/Windows/Linux + OS version):
  - Connected devices or roasting machine:
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Settings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
If you do not provide a minimal amount of information on your setup, what you are doing and what exactly happens we cannot track this down and will close this.

**Comment by MAKOMO** [comment]
Upps. Sorry. Please ignore my previous comment. I typed into the wrong window.

**Comment by MAKOMO** [comment]
You just make an account on the platform at https://artisan.plus/en/ by clicking "CADASTRO" (REGISTER) and buy the "free" 3-month trial period from our shop:  https://shop.artisan.plus/en/professional-roasters/artisan.plus-professional-3-months-free
