### ISSUE TITLE
there is problem connect between Loring and Artisan

### ISSUE THREAD

**Issue by sehoonjoo** [artisan-roaster-scope/artisan#574]
## Expected Behavior
how could i connect between Loring and Artisan?

## Actual Behavior 
i put the right ip address. and subnet.
but there is no working.
[artisan-settings.zip](https://github.com/artisan-roaster-scope/artisan/files/5962641/artisan-settings.zip)

## Steps to Reproduce the Problem

  1. 
  2. 
  3. 

## Specifications

  - Artisan Version: 2.4.4.
  - Artisan Build (number in brackets shown in the about box):
  - Platform (Mac/Windows/Linux + OS version): windows 10 64bit
  - Connected devices or roasting machine: Loring S7
  
Please attach your current Artisan settings file (as exported via 
menu Help >> Save Settings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
You need to put your computer on a local network in the IP range of the roaster. See the note here: https://artisan-scope.org/machines/loring/
