### ISSUE TITLE
Transposer: No entries accepted in Target row cells

### ISSUE THREAD

**Issue by mtwenzel** [artisan-roaster-scope/artisan#575]
## Expected Behavior
Selecting a table cell in Transposer (Target rows) should allow input of target times/temperatures.

## Actual Behavior
The cell is highlighted, active, and the cursor is blinking in it, but no numbers can be entered.

## Steps to Reproduce the Problem

  1. Open Artisan
  2. Load a profile
  3. Open Transposer
  4. Select table cell in one of the Target rows
  5. Try entering any characters

## Specifications

  - Artisan Version: 2.4.4
  - Artisan Build (number in brackets shown in the about box):
  - Platform (Mac/Windows/Linux + OS version): Mac OSX, Win 10
  - Connected devices or roasting machine: n/a

Profiles or settings upon request; I don't think they are the root cause of the problem.

**Comment by roasterdave** [comment]
Thanks for reporting.  This has already been fixed.  You can download a continuous build with the fix from here:  https://github.com/artisan-roaster-scope/artisan/releases/tag/continuous
