### ISSUE TITLE
Pre roast, inter roast and closing down protocols

### ISSUE THREAD

**Issue by reizao** [artisan-roaster-scope/artisan#587]
This is a feature request. 

Can have a pre roast protocol to warm up the roaster before start the production?

Can have a protocol between roasts?

can have a shutting down protocol?

**Comment by MAKOMO** [comment]
This is not enough?

https://artisan-roasterscope.blogspot.com/2020/12/supporting-between-batch-protocols.html

What is missing exactly?

**Comment by reizao** [comment]
Will I try it, and come back to send comments.

**Comment by MAKOMO** [comment]
Stall
