### ISSUE TITLE
Missing artisan commands in documentation

### ISSUE THREAD

**Issue by stefunkk** [artisan-roaster-scope/artisan#595]
## Expected Behavior
List possible "Artisan commands"

## Actual Behavior
Can't find "Artisan commands"

## Steps to Reproduce the Problem

  1.  Go to documentation page
  2. Go to events
  3.  There is just mentioned that there is a list of artisan commands, but i can't find any.

## Specifications

  - Artisan Version: 2
  - Artisan Build (number in brackets shown in the about box): 666
  - Platform (Mac/Windows/Linux + OS version): windows
  - Connected devices or roasting machine: max6675, esp8266
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Settings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.
[result.txt](https://github.com/artisan-roaster-scope/artisan/files/6244494/result.txt)

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._
[result.txt](https://github.com/artisan-roaster-scope/artisan/files/6244485/result.txt)

**Comment by MAKOMO** [comment]
Would be good to leave a note on the solution here instead of just closing this. The full documentation of Artisan commands is available by pressing the Help button in the custom event buttons and slider tabs (menu Config >> Events, tab Buttons and Sliders).
