### ISSUE TITLE
Modbus Ascii configuration

### ISSUE THREAD

**Issue by oscarquiroz94** [artisan-roaster-scope/artisan#604]
Dear.

I'm trying to configure Artisan to connect a roaster using Modbus over serial port (ascii).

But I can't read the temperature values properly.
The roaster uses the following configuration on the Modbus series:

**Baud rate:** 38400
**Function:** 3
**Storage format temperatures:** decimal with 2 digits (16 bits)
**Slave id:** 1
**Register1:** 100
**Register2:** 101

My configuration in Artisan is:
![CapturaSettingArtisan](https://user-images.githubusercontent.com/70978150/115932589-d99ab380-a452-11eb-83b9-be17b4fb1518.PNG)

I'm doing a test with temperatures 180.74°C and 236.59°C for example, and I get the following:
![CapturaTest](https://user-images.githubusercontent.com/70978150/115932734-2088a900-a453-11eb-964f-2d9ad6e5234e.PNG)

I can see the temperatures values in the serial log (RX: 18074 and RX:23659) but in the LCD temperatures ET and BT are differents.

**Comment by fcebreros** [comment]
HI,
I think you should have the
*Decode* option on *Int*
and the
*Divider* on *1/100*

Best
FC

**Comment by oscarquiroz94** [comment]
Hi.

The only option in Decode is IntFloat, of course I'll put 1/100 in the divider. 

![CapturaIntFloat](https://user-images.githubusercontent.com/70978150/115940879-c266c080-a468-11eb-81f6-ac3ebbbaa9c1.PNG)

I´ll try it on Monday and I'll tell you about it.
Regards

**Comment by MAKOMO** [comment]
On older version the empty Decode entry assumed regular integer register access. Select the first, empty entry. Better: update to the current version which is v2.4.4.

M

**Comment by oscarquiroz94** [comment]
Hi.

I downloaded the new version of Artisan, this is the configuration that works for me:
![CapturaWorks](https://user-images.githubusercontent.com/70978150/116078812-adeb1980-a65c-11eb-8830-01334db3713f.PNG)
![CapturaWorks2](https://user-images.githubusercontent.com/70978150/116078818-b0e60a00-a65c-11eb-88b2-db2c01ceee81.PNG)

Thank you.

**Comment by MAKOMO** [comment]
Not an issue in the Artisan software. Invalid.
