### ISSUE TITLE
Unhandled exception: Quantifiers dialog box

### ISSUE THREAD

**Issue by bravowren** [artisan-roaster-scope/artisan#607]
## Expected Behavior
In Config>Events>Quantifiers: After making changes, when clicking the "Apply" button , changes are saved.

## Actual Behavior

"Unhandled Exception" error box pops up.

## Steps to Reproduce the Problem

  1. In config>events>quantifiers check a box.
  2. Click "Apply"
  
This problem is not 100% repeatable, but can be reliably triggered by checking/unchecking boxes a few times, while saving changes in between. 

Note: clicking "OK" instead of "Apply" in this dialog box saves changes, and does not trigger any errors.

## Specifications

  - Artisan Version: 2.4.4
  - Artisan Build 97e6dec
  - Platform (Mac/Windows/Linux + OS version): Mac 10.15.7
  - Connected devices or roasting machine: Phidgets VINT Hub, OUT1100, TMP1100, Cormorant CR600
  
[20210505_artisan-settings.txt](https://github.com/artisan-roaster-scope/artisan/files/6429751/20210505_artisan-settings.txt)
[elog.txt](https://github.com/artisan-roaster-scope/artisan/files/6429752/elog.txt)

**Comment by MAKOMO** [comment]
Thanks for your detailed report. This one is fixed now and goes back to a fundamental change in structure in v2.4.4 which was not applied correctly to the "ApplyQuantifier" action. Note that this "Apply" button in the events tab under Quantifier is to retrospect apply the specified quantifiers to the recorded data and not to establish the quantifier settings.
