### ISSUE TITLE
cannot convert float NaN to integer

### ISSUE THREAD

**Issue by renatocipriani** [artisan-roaster-scope/artisan#610]
## Steps to Reproduce the Problem

  1. Open Figure options
  2. Select logit scale for both axis Y and X
  3. Apply and see the error

## Specifications

  - Artisan Version: 2.4.4
[Catarina_Artisan.speciatto_21.03.15 - Copia.aset.txt](https://github.com/artisan-roaster-scope/artisan/files/6459631/Catarina_Artisan.speciatto_21.03.15.-.Copia.aset.txt)

  - Artisan Build (number in brackets shown in the about box):
  - Platform (Mac/Windows/Linux + OS version):
  - Connected devices or roasting machine:
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Settings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

Error message found on menu Help >> error

version = 2.4.4

1 10:28:25.681 Error: File "matplotlib\backends\qt_editor\_formlayout.py", line 481, in apply File "matplotlib\backends\qt_editor\figureoptions.py", line 250, in apply_callback File "matplotlib\backends\backend_agg.py", line 407, in draw File "matplotlib\artist.py", line 41, in draw_wrapper File "matplotlib\figure.py", line 1863, in draw File "matplotlib\image.py", line 131, in _draw_list_compositing_images File "matplotlib\artist.py", line 41, in draw_wrapper File "matplotlib\cbook\deprecation.py", line 411, in wrapper File "matplotlib\axes\_base.py", line 2747, in draw File "matplotlib\image.py", line 131, in _draw_list_compositing_images File "matplotlib\artist.py", line 41, in draw_wrapper File "matplotlib\axis.py", line 1164, in draw File "matplotlib\axis.py", line 1021, in _update_ticks File "matplotlib\axis.py", line 1283, in get_majorticklocs File "matplotlib\ticker.py", line 2276, in __call__ File "matplotlib\ticker.py", line 2798, in tick_values -------------------------------------------------------------------------------- matplotlib\backends\qt_editor\_formlayout.py::apply:481 self = matplotlib\backends\qt_editor\figureoptions.py::apply_callback:250 data = [] orig_xlim = (1e-07, 0.9999999) orig_ylim = (0.0, 280.0) general = ['', 50.0, 668.95232465, '04/05/2021, 18:07', 'logit', 0.0, 280.0, 'C', 'logit', False] curves = [['BT', '-', 'default', 1.5, '#ff0000ff', '', 6.0, '#ff0000ff', '#ff0000ff'], ['BTprojection', '--', 'default', 8.0, '#ff00004c', '', 6.0, '#ff00004c', '#ff00004c'], ['FundoBT', '-', 'default', 2.0, '#00007f4c', '', 6.0, '#00007f4c', '#00007f4c'], ['FundoDeltaBT', '-', 'default', 1.5, '#0000ff4c', '', 6.0, '#0000ff4c', '#0000ff4c'], ['FundoET', '-', 'default', 2.0, '#ff00004c', '', 6.0, '#ff00004c', '#ff00004c'], ['Δ\u2009BT', '-', 'default', 1.0, '#0000ffff', '', 6.0, '#0000ffff', '#0000ffff']] mappables = [] title = xmin = 50.0 xmax = 668.95232465 xlabel = 04/05/2021, 18:07 xscale = logit ymin = 0.0 ymax = 280.0 ylabel = C yscale = logit generate_legend = False index = 5 curve = ['Δ\u2009BT', '-', 'default', 1.0, '#0000ffff', '', 6.0, '#0000ffff', '#0000ffff'] line = Line2D(Δ BT) label = Δ BT linestyle = - drawstyle = default linewidth = 1.0 color = #0000ffff marker = markersize = 6.0 markerfacecolor = #0000ffff markeredgecolor = #0000ffff rgba = (0.0, 0.0, 1.0, 1.0) figure = Figure(1281x601) axes = AxesSubplot(0.0444694,0.0628391;0.914395x0.88558) curvelabels = ['BT', 'BTprojection', 'FundoBT', 'FundoDeltaBT', 'FundoET', 'Δ\u2009BT'] has_curve = True has_sm = False linedict = {'FundoET': , 'FundoBT': , 'FundoDeltaBT': , 'Δ\u2009BT': , 'BT': , 'BTprojection': } mappabledict = {} mappablelabels = [] xconverter = None xunits = None yconverter = None yunits = None matplotlib\backends\backend_agg.py::draw:410 self = __class__ = matplotlib\artist.py::draw_wrapper:46 artist = Figure(1281x601) renderer = args = () kwargs = {} draw = matplotlib\figure.py::draw:1868 self = Figure(1281x601) renderer = artists = [, , Text(0.9588646023072251, 1, '\nTorrascópio')] ax = AxesSubplot(0.0444694,0.0628391;0.914395x0.88558) locator = None child = Rectangle(xy=(0, 0), width=1, height=1, angle=0) matplotlib\image.py::_draw_list_compositing_images:131 artists = [, , Text(0.9588646023072251, 1, '\nTorrascópio')] suppress_composite = None has_images = False not_composite = True a = AxesSubplot(0.0444694,0.0628391;0.914395x0.88558) parent = Figure(1281x601) renderer = matplotlib\artist.py::draw_wrapper:46 artist = AxesSubplot(0.0444694,0.0628391;0.914395x0.88558) renderer = args = () kwargs = {} draw = matplotlib\cbook\deprecation.py::wrapper:411 inner_args = (, ) inner_kwargs = {} arguments = OrderedDict([('self', ), ('renderer', )]) addendum = None func = is_varargs = False is_varkwargs = False kwargs = {'alternative': 'Axes.redraw_in_frame()'} kwargs_name = None name = inframe signature = (self, renderer=None, inframe=) since = 3.3 matplotlib\axes\_base.py::draw:2747 renderer = inframe = False locator = None artists = [, , , , , , , , , , , , , , , , , , , Text(63.948316950000006, 150.26108688590705, '132.3'), Text(63.948316950000006, 114.26108688590705, 'CARREGAR'), Text(144.94910455000002, 105.92179407017161, '87.9'), Text(144.94910455000002, 69.92179407017161, 'TP 1:21'), Text(333.95165765, 169.9926136823962, '152.0'), Text(333.95165765, 133.9926136823962, 'SECA 4:30'), Text(565.9508803, 230.21631546294958, '212.2'), Text(565.9508803, 194.21631546294958, 'RETIRAR 8:22'), Text(68.95232465000117, 156.9, '133.9'), Text(68.95232465000117, 110.9, 'CARREGAR'), Text(136.95189089999985, 113.5, '90.5'), Text(136.95189089999985, 67.5, 'PV 1:08'), Text(324.94918305000095, 175.1, '152.1'), Text(324.94918305000095, 129.1, 'SECA 4:16'), Text(565.9508802999989, 236.38905982663394, '213.4'), Text(565.9508802999989, 190.38905982663394, 'RETIRAR 8:17'), Text(0.5, 1.0331934398593978, ''), Text(0, 1.0331934398593978, 'Torrascópio'), Text(1.0, 1.0331934398593978, ''), ] artists_rasterized = [] rasterization_zorder = None self = AxesSubplot(0.0444694,0.0628391;0.914395x0.88558) matplotlib\image.py::_draw_list_compositing_images:131 artists = [, , , , , , , , , , , , , , , , , , , Text(63.948316950000006, 150.26108688590705, '132.3'), Text(63.948316950000006, 114.26108688590705, 'CARREGAR'), Text(144.94910455000002, 105.92179407017161, '87.9'), Text(144.94910455000002, 69.92179407017161, 'TP 1:21'), Text(333.95165765, 169.9926136823962, '152.0'), Text(333.95165765, 133.9926136823962, 'SECA 4:30'), Text(565.9508803, 230.21631546294958, '212.2'), Text(565.9508803, 194.21631546294958, 'RETIRAR 8:22'), Text(68.95232465000117, 156.9, '133.9'), Text(68.95232465000117, 110.9, 'CARREGAR'), Text(136.95189089999985, 113.5, '90.5'), Text(136.95189089999985, 67.5, 'PV 1:08'), Text(324.94918305000095, 175.1, '152.1'), Text(324.94918305000095, 129.1, 'SECA 4:16'), Text(565.9508802999989, 236.38905982663394, '213.4'), Text(565.9508802999989, 190.38905982663394, 'RETIRAR 8:17'), Text(0.5, 1.0331934398593978, ''), Text(0, 1.0331934398593978, 'Torrascópio'), Text(1.0, 1.0331934398593978, ''), ] suppress_composite = None has_images = False not_composite = True a = YAxis(56.96527777777778,37.76631944444442) parent = AxesSubplot(0.0444694,0.0628391;0.914395x0.88558) renderer = matplotlib\artist.py::draw_wrapper:46 artist = YAxis(56.96527777777778,37.76631944444442) renderer = args = () kwargs = {} draw = matplotlib\axis.py::draw:1164 self = YAxis(56.96527777777778,37.76631944444442) renderer = args = () kwargs = {} matplotlib\axis.py::_update_ticks:1021 self = YAxis(56.96527777777778,37.76631944444442) matplotlib\axis.py::get_majorticklocs:1283 self = YAxis(56.96527777777778,37.76631944444442) matplotlib\ticker.py::__call__:2276 self = vmin = -70.0 vmax = 71.0 matplotlib\ticker.py::tick_values:2798 self = vmin = 71.0 vmax = -70.0 nbins = 15 ideal_ticks = .ideal_ticks at 0x000001C1CEC62430>

**Comment by MAKOMO** [comment]
The figure options dialog was reworked for v2.4.6 and the possibility to edit axis settings were removed for now.
