### ISSUE TITLE
Feature Request: Add Between Batch Protocol (BBP) in the Background Profile

### ISSUE THREAD

**Issue by Nicodmk** [artisan-roaster-scope/artisan#616]
Usually background profile can be load on start only, based on artisan blog's "Supporting Between Batch Protocols", now the all the profile have bbp record (because of the auto start/keep on mode). Can you make the background profile have the option to align since "start mode" on ?

**Comment by fcebreros** [comment]
Hi,
not sure what you mean but on the right bottom corner you select how
the background profile gets aligned.
[image: image.png]

**Comment by Nicodmk** [comment]
Sorry If I make you confused, It can be aligned from "charge to All", there is no option from "on" or "start". Thanks for responding

**Comment by MAKOMO** [comment]
We change the alignment of a new recording to a loaded background to start at begin of background profile instead of its CHARGE mark in the next version. Thanks for the hint.
