### ISSUE TITLE
Improvement Request: 3 decimal KI parameter for software PID

### ISSUE THREAD

**Issue by wogaut** [artisan-roaster-scope/artisan#618]
Currently, the Artisan SW PID uses 2 decimal places for KP, KI, and KD. 
Tuning the PID for roasters with very long dead time (e.g. Hottop) requires small KI values (KI is inversely proportional to the system delay) on the order of 0.01-0.02, which does not allow for much numeric resolution. Since KI is nevertheless a useful parameter, it would be helpful to allow 3 decimal places (to be able to use values like e.g. 0.015) and allow for sufficient numeric resolution.

**Comment by MAKOMO** [comment]
Just changed this. Will be part of the next release. Thanks for the hint!
