### ISSUE TITLE
About WebSockets Port

### ISSUE THREAD

**Issue by highmore** [artisan-roaster-scope/artisan#639]
Hello everyone, can I control all the functions of artisan through artisan's WebSockets port?
If the answer is yes, 
Can anyone provide detail of WebSockets interface information?

**Comment by MAKOMO** [comment]
> On 15. Jul 2021, at 18:17, highmore ***@***.***> wrote:
> 
> 
> Hello everyone, can I control all the functions of artisan through artisan's WebSockets port?

Not sure what exactly you refer to by "all the functions". The WebSocket interface is to READ data from a device and not to control Artisan.

> If the answer is yes,

The answer is most likely no.

> Can anyone provide detail of WebSockets interface information?

https://artisan-scope.org/devices/websockets/

M

**Comment by highmore** [comment]
Oh, it is used to read data, and can't be used to send instructions?

**Comment by MAKOMO** [comment]
> On 15. Jul 2021, at 18:23, highmore ***@***.***> wrote:
> 
> 
> Oh, it is used to read data, and can't be used to send instructions?

Well, the WebSocket Command allows to send out JSON.

Check its documentation,
M
