### ISSUE TITLE
Comparator file / roast names are not readable (no contrast)

### ISSUE THREAD

**Issue by InvisibleOrdinary** [artisan-roaster-scope/artisan#655]
**Describe the bug**
When not selected, the roast titles / names are too light against the background color and not legible

**To Reproduce**
Open comparator and deselect the roast names

**Expected behavior**
to see them

**Screenshots**

<img width="586" alt="Screen Shot 2021-08-03 at 8 45 05 PM" src="https://user-images.githubusercontent.com/16738749/128119077-aeaf0d14-c73b-4b51-ad6c-0fd398bb6a97.png">**Setup 

(please complete the following information):**
 - Artisan Version [e.g. v2.4.4]: 2.4.5
 - Artisan Build (number in brackets shown in the about box) [e.g. 97e6dec]:  (71e271c)
 - Version [e.g. 22]: 
 - Platform (Mac/Windows/Linux + OS version) [e.g. macOS 10.15.3]: Mac 11.5.1
 - Connected devices or roasting machine [e.g. Probatone 5]: none for this

**Additional context**

If there is a setting that controls the color for this, that would solve it as well. 
[Buckman-10K_V2.aset.zip](https://github.com/artisan-roaster-scope/artisan/files/6928444/Buckman-10K_V2.aset.zip)

Please attach your current Artisan settings file (as exported via menu Help >> Save Settings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
Why are you running v2.4.5?

Builds with uneven minor numbers are development versions and not signed. Apps not notarized do not respect the systems dark mode setting, but Artisan code itself is not aware that it is running unsigned thus it applies the dark mode color scheme to its custom widgets with the result that the system widgets and the custom widget colors do not blend well. 

Thus either deactivate dark mode on your macOS or run a release version that is signed and notarized by Apple.

Current latest release is v2.4.6. Note that older versions than the latest release version are unsupported.
