### ISSUE TITLE
ET not detected

### ISSUE THREAD

**Issue by cbc1121** [artisan-roaster-scope/artisan#656]
ET not detected 

**To Reproduce**

**Expected behavior**

**Screenshots**
![IMG_8867](https://user-images.githubusercontent.com/88202316/128315981-dfc361a9-b40e-4cd0-b7cf-8b8f80626255.PNG)

**Setup (please complete the following information):**
 - Artisan Version v2.4.6
 - Artisan Build : 8002ac9 
 - Version [e.g. 22]: 10.0.18362
 - Platform : Windows 10
 - roasting machine Santoker

**Additional context**

Please attach your current Artisan settings file (as exported via menu Help >> Save Settings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.
[artisan-settings.aset.zip](https://github.com/artisan-roaster-scope/artisan/files/6936184/artisan-settings.aset.zip)

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by roasterdave** [comment]
@cbc1121 It is not possible to help when you provide no information.  Please update with the information requested in the issue form above.

**Comment by cbc1121** [comment]
> @cbc1121 It is not possible to help when you provide no information. Please update with the information requested in the issue form above.

hi dave,
I edited my post :)

**Comment by MAKOMO** [comment]
You seem to have a Santoker BT USB (eg. R3) machine which communicates via USB using the Center 301 protocol. However, for some reasons you have a mixed setup which blends a MODBUS extra device in. 

To fix:

1) menu Config >> Device, 2nd tab "Extra Devices", press Reset to remove that one extra device
2) menu Config >> Device, 3rd tab "Symb ET/BT", remove the "Y3" from the "ET Y(x)" field
3) menu Config >> Port, 3rd tab "MODBUS", set all Slave IDs in the first row of the table to 0

**Comment by cbc1121** [comment]
Thanks Marco. Problem solve 🤟🏾

**Comment by roasterdave** [comment]
Excellent!

**Comment by cbc1121** [comment]
Hi,

My artisan go something off again. When I’m not roasting. The BT difference number keep going up and down. 

Here video when I’m not roasting
