### ISSUE TITLE
Ability to configure default save filename template

### ISSUE THREAD

**Issue by edgimar** [artisan-roaster-scope/artisan#657]
When saving a roast, the current default filename format is `<title>_<date>`.  It would be nice if this were configurable, so that you could choose a format (e.g. something like `%Y%m%d%H%M\_%{title}`) that would be used to generate the default filename.

**Comment by CarefreeBuzzBuzz** [comment]
Please look at the Quick Start Guide section on Autosave. 

Michael Herbert 
CarefreeBuzzBuzz

**Comment by MAKOMO** [comment]
There is also a whole block post on this sophisticated mechanism: [Autosave File Naming](https://artisan-roasterscope.blogspot.com/2020/05/autosave-file-naming.html)
