### ISSUE TITLE
Language switching is broken

### ISSUE THREAD

**Issue by MAKOMO** [artisan-roaster-scope/artisan#671]
**Describe the bug**
Using the menu Config >> Language to switch to any other UI language has no effect after restart. The internal locale variable is correctly set as reflected by the menu entry, but the QTranslations are not loaded.

**Additional context**
This seems to be an negative effect of PR #659. 
@benwah

**Comment by benwah** [comment]
@MAKOMO  - I've just self-assigned this. I should be able to find some time to fix it next week.

**Comment by MAKOMO** [comment]
This is very tricky. Those translators have to be established at a certain time before some other classes are created. I totally forgot the exact details, but the way it was before your PR was the way it worked (with the drawback of this global var).

Thanks for looking into this.

**Comment by MAKOMO** [comment]
Fixed with Commit c115619d935d5f7be196da753dffd70331e11eef
