### ISSUE TITLE
TC4 could not convert string to float

### ISSUE THREAD

**Issue by fcebreros** [artisan-roaster-scope/artisan#676]
I'm using Artisan 2.4.4 on Ubuntu (couldn't run the last version )
and I get an error @Line5435 "arduinotc4temperature(): could not convert string to float"
when I start the readings.
Same board and settings were  working fine with Artisan 1.5 on raspbian

Artisan 2.4.4
Ubuntu / Linux
TC4 shield on Arduino Uno

![20210827_174648](https://user-images.githubusercontent.com/56903027/131203573-f1f02367-d812-4b32-93d0-95da75749b76.jpg)

**Comment by MAKOMO** [comment]
Why couldn't you install the latest version?

**Comment by fcebreros** [comment]
I could install the last version apparently without any problems but it simply didn't launch.

**Comment by MAKOMO** [comment]
Could you please reinstall v2.4.6, start it via

# /usr/share/artisan/artisan

and report the error which is logged on startup to the shell such that we can investigate the issue?

**Comment by fcebreros** [comment]
It seems some python stuff is missing.
I'm on Ubuntu 16.06 LTS and right now upgrading to 18.
I tried the same settings on Artisan 1.5 and got the same TC4 error.
It reads the temperature  but randomly stops because of the string to float error.
![20210828_100050](https://user-images.githubusercontent.com/56903027/131222515-d4309edd-9833-4728-9e32-f55640c1ff24.jpg)

**Comment by fcebreros** [comment]
Hi, 
I had the same errors trying to install the latest Artisan on Ubuntu18.
I did manage to get the TC4 board running on Artisan 2.4.4 by setting the TC4 filters to 0%

**Comment by MAKOMO** [comment]
Artisan v2.4.6 is build on Ubuntu 20.

The communication error you see must be related to the TC4 firmware you are running. Best to run aArtisan_PID_6 or newer.

**Comment by fcebreros** [comment]
OK, thanks for the info.
