### ISSUE TITLE
Apple Big Sur 11.5 no connected HB600 Standard

### ISSUE THREAD

**Issue by erminiacritical** [artisan-roaster-scope/artisan#678]
**Describe the bug**
I connected the HB600 Standard roaster with the Mac Book Pro 11.5. through a USB cable.
The system reports a Modbus error and above all the connection is not constant. It starts with all the values, but more or less at the Turning Point it loses them partially. I have checked the configuration of the roaster and the interface several times but without success. Do you have any suggestions?

<img width="1280" alt="Schermata 2021-08-18 alle 17 25 54" src="https://user-images.githubusercontent.com/89860413/131536831-ccb3d10f-dd91-40ca-bb4b-6e4dd65557e9.png">

**Comment by MAKOMO** [comment]
The error indicates that Artisan (or rather your mac) cannot open the serial port. Did you install any device driver? Which version?

Which version of Artisan are you using? Please attach your artisan-settings.aset file (export via menu Help >> Save Settings and rename from .aset into .txt and drag-drop it here). Please also tick the "Serial Log ON/OFF" flag under menu Help >> Serial and record until you see the errors and cut-copy-paste the error log here.

**Comment by erminiacritical** [comment]
I have now installed CP210xVCP x USB to Uart Bridge.
I have now downloaded Artisan 2.4.6
I attach .txt file
Zero errors reported
Tomorrow I will try a profile with the new set-up and I hope that everything will be fine.
Many thanks Marko, I'll keep you updated.

Erminia



       ERMINIA NODARI
       CO-FOUNDER 
       ***@***.***
       www.critical.coffee 
       +393476093236
     
        



Le informazioni contenute nella comunicazione che precede possono essere riservate e sono, comunque, destinate esclusivamente alla persona o all'ente sopraindicati. La diffusione, distribuzione e/o copiatura del documento trasmesso da parte di qualsiasi soggetto diverso dal destinatario è proibito. Se avete ricevuto questo messaggio per errore, Vi preghiamo di contattarci immediatamente tramite e-mail e di cancellare questo messaggio.
Grazie
Confidentiality notes: the information in this message is intended to be confidential and for the use of only the individual or entity named above.
The information herein contained may considered legally privileged information. If you are not the intended recipient you are notified that retention, dissemination, distribution the than to the intended recipient, or copying of this message is strictly prohibited. If you receive this message in error please notify us. 
 Nodari
***@***.***

**Comment by MAKOMO** [comment]
Stall
