### ISSUE TITLE
Problems with [2.4.6] under LMDE4

### ISSUE THREAD

**Issue by catpeer** [artisan-roaster-scope/artisan#693]
Version 2.4.6 doesn’t run under Linux anymore. I attach the output of strace. Maybe it helps.
[strace-artisan-2.4.6.txt](https://github.com/artisan-roaster-scope/artisan/files/7192634/strace-artisan-2.4.6.txt)

**Comment by MAKOMO** [comment]
Hm

**Comment by MAKOMO** [comment]
This is not much information and the strace is not conclusive. Which platform exactly are you trying to run Artisan on? How did you install Artisan exactly?

**Comment by MAKOMO** [comment]
Note that several people are running Artisan v2.4.6 successful under Linux (mostly Ubuntu).
Maybe you also find a better title for this issue.

**Comment by catpeer** [comment]
I use a Linuxmint distribution LMDE 4 which is based on Debian 10 with the kernel version 5.10.0-0.bpo.3-amd64. I dit use the version 2.1.2 up today and I installed all versions with an installation tool (GDebi). Now I installed version 2.4.4 and it runs again. The only small issue I had in the past was a long starting time.
Please excuse my akward posting, since it’s my first one github.

**Comment by catpeer** [comment]
After further investigation I have to admit that the issue I do have with v2.4.6 depends on my own installation. I was able to run artisan v2.4.6 in a virtual machine.
I regret to have caused some trouble. A software considerably useful.
