### ISSUE TITLE
Artisan inserts power event when nothing occurred

### ISSUE THREAD

**Issue by Brewzologist** [artisan-roaster-scope/artisan#695]
**Describe the bug**
Upon starting a roast with the ASET file attached, Artisan will insert an empty power event as the 3rd event in the roast.  This consistently happens both in the simulator and during actual roasts.

**To Reproduce**
1. Start Artisan and load the attached ASET file
2. Load the simulator in Artisan using any ALOG file.
3. Press the ON button in the simulator
4. Press OK to dismiss my user popup dialog box
5. Press START to begin the simulated roast
6. Press CHARGE button at your desired time in your ALOG file (e.g. 375F)
7. An empty power event is added as soon as the CHARGE button is pressed.  It is always the 3rd event under Roast/Properties/Events

**Expected behavior**
The empty power event should not be added to the roast

**Screenshots**
N/A

**Setup (please complete the following information):**
 - first noted in v2.4.4 and continues in v2.4.6
 - Artisan Build: daf2bac 
 - Version [e.g. 22]: 1
 - Platform (Mac/Windows/Linux + OS version) [e.g. macOS 10.15.3]:  Windows 10 with latest updates
 - Connected devices or roasting machine [e.g. Probatone 5]:  VINT Phidgets, Arduino, servo controllers (but not needed to create this bug)

**Additional context**
I included an ALOG file for reference only, but this happens with any of my roasts.

Please attach your current Artisan settings file (as exported via menu Help >> Save Settings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.
[Artisan Defect Files.zip](https://github.com/artisan-roaster-scope/artisan/files/7220639/Artisan.Defect.Files.zip)

**Comment by MAKOMO** [comment]
Thanks for this detail and easy to reproduce report. You actually hit a feature. On user request Artisan marks events with (non-zero) active sliders on CHARGE.

This is not productive for your case as you set initial event values via alarms before CHARGE on START.

I modified the behavior of Artisan in this respect to avoid the addition of events on CHARGE if corresponding events have already by set.
