### ISSUE TITLE
Websocket Event

### ISSUE THREAD

**Issue by oscarquiroz94** [artisan-roaster-scope/artisan#702]
I want to send a Json when the Charge event button has been pressed. I have this configuration:

![events](https://user-images.githubusercontent.com/70978150/135165224-89f95142-8763-497f-94c6-7fa04f646bdf.PNG)

But I never see that register in serial output when I push the Charge button:

![serial](https://user-images.githubusercontent.com/70978150/135165547-d3b170fc-6e60-4570-bf63-dfcf122f1aaf.PNG)

What am I doing wrong ?

  - Artisan Version: 2.4.4
  - Artisan Build: (1fb3d349)
  - Platform: Windows
  - Connected devices or roasting machine: Device Test
  
[websocketEvent.zip](https://github.com/artisan-roaster-scope/artisan/files/7247253/websocketEvent.zip)

Regards!

**Comment by MAKOMO** [comment]
You are using an outdated version of Artisan.

Don't escape JSON if used in non-substituting actions. Try

```send({"pushMessage":"startRoasting"})```

Substituting actions are custom button event actions and custom slider event actions where the event value is substituted. Escaping JSON in other places fails (silently).

If successfully send, you should also see a corresponding entry in the serial log.

I tried to improve the WebSocket documentation on this point: https://artisan-scope.org/devices/websockets/
