### ISSUE TITLE
Typing chinese is not working in linux

### ISSUE THREAD

**Issue by nibofly** [artisan-roaster-scope/artisan#708]
I have installed artisan 2.4.6 in linux mint 20.2 cinnamon, but I cannot input Chinese characters by using fcitx and gcin. 
It is normal to input Chinese characters in other software, but only artisan does not work.
I have chosen the source han sans font in the theme interface of the curve, still not working.
Is there a solution?

**Comment by MAKOMO** [comment]
Seems to me a platform specific issue as this works flawless at least on Windows and macOS. Not much we can do on this as data input is handled by the operating system and the corresponding GUI system. Sorry.
