### ISSUE TITLE
Button with "IO Command" does not take the sleep(<float>) command

### ISSUE THREAD

**Issue by bigl00z3** [artisan-roaster-scope/artisan#726]
**Describe the bug**

I am trying to set a visual alarm by flashing a LED (several times in a row to have it more visible)
I send a command to a Phidget 1019 by calling a button which is using the "IO Command":

The button's IO command is:
_**`pulse(0,1000,595251);sleep(1);pulse(1,1000,595251);sleep(3);pulse(2,1000,595251)`**_

For the test, I have set it to 3 different LEDs on different Phidgets output ports to allow to see if they all flash at the same time or if they do it in a sequence. For the test 

Result: they all flash at the same time once for 1000ms 
--> the sleep function does not seem to work.

This is confirmed by the "Message History" where I get the error "_No match for command  [sleep], continuing_"

Based on the Button's help menu, I would expect it to be feasible as under IO Command:

_ IO Command     Help sleep(<float>)   sleep: add a delay of <float> seconds_

**Setup (please complete the following information):**
 - Artisan Version [e.g. v2.4.4]: 2.4.5
 - Artisan Build (number in brackets shown in the about box) [e.g. 97e6dec]: 
 - Version [e.g. 22]: 
 - Platform (Mac/Windows/Linux + OS version) [e.g. macOS 10.15.3]: 
 - Connected devices or roasting machine [e.g. Probatone 5]: 

**Additional context**

Please attach your current Artisan settings file (as exported via menu Help >> Save Settings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
IO Command sleep() is broken and maybe always was. A simple typo.
