### ISSUE TITLE
Request for temp label along with gas setting along timeline

### ISSUE THREAD

**Issue by fatrabbit-la** [artisan-roaster-scope/artisan#753]
If this is not already possible (I couldn't find it), I would like to request an option to list the BT along with changes in gas setting. The way I have things set up, my charts along the timeline show the gas setting with a line below that. Would be great to see BT below the line. It's a bit hard to tell, especially on the fly, what exactly the temp is at a given time. I use background roasts for consistency and if I make minor changes to the timing of changes, often based on BT, it's impossible to remember these detailed changes.

**Comment by roasterdave** [comment]
Have you looked at [event annotations](https://artisan-roasterscope.blogspot.com/2020/05/special-events-annotations.html)?  These could give you all the details you want to see in your profile.

![Graph 4](https://user-images.githubusercontent.com/30009312/145160174-fb42c2bb-e220-4da4-8de8-717d23890d16.png)


To see a temperature on the fly at any time, move the mouse cursor and view the time (x) and temperature (y) value which is displayed near the top.  To change the y value from the Temperature axis to the RoR axis and back, hit the 'd' key.

![Screenshot - 12_7_2021 , 10_15_10 PM](https://user-images.githubusercontent.com/30009312/145158520-490ccbd4-3a05-4ffb-bee6-aad39271e3c8.png)


To toggle on or off cross hairs hit the 't' key (Ctrl+Shift+t on Windows).  

![Screenshot - 12_7_2021 , 10_36_44 PM](https://user-images.githubusercontent.com/30009312/145160628-39eff099-ada7-411e-ba63-c273b56d3ce1.png)


With the cross hairs on hold down the left mouse button and drag to measure differences.

![Screenshot - 12_7_2021 , 10_25_45 PM](https://user-images.githubusercontent.com/30009312/145159856-9353d174-57c3-402c-8a54-e07b42990f32.png)

Do these provide what you are looking for?

**Comment by InvisibleOrdinary** [comment]
Thank you for posting that… I didn't know that existed, and I definitely see the use in that. Is it possible to lock the cross hairs and measuring to the curve (BT) so it would show deltas along the bean's trajectory - seems to me that a simple straight difference would be fine for this.

**Comment by roasterdave** [comment]
No, you cannot lock the cross hairs.  However, you should be able to get want you want with a virtual device, that displays the difference in an LCD during roasting and/or as a curve.  The basics are in this [blog article](https://artisan-roasterscope.blogspot.com/2019/11/symbolic-formulas-basics-new-variables.html).  More blog articles with examples can be found with [this search](https://artisan-roasterscope.blogspot.com/search?q=virtual++devices).

**Comment by InvisibleOrdinary** [comment]
Ok…  that is fine (I do have an LCD that shows what I refer to  most), but not the same thing as being able to see the delta between any two selected points. Close enough in most cases, though.

--
Dave Ewald
Deft Coffee Roasters  |  503.702.1932  |  a part of something more

**Comment by fatrabbit-la** [comment]
Yes, this is great! My only request then, because I didn’t see this as an option in the help file, would be if it would be possible to insert a [return] such that you can create a line break in order to avoid information overlapping. I do see the ability to compensate for overlap, but that ends up deleting (making invisible) data.

Many thanks for pointing this out.

Dan

Fat Rabbit Coffee
***@***.*** ***@***.***>
www.fatrabbitcoffee.com <http://www.fatrabbitcoffee.com/>

**Comment by roasterdave** [comment]
Dan, there is no way to insert a line break at this time.  One other thing to try is to increase the size of the steps so the annotations have some separation.  Change the setting for Config>> Events>> 100% Event Step.  Increasing the value will stretch the steps upward.

**Comment by fatrabbit-la** [comment]
David,

Can you please clarify? I’m on Config > Events and I see Step as an option for Markers (that’s what I currently use) but I don’t see where to set Event Step to 100%. To the far right of that I see values I can adjust from 1 - 20. It doesn’t seem to make a difference but perhaps that’s just because of the particular graph I’m looking at.

I looked on other tabs to adjust Event Step but only see it on the Config page.

Dan

Fat Rabbit Coffee
***@***.*** ***@***.***>
www.fatrabbitcoffee.com <http://www.fatrabbitcoffee.com/>

**Comment by CarefreeBuzzBuzz** [comment]
https://artisan-roasterscope.blogspot.com/2020/05/special-events-annotations.html <https://artisan-roasterscope.blogspot.com/2020/05/special-events-annotations.html>

Read this entire blog post for clarification on items.  There are often blog posts on the various features.  

That’s the first place to go.  Hope this helps.  


----------------------------------------
Michael Herbert, Head Roaster
Order at www.carefreebuzzbuzz.com <http://www.carefreebuzzbuzz.com/>
Artisan RoasterScope  <https://artisan-scope.org/>Team

**Comment by roasterdave** [comment]
Dan, the correct location is Config>> Axes.  Sorry for the confusion.
