### ISSUE TITLE
ROR is double what it should be

### ISSUE THREAD

**Issue by JamieMcLuckie** [artisan-roaster-scope/artisan#754]
Hi, I have been roasting using Artisan 2.4.2 on a Giesen W15 today.  The BT ROR on the control tower of the Giesen reads half of what the BT ROR reads within Artisan.   Have I by accident changed a setting that makes Artisan double the BT ROR? Hopefully someone can help?  Thank you.

**Expected behavior**
Expect the delta BT to be the same if not very close to the Giesen control tower delta BT (ROR). 

**Setup (please complete the following information):**
 - Artisan Version 2.4.2 
 - Artisan Build bcaf44d 
 - Version  Build 3
 - Platform Mac 10.15.4
 - Connected devices or roasting machine Giesen W15A 2021 model 
 - 
[artisan-settings.aset.txt](https://github.com/artisan-roaster-scope/artisan/files/7678679/artisan-settings.aset.txt)

**Comment by MAKOMO** [comment]
Artisan uses a proper unit (C/min or F/min) to represent the rate of rise. I guess Giesen is showing the rate of rise as C/30s or F/30s like Cropster.

Your question is a FAQ. Please check [8) How can I get the rate-of-rise in F/30sec?](https://artisan-scope.org/help/#FAQ-Recording-8).
