### ISSUE TITLE
Artisan Installation Issues 2.4.6. with HB600

### ISSUE THREAD

**Issue by erminiacritical** [artisan-roaster-scope/artisan#757]
Hi Marko,
after many attempts I cannot run  my HB600 with Artisan.
These are the errors reported.
I am also attaching screenshots of the configuration.
can you help me?
Thank you
Erminia

Artisan 2.4.6
MacBook Pro Mac Os Big Sur 11.6

[ERRORIARTISAN.docx](https://github.com/artisan-roaster-scope/artisan/files/7711732/ERRORIARTISAN.docx)
![WhatsApp Image 2021-12-09 at 13 08 08](https://user-images.githubusercontent.com/89860413/146001856-f1edd7ae-bff6-4d69-bdb2-bc8e96af7e9c.jpeg)
![WhatsApp Image 2021-12-09 at 13 08 04](https://user-images.githubusercontent.com/89860413/146001926-e7c1c058-aee1-44a5-bda8-90c1fb30ddbb.jpeg)
![WhatsApp Image 2021-12-09 at 13 08 05 (1)](https://user-images.githubusercontent.com/89860413/146001942-313e88ad-32ff-4816-bab9-08602c387044.jpeg)
![WhatsApp Image 2021-12-09 at 13 08 05](https://user-images.githubusercontent.com/89860413/146001947-9255f69e-ed90-467b-84ee-796d74d73dbd.jpeg)
![WhatsApp Image 2021-12-09 at 13 08 06 (1)](https://user-images.githubusercontent.com/89860413/146001957-51097435-077d-4e10-ad80-ed992badbb84.jpeg)
![WhatsApp Image 2021-12-09 at 13 08 06](https://user-images.githubusercontent.com/89860413/146001966-77f51c37-4b35-410d-a48e-94cd8afe3277.jpeg)
![WhatsApp Image 2021-12-09 at 13 08 07](https://user-images.githubusercontent.com/89860413/146001972-03e938b8-a156-4d72-a33a-14e64e60a781.jpeg)
![WhatsApp Image 2021-12-09 at 13 08 08](https://user-images.githubusercontent.com/89860413/146001981-30b736fe-5636-4291-9f1a-2ac396be4d16.jpeg)
![WhatsApp Image 2021-12-09 at 13 08 10](https://user-images.githubusercontent.com/89860413/146001983-6d575ce4-76bc-4693-8677-22f794ed2d6b.jpeg)

**Comment by MAKOMO** [comment]
Obviously, Artisan cannot open the serial port you indicated. Did you install the required serial driver from SiLabs as noted in the documentation?

https://artisan-scope.org/machines/hb/

**Comment by erminiacritical** [comment]
Thanks Marko, 
I have already installed the driver, but it doesn't work.
Maybe I need to change some values?
Erminia





       ERMINIA NODARI
       CO-FOUNDER 
       ***@***.***
       www.critical.coffee 
       +393476093236
     
        



Le informazioni contenute nella comunicazione che precede possono essere riservate e sono, comunque, destinate esclusivamente alla persona o all'ente sopraindicati. La diffusione, distribuzione e/o copiatura del documento trasmesso da parte di qualsiasi soggetto diverso dal destinatario è proibito. Se avete ricevuto questo messaggio per errore, Vi preghiamo di contattarci immediatamente tramite e-mail e di cancellare questo messaggio.
Grazie
Confidentiality notes: the information in this message is intended to be confidential and for the use of only the individual or entity named above.
The information herein contained may considered legally privileged information. If you are not the intended recipient you are notified that retention, dissemination, distribution the than to the intended recipient, or copying of this message is strictly prohibited. If you receive this message in error please notify us. 
 Nodari
***@***.***

**Comment by erminiacritical** [comment]
> Thanks Marko, 
> I have already installed the driver, but it doesn't work.
> Maybe I need to change some values?
> Erminia






       ERMINIA NODARI
       CO-FOUNDER 
       ***@***.***
       www.critical.coffee 
       +393476093236
     
        



Le informazioni contenute nella comunicazione che precede possono essere riservate e sono, comunque, destinate esclusivamente alla persona o all'ente sopraindicati. La diffusione, distribuzione e/o copiatura del documento trasmesso da parte di qualsiasi soggetto diverso dal destinatario è proibito. Se avete ricevuto questo messaggio per errore, Vi preghiamo di contattarci immediatamente tramite e-mail e di cancellare questo messaggio.
Grazie
Confidentiality notes: the information in this message is intended to be confidential and for the use of only the individual or entity named above.
The information herein contained may considered legally privileged information. If you are not the intended recipient you are notified that retention, dissemination, distribution the than to the intended recipient, or copying of this message is strictly prohibited. If you receive this message in error please notify us. 
 Nodari
***@***.***

**Comment by erminiacritical** [comment]
Ok, tomorrow I'll try while the roaster 'll be connected. Sorry but I'm not a software expert. I hope that I will understand which port to choose.

E



       ERMINIA NODARI
       CO-FOUNDER 
       ***@***.***
       www.critical.coffee 
       +393476093236
     
        



Le informazioni contenute nella comunicazione che precede possono essere riservate e sono, comunque, destinate esclusivamente alla persona o all'ente sopraindicati. La diffusione, distribuzione e/o copiatura del documento trasmesso da parte di qualsiasi soggetto diverso dal destinatario è proibito. Se avete ricevuto questo messaggio per errore, Vi preghiamo di contattarci immediatamente tramite e-mail e di cancellare questo messaggio.
Grazie
Confidentiality notes: the information in this message is intended to be confidential and for the use of only the individual or entity named above.
The information herein contained may considered legally privileged information. If you are not the intended recipient you are notified that retention, dissemination, distribution the than to the intended recipient, or copying of this message is strictly prohibited. If you receive this message in error please notify us. 
 Nodari
***@***.***

**Comment by MAKOMO** [comment]
resolved by configuration, see Issue 758
