### ISSUE TITLE
ERROR MODBUS AND SERIAL EXCEPTION- MACPRO VS HB600

### ISSUE THREAD

**Issue by erminiacritical** [artisan-roaster-scope/artisan#758]
Hi Marko,
I am very happy because I think I have solved the problem that bars Artisan and HB600 to run together.
I share in the blog:
To avoid:
  - Modbus 1 communication error 14: 23: 09.740 Modbus error: writeMask () Modbus Error: [Connection] Failed to connect [ModbusSerialClient (rtu baud [115200])] @ line 493
- Serial Exception: Not able to open serial port
After installing the driver CP210X VPC on the Mac (remember to open the privacy lock)
Connect Artisan with the roaster turned on and in the Port Configuration screen choose CP2102 USB to UART Bridge Controller
In the Modbus screen: choose v / cu.usbserial-0001.
Thanks for the cooperation Marko !!!!! I was born in the pre-digital era and I am really satisfied when I overcome the obstacle :)
Erminia

![IMG_0746](https://user-images.githubusercontent.com/89860413/146245086-edc9ad9b-4970-4e77-b2dc-151ddb5bc1f5.jpg)
![IMG_0747](https://user-images.githubusercontent.com/89860413/146245104-41b3b579-701b-4a90-bd01-85f3d2ce504e.jpg)
![IMG_0748](https://user-images.githubusercontent.com/89860413/146245115-e7312d35-23d1-44e4-b0f1-b3de8522f32d.jpg)
![IMG_0754](https://user-images.githubusercontent.com/89860413/146245124-6ac4bb9d-0b1f-43e0-a528-9387fde8824a.jpg)

**Screenshots**

**Setup (please complete the following information):**
 - Artisan Version [e.g. v2.4.4]: 
 - Artisan Build (number in brackets shown in the about box) [e.g. 97e6dec]: 
 - Version [e.g. 22]: 
 - Platform (Mac/Windows/Linux + OS version) [e.g. macOS 10.15.3]: 
 - Connected devices or roasting machine [e.g. Probatone 5]: 

![IMG_0757](https://user-images.githubusercontent.com/89860413/146245136-57a30ef3-3249-412c-abbf-4c22a0d48cb6.jpg)

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment]
Thanks for this confirmation!

**Comment by erminiacritical** [comment]
Hi, I still have problems. This is just a test to see if I can reopen this thread just by commenting.

**Comment by erminiacritical** [comment]
I’m @erminiacritical
👀 Hi Marko, my problem is not solved.( HB600)  I roasted yesterday only once seeing the ET / BT values on the display even in the presence of the MODBUS error. Today I don't see the values and therefore I have to roast without curve and without RoR. I attach a list of errors and screenshots. Where should I change? What should I change? Please help me
[17dicembre.docx](https://github.com/artisan-roaster-scope/artisan/files/7736637/17dicembre.docx)
![IMG_0775](https://user-images.githubusercontent.com/89860413/146581593-bcad215e-4d57-427c-831f-25e708597ed4.jpg)
![IMG_0776](https://user-images.githubusercontent.com/89860413/146581613-e98de57b-6988-406f-9109-db0b1f09137c.jpg)
![IMG_0777](https://user-images.githubusercontent.com/89860413/146581617-7fed2c31-d55f-4a75-8fbe-e9401d14bca0.jpg)
![IMG_0778](https://user-images.githubusercontent.com/89860413/146581624-34c67ec7-4dad-4623-a533-9f4afedc6686.jpg)
![IMG_0779](https://user-images.githubusercontent.com/89860413/146581638-d4c05d88-836e-4af5-9256-4986c5bd5c3f.jpg)
![IMG_0780](https://user-images.githubusercontent.com/89860413/146581649-6cc8de7a-9a19-4697-9f89-717ed3fe3c0a.jpg)
![IMG_0781](https://user-images.githubusercontent.com/89860413/146581661-ae5a63bd-5962-4a98-9b24-df66cefd1966.jpg)
![IMG_0782](https://user-images.githubusercontent.com/89860413/146581680-f31f840e-b7ad-4b8d-98c1-2228806e03a4.jpg)

**Comment by MAKOMO** [comment]
Hi,

your setup is (again) totally broken. Your machine is NOT communicating via MODBUS thus your should not have MODBUS configured at all.

I can only guess that you loaded an .alog profile recorded on a different setup (one with MODBUS configured) and answered the dialog

<img width="573" alt="Screenshot 2021-12-17 at 20 38 18" src="https://user-images.githubusercontent.com/13909011/146598882-425ba4af-c31c-4e42-bffa-4e16a7819162.png">

with YES instead of NO. As a consequence your setup got modified.

Do the following:

1) Factory Reset
  menu Help >> Factory Reset
2) Setup again for your HB roaster
  menu Config >> Machine >> HB >> ..
as you did before.
