### ISSUE TITLE
Blend weight input vs ratio

### ISSUE THREAD

**Issue by Javapik** [artisan-roaster-scope/artisan#760]
I'd like to suggest the enhancement of allowing Blend components to be inputted by weight in addition to ratios on Artisan.plus. I prefer to make pre-roast blends and construct them by gram weight - especially when making a blend for the first time. Currently I'm having to divide the individual bean by the total batch size to figure the ratio but then in the roast properties "Bean' box that isn't matching and is throwing off my inventory. Example for a blend of 120gr Brazil and 50gr Costa Rica, and 40 gr Ethiopia I have to input 57%, 24%, and 19%. Then when its time to roast I go to Roast Properties in the app and choose the blend from the "Blend" pull down menu, then I input that my roast total weight is 210 grams. But, the Bean description box then shows I'm using 119.7 gr of Brazil, 50.4 gr of Costa Rica, and 39.9 gr of Ethiopia. More roasts of this Blend will compound the discrepancy and make my inventory increasingly inaccurate.
Thanks in advance. Ed

**Comment by MAKOMO** [comment]
added for v2.4.6

**Comment by Javapik** [comment]
Thank you!
