### ISSUE TITLE
TC4 error

### ISSUE THREAD

**Issue by RinaldAbuud** [artisan-roaster-scope/artisan#774]
### Discussed in https://github.com/artisan-roaster-scope/artisan/discussions/773

<div type='discussions-op-text'>

<sup>Originally posted by **RinaldAbuud** December 28, 2021</sup>
ser.ARDUINO TC4temperature(): WriteFile failed (PermissionError(13, 'Access is denied.',None, 5))@line 5352

anyone can help me for this problem..?</div>

**Comment by MAKOMO** [comment]
Seems not an issue with the software. No need to file an issue AND a discussion item.
