### ISSUE TITLE
Artisan crashes when saving Ramp/Soak settings to .aprs (in Control window)

### ISSUE THREAD

**Issue by bigl00z3** [artisan-roaster-scope/artisan#777]
**Describe the bug**

Artisan crashes when saving Ramp/Soak settings (in Control window)

**To Reproduce**

Tested on Mac OSX and Raspberry Pi. both giving the same issue
1. Open the PID Control Window
2. Move to Ramp/Soak tab
3. Press "Save"
4. Type a name for the file and press save
5. Artisan freezes, need to force quit

**Expected behavior**

Saving RampSoak settings to .aprs file

**Setup (please complete the following information):**
 - Artisan Version [e.g. v2.4.4]:  2.4.7 (on OS X) and 2.4.6 build 2 (on RPI)
 - Artisan Build (number in brackets shown in the about box) [e.g. 97e6dec]: 55dcc17 (on OS X) and fyb8e574) (on RPI)
 - Version [e.g. 22]: 
 - Platform (Mac/Windows/Linux + OS version) [e.g. macOS 10.15.3]: Mac OS X 12.1 and RaspberryPi Buster
 - Connected devices or roasting machine [e.g. Probatone 5]: Modbus, Phidget

**Additional context**

Please attach your current Artisan settings file (as exported via menu Help >> Save Settings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._
[artisan-settings Nbi 7.5 - 2 PIDs Modbus.aset.txt](https://github.com/artisan-roaster-scope/artisan/files/7793836/artisan-settings.Nbi.7.5.-.2.PIDs.Modbus.aset.txt)

**Comment by MAKOMO** [comment]
Thanks for reporting. Fixed in code.
