### ISSUE TITLE
Events not showing for lower values

### ISSUE THREAD

**Issue by EauRougeRoasters** [artisan-roaster-scope/artisan#802]
When adjusting Fan or Heater on the roaster (Aillio Bullet V2) the events display down to 50% (H50, for example). If either input is reduced below 50% the event will not display.

As a workaround, if the Artisan slider is manually pulled down to a value below 50 the event will display. However roaster inputs are not recognized again until at 50 or above.

[https://imgur.com/a/zeoM13M](url)

**Setup (please complete the following information):**
 - Artisan Version [e.g. v2.4.4]: 2.1.2
 - Artisan Build (number in brackets shown in the about box) [e.g. 97e6dec]: 2d7c9951
 - Version [e.g. 22]: 
 - Platform (Mac/Windows/Linux + OS version) [e.g. macOS 10.15.3]: Windows 10 Home Version 21H1 build 19043.1466
 - Connected devices or roasting machine [e.g. Probatone 5]: Aillio Bullet V2 ITBS

**Additional context**
[artisan-settings.zip](https://github.com/artisan-roaster-scope/artisan/files/7961617/artisan-settings.zip)
[220120-1 Wassail.zip](https://github.com/artisan-roaster-scope/artisan/files/7961627/220120-1.Wassail.zip)

**Comment by MAKOMO** [comment]
You have your input filter set to ignore readings below 50. Just disable this one or set the minimum to 0.

<img width="705" alt="Screenshot 2022-01-29 at 14 21 21" src="https://user-images.githubusercontent.com/13909011/151662638-9c425801-e631-43d2-a687-706fb84417e1.png">

Any reason using an updated Artisan version? Current Artisan version is 2.4.6!
