### ISSUE TITLE
Would you be possible to allow Artisan to read ET, BT, and color values by pulling those values from a specific string format available in a serial comm port?

### ISSUE THREAD

**Issue by chiwilliam** [artisan-roaster-scope/artisan#81]
I implemented my own circuit to measure BT, ET, and color values. I used a combination of various electronics and none of them are listed in the supported list of devices. It would be great to allow Artisan to also read the values following a specific string pattern to make it universal, instead of just calling library methods. For example, a string like: BT=value,ET=value,COLOR=value[breakline] would allow us to feed all three values to Artisan while setting a specific serial configuration (com, baud, byte size, parity, stopbits and timeout).

**Comment by MAKOMO** [comment]
Sorry, I just saw this (a little late). You can configure Artisan to use an external program that produces data (see menu Config >> Devices; first tab ET/BT (click help for details; now also taking more than two values). Alternatively, you can use the TC4/Arduino device and implement the TC4 text based protocol that essentially does what you request. See the TC4 repository for the specification of that protocol: https://code.google.com/p/tc4-shield/source/browse/applications/Artisan/aArtisan/trunk/src/aArtisan/commands.txt
