### ISSUE TITLE
New Yoshan roaster support.

### ISSUE THREAD

**Issue by keshka** [artisan-roaster-scope/artisan#817]
Yoshan has come out with a great little home roaster that I would like to request be added to Artisan's support. Here is the page on Alibaba:
https://www.alibaba.com/product-detail/Roaster-Bean-Machine-Roasting-Home-Electric_1600245468069.html?spm=a2756.order-detail-ta-ta-b.0.0.14a02fc2CswulW
and on Yoshan's site:
https://www.ysroaster.com/products/yoshan-electric-500g-mini-coffee-bean-roaster-for-home-sample-roasting.html

the software they offer does not speak English nor seem to work well
Thank you
Keshka Kotera

**Comment by CarefreeBuzzBuzz** [comment]
YOSHAN has a manual for their gas roasters.  Maybe its the same for this one or maybe they have one.  Please ask them.  Without their input on the settings we would not know what to use.  

Thanks.  

Like all manufacturers they could become a Machine Supporter of Artisan.  
----------------------------------------
Michael Herbert, Head Roaster
Order at www.carefreebuzzbuzz.com <http://www.carefreebuzzbuzz.com/>
Artisan RoasterScope  <https://artisan-scope.org/>Team

**Comment by MAKOMO** [comment]
Would you please share those instruction such that we can close this issue?

**Comment by MAKOMO** [comment]
Nothing attached. You need to go to this GitHub page at https://github.com/artisan-roaster-scope/artisan/issues/817 and drag-and-drop the document in a new message to get it attached. Attachments in emails just answering this are deleted.

**Comment by keshka** [comment]
kk

**Comment by MAKOMO** [comment]
Still not attached. You need to go to this page: https://github.com/artisan-roaster-scope/artisan/issues/817

and drag-and-drop the file to the "Write" field.

**Comment by MAKOMO** [comment]
Just send the file to info@artisan.plus per email. Thanks.

**Comment by keshka** [comment]
[CP210X Yoshan ROASTER ARSTIAN DATA USER MANUAL GUIDE[211030].pdf](https://github.com/artisan-roaster-scope/artisan/files/8056733/CP210X.Yoshan.ROASTER.ARSTIAN.DATA.USER.MANUAL.GUIDE.211030.pdf)

**Comment by keshka** [comment]
I am still investigating the possibility of Artisan to control this roaster. From what I see so far, the data stream from the USB port Yoshan uses for data. The MODBUS data there is just drum and bean temp.

I have just glossed over MODBUS learning so far but it looks like one master and many slave components. There is another USB port on the inside of the machine from the Arduino they use that I think controls the heat, drum and fan speed. Just a guess but if MODBUS expects one master, trying to insert commands into the data flow might create a disaster.  Anyone with more experience please chime in. 

At this point, it seems my only option would be to reprogram there Arduino but that probably would require replacing there proprietary board used to manage heat, drum and fan.

**Comment by MAKOMO** [comment]
Most likely this machine cannot be controlled via software. Looks like they use some standard PID modules to forward ET and BT via MODBUS. Why would they use an Arduino (besides the Arduino licence does not allow its use in a commercial product)?

**Comment by MAKOMO** [comment]
Oh, you have this model with the large screen. This seems to be based on a Siemens PLC (not an Arduino). You could use the MODBUS scanner (SCAN button in the MODBUS tab under Ports) to scan for other registers and guess which ones hold the heat, exhaust air speed, and drum speed readings in a first step.

**Comment by keshka** [comment]
Yes, it does have a nice screen, made by SamKoon. They call it a "Human-computer interaction unit". They don't say much about the processor in it (http://www.samkoon.com.cn/product/detail/19) but I believe it monitors and graphs the temperatures.  I have downloaded all the "tools" SamKoon provides to work with this device however too much of it is written in Cantonese and I can't read that but what little I have been able to learn of the tools is that it's much like the Arduino IDE in that you can create an application but there is no way to download from the SamKoon screen/processor to modify the app. There is also an Arduino Uno attached to a  proprietary board used to manage heat, drum and fan. As far as the license is concerned, it is China and pretty sure they don't care.  I have scanned the MODBUS informatiion the screen provides and only bean and drum temperature seem to be there. Today I will scan what the Arduino is presenting to it's USB port as serial data. I did look at it with a serial monitor but not a MODBUS monitor. Should be interesting!

**Comment by keshka** [comment]
Had a bit of time with the roaster yesterday and discovered three MODBUS data items are being sent to the serial port of the arduono.  Didn't have time to verify the port speed and the data was hit/miss. I don't know at this point if I can insert control commands to this serial port also if Artisan can work with two ports at once
