### ISSUE TITLE
Configuration Problems

### ISSUE THREAD

**Issue by RMWILDE** [artisan-roaster-scope/artisan#83]
Hi,

I am currently roasting on a Solar FZ-94 and trying to use Artisan Software to track but I'm having issues and I believe it will just be a case of getting the correct configuration within the software.

The USB and driver I am using is a FT232R USB UART / FTDI (I'm not great with technology so I apologise if this doesn't make too much sense)

I have tested the USB connector and driver and it works fine but when in Artisan it says the following:

Modbus Error: readSingleRegister () Modbus Error: [Connection Failed] to connect[rtu baud]9600]] @line 25150

Can anyone help please?

Thanks in advance,

Reece

**Comment by MAKOMO** [comment]
Reece,

this does not sound like an issue with the software so I will close this here. Please register at the Artisan mailing list to reach out to other users (some of which successfully work with Artisan and a FZ-94) to get support from the community (registration required to be able to post!).

https://lists.mokelbu.de/listinfo/artisan-user

I collected some information on configuring Artisan for those machines on the Artisan blog:

http://artisan-roasterscope.blogspot.de/2015/01/connecting-artisan-to-coffee-tech-fz-94.html

Note that there are different version of that roaster, some requiring a different USB driver and specific configurations.

Marko
