### ISSUE TITLE
WIN 11:  When  Cursor Touches graph: TEMP/TIME not same as past

### ISSUE THREAD

**Issue by SAS613** [artisan-roaster-scope/artisan#834]
**Describe the bug**
.
When touching cursor to any line on graph, the temp and time at the top of screen is not bold, in a different location and different format.

![image](https://user-images.githubusercontent.com/100977226/156857947-11d44270-4379-445b-9b86-9b73694d8aea.png)

**Comment by MAKOMO** [comment]
Thanks for your report! Could you please clarify what exactly you mean by "touching cursor to any line on graph"? Are you running Artisan on Windows 11? Could you please send us your Artisan log file to investigate this one. For this please hold the ALT key and click the plus icon in the upper left corner. This should open an email with the log file attached. Send this please to info@artisan.plus. Thank you very much for your support!

**Comment by SAS613** [comment]
Maybe I posted too soon.  Older versions just display x=2:40  y=300.  I think Time- 2:40; Temp=300 is better.  I think it should be in bold though.
Moshe
