### ISSUE TITLE
Delta BT and ET missing from roasting report 0.9.8 mac

### ISSUE THREAD

**Issue by Smulfhunter** [artisan-roaster-scope/artisan#84]
[report_0.9.7.pdf](https://github.com/artisan-roaster-scope/artisan/files/94103/report_0.9.7.pdf)
[report_0.9.8.pdf](https://github.com/artisan-roaster-scope/artisan/files/94104/report_0.9.8.pdf)

[16_01_13_P609 Gatuya.alog.zip](https://github.com/artisan-roaster-scope/artisan/files/94105/16_01_13_P609.Gatuya.alog.zip)

upgraded to 0.9.8 but had to revert back to 0.9.7 because delta BT and ET curves are missing from the roasting report in 0.9.8. the same log file created by 0.9.8 when loaded in 0.9.7 works as before.  

os x 10.9.5

**Comment by MAKOMO** [comment]
This is fixed for the next release v0.9.9
