### ISSUE TITLE
Silent error since update to 2.6.0

### ISSUE THREAD

**Issue by pmainguet** [artisan-roaster-scope/artisan#848]
Hello,

I've updated this morning my install from 2.4.6 to 2.6.0 on my Ubuntu machine (was working fine before) but when I tried to launch it via command terminal, nothing happened. sudo install + password, then nothing. I can't find any relevant logs in my /var/log.

I then updated my Linux install as some packages could be updated, but same. I then deinstall and try with 2.4.6 but same happens.

I am basically stuck here with no alternative, while I have to roast a big batch today ...

Anybody facing the same issue ? Any pointers to troubleshooting docs or application level logs that could help me identify the cause ?

Thanks

**Comment by MAKOMO** [comment]
What does happen when you start with 

`# /share/artisan/artisan`

or

`# sudo /share/artisan/artisan'

**Comment by pmainguet** [comment]
Hello @MAKOMO 
Thanks for the quick answer.

I got 

sudo: /share/artisan/artisan: command not found
or
bash: /share/artisan/artisan: No such file or directory

**Comment by MAKOMO** [comment]
Sorry, the paths were wrong `/usr/share/artisan/artisan` is correct.

The error indicates that your system does not support the minimal glibc version which is required by the underlying python process. You need to upgrade your Ubuntu system to run this version of Artisan. Sorry.

**Comment by pmainguet** [comment]
Thanks! Just for my information, was there a change between version 2.4.6 and 2.6.0 regarding the version of this library ?
The software uses to work perfectly before that.

**Comment by MAKOMO** [comment]
Yes, many things changed. Most components got updated. Significant here: Python was upgraded from 3.9.5 to 3.10.2.

The software still works perfectly. Just not supporting your outdated system any longer.

**Comment by pmainguet** [comment]
Thank you very much for your explanation and your reactivity!
