### ISSUE TITLE
Different result saved log file and exported csv file

### ISSUE THREAD

**Issue by alexyun78** [artisan-roaster-scope/artisan#85]
I capture the roasting log file with TC4 connection with BT and ET. Complete roasting, I save the log as "16-02-03_1918.alog" and exported CSV format as "16-02-03_1918_Artisan.CSV"
I load the "16-02-03_1918.alog" and importe "16-02-03_1918_Artisan.CSV" to compare result.
So you can found something wrong CSV  BT and ET values swapped.
Please check below picture and saved log file.

![artisan_alog](https://cloud.githubusercontent.com/assets/9426923/12852207/2e86710a-cc71-11e5-8af9-a8c14df20589.JPG)
![artisan_csv](https://cloud.githubusercontent.com/assets/9426923/12852208/2e89e47a-cc71-11e5-906c-9a60d9f39b2e.JPG)

**Comment by MAKOMO** [comment]
This is a feature that was introduced at one point for a reason I by now forgot. Artisan assumes on CSV import that the ET temperature curve to be mostly above the BT temperature curve. If it detects the opposite it will swap the curves on input.

I will deactivate this auto swap code for the next release (v0.9.9) as it indeed can lead to unintuitive results as in your case.
