### ISSUE TITLE
2.60 and 2.61 and lag at the DROP moment

### ISSUE THREAD

**Issue by procent85** [artisan-roaster-scope/artisan#859]
**Describe the bug**
Hello. In version 2.60 and 2.61 I am experiencing a lag at the DROP moment. 

**To Reproduce**
The earlier stages of roasting the coffee are fine, but at the end when I open the lid and throw the beans into the cooling tray, the DROP temperature and time are marked with a delay. For example: I dropped my coffee at 26% DEV, 12:45 (or 12:48) min. and 207.4 C but Artisan marked DROP as 27%, 12:54 and temp. 203 C. I attached a high resolution screenshot. Please zoom in to the end of the graph, you can see the delay with which Artisan "marked" the drop. This happens every time I roast coffee.

**Expected behavior**
Marking DROP without lag as in previous versions.

**Screenshots**
Please see the attachment.

**Setup (please complete the following information):**
 - Artisan Version 2.60 and 2.61
 - Platform Windows-10
 - Connected devices or roasting machine: Coffed SR5 manual

Please attach your current Artisan settings file (as exported via menu Help >> Save Settings as *.aset) file.
![KOL](https://user-images.githubusercontent.com/57193052/161377200-29ab3f80-582a-44ae-b8e8-37bb0cd1b73b.jpg)
[KOL NR2 4.7KG 26 I 207.4 ST - MAI 3_51 - CH 205 G 0_40 - TP 78 DE 5_37.txt](https://github.com/artisan-roaster-scope/artisan/files/8402252/KOL.NR2.4.7KG.26.I.207.4.ST.-.MAI.3_51.-.CH.205.G.0_40.-.TP.78.DE.5_37.txt)
[artisan-settings - 2.6.1 with lag.txt](https://github.com/artisan-roaster-scope/artisan/files/8402253/artisan-settings.-.2.6.1.with.lag.txt)

Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by procent85** [comment]
I would like to add that I have recently formatted my SSD drive, installed Windows 10 with the latest updates and did a clean installation of Artisan . Unfortunately, there is still lag on my Coffed SR5 machine at the DROP moment. I am posting a high res. screenshot from today's roast. I finished roast at 207.0 C and 12:27 min. 
![xxx](https://user-images.githubusercontent.com/57193052/169227957-d4c32af1-d1d3-4e49-b481-06bfaaefea2c.png)

**Comment by MAKOMO** [comment]
Could you please test the current development build v2.6.1 if that one performs any better and report here?

https://github.com/artisan-roaster-scope/artisan/releases/tag/continuous

**Comment by procent85** [comment]
Hi, after a dozen roasts I can say that this bug has been fixed.

**Comment by MAKOMO** [comment]
Thanks for this confirmation
