### ISSUE TITLE
Raise Artisan Temperature Dispolay Graph Limit from 600F to 800F

### ISSUE THREAD

**Issue by mikeysp** [artisan-roaster-scope/artisan#86]
I would like to increase the artisan display graph to include higher temperatures. My air roaster exceeds 600 degrees F on larger batches and has a safety shutdown of over 700 F. Any advice and/or assistance is appreciated. Thanks, Mike.

**Comment by MAKOMO** [comment]
Under menu Config >> Axis you can set the limits of the visible x- and y-axis to your needs.
