### ISSUE TITLE
Make it easier to switch from backgrount to manual pid

### ISSUE THREAD

**Issue by vince2848** [artisan-roaster-scope/artisan#860]
Add button the possibility to add button to change from background to manual pid

**Comment by bigl00z3** [comment]
You can already do this (I do).

Just create a [custom button](https://artisan-scope.org/docs/events/), and if you have a quick look at the `help` function under the `Config/Events.../Buttons` tab you will see under Artisan commands:

<img width="804" alt="image" src="https://user-images.githubusercontent.com/8886922/161400257-bd81594a-077a-4484-8850-052b6c0a2b86.png">

There is (by experience) very little that Artisan can't do, but there is a lot where users (including me) don't read the doc well enough...      

Have a great day.

Nico
