### ISSUE TITLE
Getting Victor 86B wokring with artisan

### ISSUE THREAD

**Issue by rhys100** [artisan-roaster-scope/artisan#861]
Hi am I am using windows 10 and Victor 86B meter and have this fine working with Roast Monitor from coffee snobs but cant get it to work with artisian i believe because of driver issues

When using 86b with Artisian it seems to require a com port.

The driver im using that works with Roast Monitor does not give the usb device a com port
screenshot 1 - https://i.imgur.com/wKjlUO3.png
screenshot 2 - https://i.imgur.com/gVLEC8r.png

However if  i try any CP2102 drivers (tried alot) which gives assigns the usb to COM4 the driver and device always seems to fail
screenshot 1 https://i.imgur.com/IFdKDbs.png
screenshot 2: https://i.imgur.com/c4kfQ3Z.png

Is there a driver that is known to work or any tips to get this driver to be valid on the com4 port or any other suggestions?

**Comment by MAKOMO** [comment]
There seem to be variants of that device that do not work with Artisan. The one supported by Artisan comes with a build-in USB2serial converter using the CP2102 chipset (and requires thus the corresponding driver). There are other variants that connect directly as USB HID. Those later devices are not supported.
