### ISSUE TITLE
Mastech MS6514 

### ISSUE THREAD

**Issue by firo84** [artisan-roaster-scope/artisan#90]
Hi,

I'm using Mac OSX 10.11 (El Capitan). Which driver should I use for Mastech MS6514 in order to work?
Because I noticed there are few sources for the driver.

Thank you.

**Comment by MAKOMO** [comment]
I heared the Mastech needs a SiLabs CP201x driver.  You can download the v4.x from  here https://www.silabs.com/products/mcu/Pages/USBtoUARTBridgeVCPDrivers.aspx
