### ISSUE TITLE
Artisan 2.6.0 PID control messages for TC4 hardware PID

### ISSUE THREAD

**Issue by hiroyuki2080** [artisan-roaster-scope/artisan#910]
**Describe the bug**

There are 2 issues - the first one is not a realy an issue on TC4 but the second one affects to the ramp stage.
First issue
   At the first batch and PID start, PID control sends out PID parameters and SV in one block(see serial monitor below).
  This happens only at the first batch of Artisan starts up.
Second issue
   PID control sends out PID parameters and SV is coming up in the following second but SV value starts from very low temperature(see serial monitor below)
############
##First batch##
############
# Active channels set to 1200
UNITS;C
FILT;70,70,70,70
READ
27,213,210,0,0,0.01
READ
27,213,210,0,0,0.01
ot2 50
ot1 50
READ
27,213,210,0,0,0.01
READ
27,213,211,0,0,0.01
PID;T;0.1;0.5;0.1
PID;CHAN;1
PID;CT;1000
PID;LIMIT;0;100
PID;ON
PID;SV;159.0                < SV in the same block with PID parameters
READ
27,213,211,0,0,0.01
PID;SV;4.72                  <SV starts from very low temperature
READ
27,214,211,0,0,0.01
PID;SV;6.5
READ
27,214,211,0,0,0.01
PID;SV;8.27
PID;OFF
CHAN;1200
# Active channels set to 1200
UNITS;C
FILT;70,70,70,70
READ
27,214,211,0,0,0.01
READ
27,214,211,0,0,0.01
ot2 50
ot1 50
READ
27,214,211,0,0,0.01
READ
27,214,211,0,0,0.01
READ
27,214,211,0,0,0.01
PID;T;0.1;0.5;0.1
PID;CHAN;1
PID;CT;1000
PID;LIMIT;0;100
PID;ON
READ
27,214,211,0,0,0.01
PID;SV;6.81             <SV starts from very low temperature
READ
27,214,212,0,0,0.01
PID;SV;8.58
READ
27,214,212,0,0,0.01
PID;SV;10.36
PID;OFF

Best regards
Hiroyuki Yamamoto

**To Reproduce**

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - Artisan Version [e.g. v2.4.4]:  v2.6.0
 - Artisan Build (number in brackets shown in the about box) [e.g. 97e6dec]: 7088095
 - Version [e.g. 22]:
 - Platform (Mac/Windows/Linux + OS version) [e.g. macOS 10.15.3]: Windows 10
 - Connected devices or roasting machine [e.g. Probatone 5]:  TC4

**Additional context**

Please attach your current Artisan settings file (as exported via menu Help >> Save Settings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._
![PID1](https://user-images.githubusercontent.com/40195495/175997693-28db57e9-db04-4548-9ec6-6435d2c481b2.jpg)
![PID2](https://user-images.githubusercontent.com/40195495/175997724-708308ec-00f8-4efd-8740-878dea166482.jpg)
[artisan-settings.aset.txt](https://github.com/artisan-roaster-scope/artisan/files/8994330/artisan-settings.aset.txt)

**Comment by MAKOMO** [comment]
I don't understand the first part of the issue. TC4 commands are not send in blocks, but as individual commands. The initial SV after initializing the TC4 PID is just part of that initialization.

The low SV might be due to a bug in the Ramp/Soak processing within Artisan. I have to check.

**Comment by hiroyuki2080** [comment]
Thank you for looking into the issue. The first one is not really a matter but the second issue makes higher ramp speed than the one starting from a normal current temperature after a warming period.

**Comment by MAKOMO** [comment]
I made a modification to the code such that the SV is not initialized on PID initialization if in Ramp/Soak mode.

Regarding the second issue: the SV Ramp/Soak pattern starts always with SV 0. Thus it is expected that after turning the PID on the RS SV starts from very low target temperatures.  However, it will reach the target temperature within the 2min as defined by your first RS item. See attached image.

To start from a different SV you would introduce a first RS item with just a Soak part at minimal duration (00:01) to set your starting SV.

Does this help?

<img width="1213" alt="Screenshot 2022-07-05 at 15 49 41" src="https://user-images.githubusercontent.com/13909011/177343678-3dd485bd-6a15-4a9e-9a21-1f83dea1c376.png">

<img width="1214" alt="Screenshot 2022-07-05 at 15 51 12" src="https://user-images.githubusercontent.com/13909011/177343695-4c7a6ba6-57f3-4e70-92a9-00bedb08ed35.png">
