### ISSUE TITLE
Ozturk OKS 1.5 Drivers/connection issues 

### ISSUE THREAD

**Issue by madskillsman** [artisan-roaster-scope/artisan#916]
Hey there, I am trying to get my Ozturk OKS 1.5 to work with Artisan. I am running into the issue of Ozturk having horrible customer support, and not being able to get it to connect. I cannot figure out what driver to use (to the best of my knowledge I have tried all that could work) and continue to get MODBUS communication errors. 

I have a USB to USB type C cable plugged in from my MacBook pro strait to the roaster. I am running the latest version of artisan. Is there a driver that is known to work that I should try? Is there something else that I am missing? Any help would be amazing, thank you!

**Comment by MAKOMO** [comment]
All I can contribute here is that there are known issues with non-Apple USB-to-USB-C under the latest macOS.
