### ISSUE TITLE
HeatSnob USB Thermocouple Support

### ISSUE THREAD

**Issue by gobears98** [artisan-roaster-scope/artisan#92]
I figured out how to interface to the HeatSnob USB thermocouple, using hid_api.
I have 2 devices working well with Artisan, using and external application interface.

If there is any interest in building in official support for the device, I could provide the source code.
Its actually quite simple code, just a few hundred lines.

BTW, the heatsnob device is inexpensive ($60), compact, well designed and very well built.
You can connect as many as your have USB ports.

They are very pupular in Australia where they originate, but also available in the USA.
Not sure about the rest of the world.

Anyway, I am really excited to try out Artisan as an alternative to the RoastMaster software they ship with their product.

Cheers,
~Bruce

**Comment by MAKOMO** [comment]
Please share your code and we will see if it can be integrated cross-plattform

**Comment by gobears98** [comment]
`/*******************************************************
 HeatSnob USB HID interface code
 * Bruce W. McGaughy
 * 
 * Based on, and following same license as:
 * 
 * Windows HID simplification

 Alan Ott
 Signal 11 Software

 8/22/2009

 Copyright 2009, All Rights Reserved.
 
 This contents of this file may be used by anyone
 for any reason without any conditions and may be
 used as a starting point for your own applications
 which use HIDAPI.
 * 
********************************************************/

#include <stdio.h>
#include <wchar.h>
#include <string.h>
#include <stdlib.h>
#include "hidapi.h"
#include <math.h>

// Headers needed for sleeping.
#ifdef _WIN32
	#include <windows.h>
#else
	#include <unistd.h>
#endif

// Dump verbose information if user passes "info" string to application.
static bool  VERBOSE_MODE = false;

//////////////////////////////////////////////////////////////////////////
// Given the buffer of bytes from reading USB HID of Maxim 31855,, read the 
// thermocouple and internal chip temperature.
// INPUT:  buf = Buffer of all bytes read from USB HID interface.
//               NOTE: The 32 bit output of the Maxim 31855 is stored in 
//                     bytes 3, 4, 5, and 6, with the 0th bit in the right 
//                     most bit of byte 6, and the 31st bit in the left most
//                     bit of byte 3.
// OUTPUTS: tc = The thermocouple temperature reading in celsius.
//          it = Internal temperature of the Maxim chip.
//////////////////////////////////////////////////////////////////////////


void get_temps( unsigned char* buf, double& tc, double& it ){
    
    // Read the bits from bit 31 down to bit 0. The bit_index indicates
    // which bit we are working on.
    int bit_index = 31;
    
    // Initialize the outputs to zero, and accumulate temperature with each bit
    tc = 0.0;
    it = 0.0;
    
    // The most significant bit of TC temperature is 4096 * 0.25 celsius.
    // Each lower bit cuts the tc_mult in half
    double tc_mult = 4096.0;

    // Most signficant bit of internal tempearture is 1024 * .0625 celsius,
    // Each lower bit cuts the it_mult in half.
    double it_mult = 1024.0;

    // Read the bits from 31...0 by iterating each byte from 3...7 and then
    // each bit from 7...0 within each byte.
    for (int i = 3; i < 7; i++){
        for ( int j = 7 ; 0 <= j ; j--){
            // Get the bit value by left shifting j bits and masking with 1
            int bit_val = (buf[i] >> j) & 0x01;

            // The 31st bit is the sign of TC, 
            // Reverse sign of multiplier if bit is 1:
            if ( bit_index == 31 && bit_val == 1){
                tc_mult *= -1.0;
            }else if ( bit_index <= 30 && bit_index >= 18){
                // Bits 30... 18 are the bits of tc temperature
                tc += bit_val * tc_mult * 0.25;
                tc_mult /= 2;
            }else if (bit_index == 15 && bit_val == 1 ){
                // The 15st bit is the sign of IT, 
                // Reverse sign of multiplier if bit is 1
                it_mult *= -1.0;
            }else if ( bit_index <= 14 && bit_index >= 4){
                // Bits 14...4 are the bits of it:
                it += bit_val * it_mult * 0.0625;
                it_mult /= 2;
            }
            bit_index--;
        }
    }

    if ( VERBOSE_MODE ){
        
        printf("\n\nFirst 8 bytes of USB HID output in hex format:\n");
        for (int i = 0; i < 8; i++)
                printf("%02hhx ", buf[i]);
        
        printf("\nAnd in Binary format:\n");
        for (int i = 0; i < 8; i++){
            char b = buf[i];
            for ( int j = 7 ; 0 <= j ; j--){
                printf("%d ", (b & ( 1 << j )) >> j);
                //printf("%d ", (b >> j) & 0x01);

            }
            printf("\n");
        }
    }
}

int main(int argc, char* argv[])
{
	

#ifdef WIN32
	UNREFERENCED_PARAMETER(argc);
	UNREFERENCED_PARAMETER(argv);
#endif

        // Check if user requests "verbose" mode, then dump debug info.
        if (argc == 2 && strcmp( "verbose", argv[1] ) == 0 ){
            printf(  "%s %s ", argv[0], argv[1] );
            VERBOSE_MODE = true;
        }
        
        ////////////////////////////////////////////////////////////////////////////////
        // Enumerate all the devices, and look for heat snob devices:
        ////////////////////////////////////////////////////////////////////////////////
        
	struct hid_device_info *devs, *cur_dev;
        devs = hid_enumerate(0x0, 0x0);
	cur_dev = devs;	
        
        // And remember heat snob device paths:
        char paths[256][256];
        int num_paths = 0;
        
        while (cur_dev) {
            if ( VERBOSE_MODE ){
                printf("Device Found\n  vendor id: %04hx product id:%04hx\n serial_number: %ls", cur_dev->vendor_id, 
                        cur_dev->product_id, cur_dev->serial_number);
                printf("\n");
                printf("  Manufacturer: %ls\n", cur_dev->manufacturer_string);
                printf("  Product:      %ls\n", cur_dev->product_string);
                printf("  Release:      %hx\n", cur_dev->release_number);
                printf("  Interface:    %d\n",  cur_dev->interface_number);
                printf("  Path:    %s\n",  cur_dev->path);
                printf("\n");
            }
            // Check if we match the heat snob vendor & product id, then remember the path:
            if ( cur_dev->vendor_id == 0x4d8 && cur_dev->product_id == 0xf899 ){
                strcpy( paths[num_paths], cur_dev->path);
                if ( VERBOSE_MODE ){
                    printf("Found a heatsnob device: %s\n", paths[num_paths]);
                }
                ++num_paths;
            }
            cur_dev = cur_dev->next;
        }
	hid_free_enumeration(devs);

        ////////////////////////////////////////////////////////////////////////////////
        // Read tempereature for each of the usb devices:
        ////////////////////////////////////////////////////////////////////////////////
        
        // Arrays to hold thermocouple and internal temperatures:
        double tc_temps[256];
        double it_temps[256];
        
        unsigned char buf[256];
	hid_device *handle;
        
        // Iterate each device path:
        for (int p = 0 ; p < num_paths ; ++ p){
            // Set up the command buffer for reading:
            memset(buf,0x00,sizeof(buf));
            buf[0] = 0x01;
            buf[1] = 0x81;

            // Open the device by path:
            handle = hid_open_path( paths[p] );

            if (!handle) {
                printf("ERROR: unable to open device with path: %s \n", paths[p] );
            }

            // Read the device:
            
            int res = hid_read(handle, buf, sizeof(buf));
            if ( VERBOSE_MODE){
                if (res == 0)
                    printf("waiting...\n");
                if (res < 0){
                    printf("Error: Unable to read device with path: %s \n", paths[p]);
                }

            }
                
            
            hid_close(handle);
        
            // Extract the temperatures:
            get_temps( buf, tc_temps[p], it_temps[p] );
            
            if ( p == 0 ){
                printf("%03.2f", tc_temps[p] );
            }else{
                printf(",%03.2f", tc_temps[p]);
            }
        }
        
        printf("\n");
        
        if ( VERBOSE_MODE ){
            for ( int p = 0 ; p < num_paths ; ++p ){
                printf("Device Path:  %s,  thermocouple temp: %03.2f,  internal chip temp: %03.2f\n", paths[p], tc_temps[p], it_temps[p] );
            }
        }

	/* Free static HIDAPI objects. */
	hid_exit();

#ifdef WIN32
	system("pause");
#endif

	return 0;
}
`

**Comment by gobears98** [comment]
Above is the file.
It is based on the hidtest.c application in the mac directory of hid_api_0.7.0 distribution.

The makefile is there too. Just copy/paste my code above into hidtest.c (in the mac directory), call make, and it should work fine. Since hid_api is cross-platform, and has the similar directories for windows & linux with minimal differences, it should be straightforward to plug-in. Especially if you have an HID USB framework already built into Artisan. Then its even easier.

**Comment by gobears98** [comment]
I added some comments to help understand the data layout of the Maxim chip.
And, added support to catch and report faults like open circuit or short to gnd.

I will insert the code into the next message.

**Comment by gobears98** [comment]
`/*******************************************************
 HeatSnob USB HID interface code
 * Bruce W. McGaughy
 * 
 * Based on, and following same license as:
 * 
 * Windows HID simplification

 Alan Ott
 Signal 11 Software

 8/22/2009

 Copyright 2009, All Rights Reserved.
 
 This contents of this file may be used by anyone
 for any reason without any conditions and may be
 used as a starting point for your own applications
 which use HIDAPI.
 * 
********************************************************/

#include <stdio.h>
#include <wchar.h>
#include <string.h>
#include <stdlib.h>
#include "hidapi.h"
#include <math.h>

// Headers needed for sleeping.
#ifdef _WIN32
	#include <windows.h>
#else
	#include <unistd.h>
#endif

// Dump verbose information if user passes "info" string to application.
static bool  VERBOSE_MODE = false;

//////////////////////////////////////////////////////////////////////////
// Maxium 31855: Tempearture measurement chip of Heatsnob:
// https://www.adafruit.com/datasheets/MAX31855.pdf
// 
// The chip outputs 32 bits of data, which are packed in 4 chars which are
// in the output buffer of HID read(), starting at 4th char 
//
// Summary of bits: 31 : Sign bit of Thermocouple temperature, 1 = negative
//                  30 : MDB Thermocouple: 1024c = 4096c * 0.25 c 
//                  ...  Bits 29...19 are from 512c ... 0.5c
//                  18 : LSB Thermocouple:  0.25c = 1 * 0.25c 
//                  17 : Reserved, always 0.
//                  16 : Fault bit, 1=fault
//                  15 : Sign bit of internal chip temperature, 1 = negative
//                  14 : Internal Chip Temp MSB: 64c = 1024c * .0625c
//                  ...  Bits 13...5 are from 32c ...  0.25c
//                  4 :  LSB of internal chip temperature:  0.0625
//                  3 :  Reserved, always 0.
//                  2 :  1 = short to vcc
//                  1 :  1 = short to gnd
//                  0 :  1 = open circuit
//////////////////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////
// Given the buffer of bytes from reading USB HID of Maxim 31855,, read the 
// thermocouple and internal chip temperature.
// INPUT:  buf = Buffer of all bytes read from USB HID interface.
//               NOTE: The 32 bit output of the Maxim 31855 is stored in 
//                     bytes 4, 5, 6, and 7 (indexes 3,4,5,6), 
//                     with the 0th bit in the right 
//                     most bit of byte 6, and the 31st bit in the left most
//                     bit of byte 3.
// OUTPUTS: tc = The thermocouple temperature reading in celsius.
//          it = Internal temperature of the Maxim chip.
//
//////////////////////////////////////////////////////////////////////////



void get_temps( unsigned char* buf, double& tc, double& it, bool& fault, bool& short_vcc, bool& short_gnd, bool& open_circuit ){
    
    fault = short_vcc = short_gnd = open_circuit = false;
    
    // Read the bits from bit 31 down to bit 0. The bit_index indicates
    // which bit we are working on.
    int bit_index = 31;
    
    // Initialize the outputs to zero, and accumulate temperature with each bit
    tc = 0.0;
    it = 0.0;
    
    // The most significant bit of TC temperature is 4096 * 0.25 celsius.
    // Each lower bit cuts the tc_mult in half
    double tc_mult = 4096.0;

    // Most signficant bit of internal tempearture is 1024 * .0625 celsius,
    // Each lower bit cuts the it_mult in half.
    double it_mult = 1024.0;

    // Read the bits from 31...0 by iterating each byte from 3...7 and then
    // each bit from 7...0 within each byte.
    for (int i = 3; i < 7; i++){
        for ( int j = 7 ; 0 <= j ; j--){
            // Get the bit value by left shifting j bits and masking with 1
            int bit_val = (buf[i] >> j) & 0x01;

            // The 31st bit is the sign of TC, 
            // Reverse sign of multiplier if bit is 1:
            if ( bit_index == 31 && bit_val == 1){
                tc_mult *= -1.0;
            }else if ( bit_index <= 30 && bit_index >= 18){
                // Bits 30... 18 are the bits of tc temperature
                tc += bit_val * tc_mult * 0.25;
                tc_mult /= 2;
            }else if (bit_index == 16 && bit_val == 1){
                fault = true;
            }else if (bit_index == 15 && bit_val == 1 ){
                // The 15st bit is the sign of IT, 
                // Reverse sign of multiplier if bit is 1
                it_mult *= -1.0;
            }else if ( bit_index <= 14 && bit_index >= 4){
                // Bits 14...4 are the bits of it:
                it += bit_val * it_mult * 0.0625;
                it_mult /= 2;
            }else if ( bit_index == 2 && bit_val == 1 ){
                short_vcc = true;
            }else if ( bit_index == 1 && bit_val == 1 ){
                short_gnd = true;
            }else if ( bit_index == 0 && bit_val == 1 ){
                open_circuit = true;
            }
           
            bit_index--;
        }
    }

    if ( VERBOSE_MODE ){
        
        printf("\n\nFirst 8 bytes of USB HID output in hex format:\n");
        for (int i = 0; i < 8; i++)
                printf("%02hhx ", buf[i]);
        
        printf("\nAnd in Binary format:\n");
        for (int i = 0; i < 8; i++){
            char b = buf[i];
            for ( int j = 7 ; 0 <= j ; j--){
                printf("%d ", (b & ( 1 << j )) >> j);
                //printf("%d ", (b >> j) & 0x01);

            }
            printf("\n");
        }
    }
}

int main(int argc, char* argv[])
{
	

#ifdef WIN32
	UNREFERENCED_PARAMETER(argc);
	UNREFERENCED_PARAMETER(argv);
#endif

        // Check if user requests "verbose" mode, then dump debug info.
        if (argc == 2 && strcmp( "verbose", argv[1] ) == 0 ){
            printf(  "%s %s ", argv[0], argv[1] );
            VERBOSE_MODE = true;
        }
        
        ////////////////////////////////////////////////////////////////////////////////
        // Enumerate all the devices, and look for heat snob devices:
        ////////////////////////////////////////////////////////////////////////////////
        
	struct hid_device_info *devs, *cur_dev;
        devs = hid_enumerate(0x0, 0x0);
	cur_dev = devs;	
        
        // And remember heat snob device paths:
        char paths[256][256];
        int num_paths = 0;
        
        while (cur_dev) {
            if ( VERBOSE_MODE ){
                printf("Device Found\n  vendor id: %04hx product id:%04hx\n serial_number: %ls", cur_dev->vendor_id, 
                        cur_dev->product_id, cur_dev->serial_number);
                printf("\n");
                printf("  Manufacturer: %ls\n", cur_dev->manufacturer_string);
                printf("  Product:      %ls\n", cur_dev->product_string);
                printf("  Release:      %hx\n", cur_dev->release_number);
                printf("  Interface:    %d\n",  cur_dev->interface_number);
                printf("  Path:    %s\n",  cur_dev->path);
                printf("\n");
            }
            // Check if we match the heat snob vendor & product id, then remember the path:
            if ( cur_dev->vendor_id == 0x4d8 && cur_dev->product_id == 0xf899 ){
                strcpy( paths[num_paths], cur_dev->path);
                if ( VERBOSE_MODE ){
                    printf("Found a heatsnob device: %s\n", paths[num_paths]);
                }
                ++num_paths;
            }
            cur_dev = cur_dev->next;
        }
	hid_free_enumeration(devs);

        ////////////////////////////////////////////////////////////////////////////////
        // Read tempereature for each of the usb devices:
        ////////////////////////////////////////////////////////////////////////////////
        
        // Arrays to hold thermocouple and internal temperatures:
        double tc_temps[256];
        double it_temps[256];
        
        unsigned char buf[256];
	hid_device *handle;
        
        // Iterate each device path:
        for (int p = 0 ; p < num_paths ; ++ p){
            // Set up the command buffer for reading:
            memset(buf,0x00,sizeof(buf));
            buf[0] = 0x01;
            buf[1] = 0x81;

            // Open the device by path:
            handle = hid_open_path( paths[p] );

            if (!handle) {
                printf("ERROR: unable to open device with path: %s \n", paths[p] );
            }

            // Read the device:
            
            int res = hid_read(handle, buf, sizeof(buf));
            if ( VERBOSE_MODE){
                if (res == 0)
                    printf("waiting...\n");
                if (res < 0){
                    printf("Error: Unable to read device with path: %s \n", paths[p]);
                }

            }
                
            
            hid_close(handle);
        
            // Extract the temperatures and catch any faults
            bool fault, short_vcc, short_gnd, open_circuit;
            get_temps( buf, tc_temps[p], it_temps[p], fault, short_vcc, short_gnd, open_circuit );
            
            // Report faults if requested.
            if (VERBOSE_MODE){
                if (fault  )
                    printf("Error: Fault reported by thermocouple chip.\n");
                if ( short_vcc  )
                    printf("Error: Short to vcc reported by thermocouple chip.\n");
                if ( short_gnd )
                    printf("Error: Short to gnd reported by thermocouple chip.\n");
                if ( open_circuit )
                    printf("Error: Open circuit reported by thermocouple chip.\n");
            }
            
            if ( p == 0 ){
                // Print the first temperature for Artisan
                printf("%03.2f", tc_temps[p] );
            }else{
                // Print the other temperatures for Artisan if available.
                printf(",%03.2f", tc_temps[p]);
            }
        }
        
        printf("\n");
        
        if ( VERBOSE_MODE ){
            for ( int p = 0 ; p < num_paths ; ++p ){
                printf("Device Path:  %s,  thermocouple temp: %03.2f,  internal chip temp: %03.2f\n", paths[p], tc_temps[p], it_temps[p] );
            }
        }

	/* Free static HIDAPI objects. */
	hid_exit();

#ifdef WIN32
	system("pause");
#endif

	return 0;
}
`

**Comment by bubbaj3** [comment]
I just downloaded 0.9.9 and the heatsnob prob doesn't seem to work.  Does anyone know if this has been incorporated into the latest release?  I probably don't have it configured correctly.

**Comment by MAKOMO** [comment]
The provided code is not in Python and no push was provided. Artisan does for now not provide support for any USB HID devices. This might never change.
