### ISSUE TITLE
Asian plus document upload issue

### ISSUE THREAD

**Issue by elguapo1911** [artisan-roaster-scope/artisan#920]
I was in artisan plus adding recently purchased coffeebeans. I normally upload the PDF with the organic certification but it won't let me upload a PDF format? I swear I've done this before. Any suggestions?

**Comment by MAKOMO** [comment]
While not in edit mode of the new bean entry, just click on the "Upload documents" link to open the Documents Uploader widget which allows you to select a set of documents to be attached via the "+".

<img width="1034" alt="Screenshot 2022-07-21 at 17 31 54" src="https://user-images.githubusercontent.com/13909011/180254338-65d6bb59-75aa-41d9-a19b-6535ee1e200b.png">

Hope this works for you!

**Comment by elguapo1911** [comment]
I'll give it a try out of edit mode. Thanks!

**Comment by MAKOMO** [comment]
Oh, no. You should be "NOT" in edit mode.

**Comment by elguapo1911** [comment]
Lol ok, my bad
