### ISSUE TITLE
Silent Uninstaller

### ISSUE THREAD

**Issue by peterbeck** [artisan-roaster-scope/artisan#93]
Is there any switch to run the uninstaller silent (on windows systems) ? "/S" does not work with the uninstaller. 
Would be nice as the previous version needs to be removed before upgrading to the latest one, which is a little problem with automated software deployments...

Regards
Peter

**Comment by MAKOMO** [comment]
Thanks for the hint. I never thought about this as I am not using any Windows machine. The Windows installer did not support silent install nor uninstall. Just added this to the build script. Will be part of the v1.0 release.
