### ISSUE TITLE
Hide and show sliders with Websocket Command

### ISSUE THREAD

**Issue by oscarquiroz94** [artisan-roaster-scope/artisan#932]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to control the power from slider and other times I don't, is important to hide slider to avoid mistakes while the scope is run.

**Describe the solution you'd like**
Using a Websocket Command I want to hide o show sliders while the scope is run.

**Comment by MAKOMO** [comment]
We do not plan to have the Artisan UI being controlled by an external hardware or software.
