### ISSUE TITLE
Support for 4k monitor

### ISSUE THREAD

**Issue by MarcelPr** [artisan-roaster-scope/artisan#95]
All the dialog windows (such as editing events or working with designer) are small to clearly show the variable numerical values. 

Thanks for the great software.

**Comment by MarcelPr** [comment]
![4ka](https://cloud.githubusercontent.com/assets/19701401/15757422/7f9c4e66-28d3-11e6-9c48-8e4f4f574d43.jpg)

**Comment by MarcelPr** [comment]
![4kb](https://cloud.githubusercontent.com/assets/19701401/15757443/98a725d4-28d3-11e6-9077-382a0346e83d.jpg)

**Comment by MAKOMO** [comment]
Could you try the actual v1.0.0b4 builds? Please test both the regular Python2 Windows as well as the Python3 build (artisan-win-1.0.0b4-py3.zip)

**Comment by utilitalian** [comment]
I also have this issue running v1.0.1 on my new Surface Pro 4. Temp displays need a microscope to see, and many of the words and numbers are cut off in the windows.

**Comment by MAKOMO** [comment]
A first beta version of the Qt5-based Artisan v1.2 has been released now that supports high-resolution screens better.
