### ISSUE TITLE
Focus is automatically changed from "OK" button to "Restore Defaults" button in "Axes" dialog

### ISSUE THREAD

**Issue by bfailing** [artisan-roaster-scope/artisan#973]
**Describe the bug**
Focus is automatically changed from the "OK" button to "Restore Defaults" button in the "Axes" dialog upon clicking in any field.  Changes made in that dialog are lost and defaults are restored upon hitting Enter.  However, if focus was not automatically changed, then hitting Enter would save the changes as expected.

**To Reproduce**
1. Go to Config > Axes
2. Note that the "OK" button is focused
3. Click in any field (e.g., "100% Event Step")
4. Observe the focus automatically change to the "Restore Defaults" button

**Expected behavior**
Focus remains on the "OK" button while making changes in the dialog.

**Setup (please complete the following information):**
 - Artisan Version [e.g. v2.4.4]: v2.6.0
 - Platform (Mac/Windows/Linux + OS version) [e.g. macOS 10.15.3]: Windows 10
 - Connected devices or roasting machine [e.g. Probatone 5]: Arduino/TC4

**Comment by MAKOMO** [comment]
Fixed. Commit 238bea3326283b28015a7eb87ad18d8f06adb36b
