### ISSUE TITLE
AUC lcd 3 digits

### ISSUE THREAD

**Issue by s4reea** [artisan-roaster-scope/artisan#977]
LCD auc screen is only 3 digits limited and in case it goes above 1000 then it goes null. 

i use it for consistency between roasts on different days and weather conditions. 
calc it from TP

if you can please enable a 4 digit lcd screen then it will be great

**Comment by MAKOMO** [comment]
Fixed by commit e50f16c49c10821561f5dc7843fb874aced2db90.
