### ISSUE TITLE
Issue: Phidget barometer raw data

### ISSUE THREAD

**Issue by s4reea** [artisan-roaster-scope/artisan#982]
Artisan in ambient readings reads the raw hectoPascals of the phidget for exmple 1010.5hPa
while in phidget control panel I see the actual barometric pressure 90.1k Pa

is this a bug ?

**Comment by MAKOMO** [comment]
Did you specify your elevation in the Ambient tab?

**Comment by s4reea** [comment]
Yeah
 997 meters

> Did you specify your elevation in the Ambient tab?
Yes
997m

**Comment by MAKOMO** [comment]
It is the other way around. The Phidget Control Panel outputs the raw atmospheric pressure which is used by Artisan together with the ambient temperature (defaults to 23C) and the given MASL/hasl to compute the atmospheric pressure using the following function.

```Python
    # computes the barometric pressure from
    #   aap:  atmospheric pressure in hPa
    #   atc:  temperature in Celsius
    #   hasl: height above sea level in m
    # see https://www.wmo.int/pages/prog/www/IMOP/meetings/SI/ET-Stand-1/Doc-10_Pressure-red.pdf
    @staticmethod
    def barometricPressure(aap, atc, hasl):
        return aap * pow((1 - ((0.0065*hasl) / (atc + (0.0065*hasl) + 273.15))),-5.257)
```

Cannot see anything wrong here and the readings I get look fine.

**Comment by s4reea** [comment]
![image](https://user-images.githubusercontent.com/7386520/195556006-da2e65e3-be28-476d-8102-55a9be9abb3e.png)

![image](https://user-images.githubusercontent.com/7386520/195556104-d5faa56e-b294-4ab5-bfa6-6964978d65dc.png)

they are both from same sensor

and when I put at devices amsl 0 height instead of 997
![image](https://user-images.githubusercontent.com/7386520/195556595-da0583ad-5a41-4f5f-88bd-c382fa28b3a9.png)

The right one, So I think we should choose only one settings... phidget or manual height input ?

**Comment by MAKOMO** [comment]
I don't understand your question. Sorry.

**Comment by s4reea** [comment]
there is difference between actual measured pressure of barometer phidget and the shown value in artisan Roast properties. 

I found the cause of this bug.

If I go to devices -> ambient -> and type the masl there, (997) it shows different pressure (wrong pressure), if I leave it 0, the pressure shown in artisan is right

**Comment by MAKOMO** [comment]
This is strange. The pressure Artisan displays needs the correct MASL to be correct as it computes it from the raw atmospheric pressure the sensor is delivering. The Phidget module itself is not able to store a MASL value. So maybe your sensor is measuring wrong and is defect or the value you compare the result with is wrong.

**Comment by s4reea** [comment]
I understand what you say. 
I think this thing worths a check
As I have other pressure sensors from Aqara and they are all around 90.5-91kpa
