### ISSUE TITLE
Properties dialog "+" Button greyed out.

### ISSUE THREAD

**Issue by Tobias007** [artisan-roaster-scope/artisan#984]
## Expected Behavior

Roast properties can be saved with the "+" Button in the propoerties dialog.

## Actual Behavior

"+" button greyed out

## Steps to Reproduce the Problem

  1. Cmd-T
  2. Try to push "+" - no reaction as greyed out.
  3.

## Specifications

  - Artisan Version: 2.6.0
  - Artisan Build (number in brackets shown in the about box): 755533
  - Platform (Mac/Windows/Linux + OS version): Mac 12.5.1
  - Connected devices or roasting machine: WebSocket / own device

Please attach your current Artisan settings file (as exported via menu Help >> Save Settings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._
[artisan-settings.aset.zip](https://github.com/artisan-roaster-scope/artisan/files/9793687/artisan-settings.aset.zip)

**Comment by roasterdave** [comment]
The + button will be disabled and grey when either of following is true.  
- Title is the default "Roaster Scope"
or
- Green Weight is 0

Make entries in both fields to enable the button.
